### ISSUE TITLE
Travis g++-8 is broken due to linker errors against filesystem library

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#1008]
Currently our travis builds with g++-8 are failing due to linker errors. 
The linker can't find the symbols for filesystem anymore. 
Compiler version `g++-8 (Ubuntu 8.1.0-5ubuntu1~16.04) 8.1.0`

Not sure if an update to the ppa toolchain broke somehing here.

@marehr @h-2 do you have suggestions?

**Comment by h-2** [comment]
I don't think it's related to anything that we've done, let's wait for now...

**Comment by eseiler** [comment]
It's weird, gcc and cmake versions are the same as before, but our cmake script now detects `<filesystem>` as builtin (which would require that it compiles and links without using any `-l` stuff) instead of detecting the `-lstdc++fs` need.
AFAIK it is only builtin beginning with gcc-9

**Comment by rrahn** [comment]
So it is broken then by the package. If it is  changed until Monday, we should hack it in the CMake to still use `-lstdc++fs` for gcc8

**Comment by marehr** [comment]
@eseiler Thank you for investigating. I created a (possible) fix #1015.

**Comment by h-2** [comment]
fixed by #1015
