### ISSUE TITLE
Model header include for variables as a Doxygen Macro

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#1010]
Currently we use this snippet to document the include header for the view variable definitions.

https://github.com/seqan/seqan3/blob/cfea39c4248adeef490b491778231dc32c654507/include/seqan3/range/views/convert.hpp#L33-L36

However, this seems to be a problem for all typedefs and vairable definitions in the library.
I am wondering if we can add a  macro that generates this. Maybe even a functional one, that can generate the path from `__FILE__` macro?

**Comment by smehringer** [comment]
I did a bit of research but I could not find anything usable in this way.

The doxygen special command `\headerfile` does only work for classes and structs.

There is no functional macro to get the current file (at least I could not find one) for doxygens preprocessor.

Do we want a simple doxygen command anyway? something like `\header myfile.hpp` that resolves to the the markdown in rrahn's example?

**Comment by eseiler** [comment]
https://stackoverflow.com/questions/38513580/how-to-create-a-doxygen-link-to-the-same-file

Quite hacky, though

**Comment by smehringer** [comment]
yeah, I saw this but I thought we do not want a bash script or python or whatsoever as to not pollute the repository

**Comment by rrahn** [comment]
No, no weird scripts that need to run when something changes. 

> Do we want a simple doxygen command anyway? something like \header myfile.hpp that resolves to the the markdown in rrahn's example?

I would slightly prefer this.
