### ISSUE TITLE
Warning Levels

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#107]
## GCC warning levels

We have

|                  | `-pedantic -Werror -Wall -Wextra` | `-Wconversion` |  issues |
|------------------|:--------------:|:---------------------:|--------------|
|  SeqAn      | ☑           |     ☐               | this! |
|  range-v3   | ☑ | ☐  | ericniebler/range-v3/issues/680 |
| SDSL         | ? | ☐ | xxsds/sdsl-lite/issues/26 xxsds/sdsl-lite/pull/17 |
| cereal        | ☑ | ☐ | USCiLab/cereal/issues/434
|umeSIMD   | ? | ? | @marehr |

~~Cereal is less important because it is optional and we include it after seqan headers (so we can selectively disable warnings).~~

## Clang

Not relevant, yet. As soon as we have it, we will need `-pedantic -Werror -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic`

**Comment by h-2** [comment]
@cpockrandt Can you look at the SDSL issue, add the warnings to their tests, fix issues and prepare a PR to their repo? If they don't implement at least `-pedantic -Werror -Wall -Wextra` we basically cannot include any of their code, because all our tests will fail => this has a high priority!
Thanks!

**Comment by cpockrandt** [comment]
First PR on this is open: https://github.com/xxsds/sdsl-lite/pull/36

**Comment by marehr** [comment]
@cpockrandt can this be closed?

**Comment by marehr** [comment]
@cpockrandt can this be closed?

**Comment by rrahn** [comment]
I am closing this as it seems there is no response to @marehr pings. 
In case we reopen it or make a new issue with relevance.

**Comment by h-2** [comment]
As we discussed yesterday we still want to add `-Wconversion` and we also realised @marehr broke some things so I would keep the open as  meta-ticket for warning levels.

**Comment by rrahn** [comment]
Yes, but can we not leave issues open for ages if no one is working on this. -wconversion can be a new ticket really

**Comment by h-2** [comment]
This issue is exactly about -Wconversion, that's why I opened it originally. And to track the warning levels of our dependencies. @marehr implemented something to ignore warning levels on dependencies and incidentally broke warning-detection for SeqAn, too. I think this issue is relevant and we should track exactly those questions here, we should we close it and make a new issue?

**Comment by rrahn** [comment]
ok ok ok

**Comment by rrahn** [comment]
@cpockrandt @h-2 Is there any chance we can get this before the release?

**Comment by h-2** [comment]
The warning levels of dependencies are unimportant for us now, because we include them via `-isystem`.

I am **very much** in favour of activating `-Wconversion`.

**Comment by h-2** [comment]
superseded by #896
