### ISSUE TITLE
Doxygen warnings

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#108]
We really need to get rid of the warnings so that we a have clean state once and for all.

This is the list of files and responsible people:

@h-2:
  - [x] `seqan3/include/seqan3/alphabet/adaptation/all.hpp`
  - [x] `seqan3/include/seqan3/alphabet/concept_pre.hpp`
  - [x] `seqan3/include/seqan3/alphabet/nucleotide/all.hpp`
  - [x] `seqan3/include/seqan3/alphabet/nucleotide/dna4.hpp`
  - [x] `seqan3/include/seqan3/alphabet/nucleotide/dna5.hpp`
  - [x] `seqan3/include/seqan3/alphabet/nucleotide/nucl16.hpp`
  - [x] `seqan3/include/seqan3/alphabet/nucleotide/rna4.hpp``
  - [x] `seqan3/include/seqan3/alphabet/nucleotide/rna5.hpp`
  - [x] `seqan3/include/seqan3/alphabet/all.hpp`

@rrahn:
  - [x] `seqan3/include/seqan3/core/concept/core_detail.hpp`
  - [x] `seqan3/include/seqan3/core/concept/iterator_detail.hpp`

@sarahet:
  - [x] `seqan3/include/seqan3/alphabet/aminoacid/aa27.hpp`
  - [x] `seqan3/include/seqan3/alphabet/aminoacid/all.hpp`

@marehr:
  - [x] `seqan3/include/seqan3/alphabet/composition/all.hpp`
  - [x] `seqan3/include/seqan3/alphabet/gap/all.hpp`
  - [x] `seqan3/include/seqan3/alphabet/gap/gap.hpp`

@mariehoffmann:
  - [x] `seqan3/include/seqan3/alphabet/quality/concept.hpp`
  - [x] `seqan3/include/seqan3/alphabet/quality/illumina18.hpp`
  - [x] `seqan3/include/seqan3/container.hpp`

These files should be excluded from doxygen for now:
  - [x] `seqan3/include/seqan3/io/alignment/align_file_detail.hpp`
  - [x] `seqan3/include/seqan3/io/alignment/align_file_in.hpp`
  - [x] `seqan3/include/seqan3/io/alignment/align_file.hpp`
  - [x] `seqan3/include/seqan3/io/sequence/sequence_file_format.hpp`
  - [x] `seqan3/include/seqan3/io/sequence/sequence_file_in.hpp`

**Comment by marehr** [comment]
#127, #133, #139 fixed almost all documentation issues

@h-2 There is only one missing and I don't know what you wanted to do there
https://github.com/seqan/seqan3/blob/410d4d4dd0ba0bbc48391f38f575bd9e1e0e0cb2/include/seqan3/range/container/concatenated_sequences.hpp#L1308-L1320

```log
/home/marehr/develope/seqan3/include/seqan3/range/container/concatenated_sequences.hpp:1312:
warning: unable to resolve reference to `serialisation' for \ref command
```

**Comment by h-2** [comment]
> @h-2 There is only one missing and I don't know what you wanted to express

Just remove the \ref and add (TODO link) behind it :wink:

**Comment by rrahn** [comment]
I kept the ref but added a page in the all.hpp of the IO module. There we can add at some point some description for the serialisation in seqan using cereal. (see #187 for the corresponding issue)
Now we also have CI for the dev/user docu.
