### ISSUE TITLE
Gap Decorator with bulk insertion of gaps and/or a read-only decorator

### ISSUE THREAD

**Issue by mariehoffmann** [seqan/seqan3#1080]
I propose to provide a bulk-insertion feature (given all gaps at start, insert them at once) which can be implemented much more efficiently, since only a constant number of random access operations needs to be done and then the internal state pointers on the gap structure are used to insert the preceding or succeeding gaps.
Additionally, a read-only decorator could be provided for bulk insertion and no option to add or remove gaps later, e.g. for pre-computed alignments.
We could have a unified gap_decorator interface that optionally gets a tag indicating writability. So, default could be the gap_decorator_anchor_block - a modifiable, general-purpose decorator, providing the 'read-only' tag, would then default to the read-only decorator using a bit vector under the hood.

**Comment by mariehoffmann** [comment]
Candidate using bit vector for gap indication and having best read-only results in previous benchmarks is the `sdsl/int_vector` with `rank_support_v5` and `select_support_mcl`.

**Comment by h-2** [comment]
Turned into a card https://github.com/seqan/seqan3/projects/10#card-27119143
