### ISSUE TITLE
config system broken on GCC10

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1087]
@rrahn Can you have a look at this or find someone else who can? I know GCC10 still has a while before release, but learning from the last release, we should try to report regressions quickly, I think.

(see CDash where we have GCC10 nightly builds now)

**Comment by rrahn** [comment]
I have seen this already. I see that I include it for the future milestones.

**Comment by eseiler** [comment]
Related? https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90764
(Type deductions are broken, so `lower_bound{3}` = ICE, `lower_bound<int64_t>{3}` = OK)

**Comment by rrahn** [comment]
Possibly. At some point I will check this.

**Comment by h-2** [comment]
Hm, maybe we can discuss this again in the strategy meeting or find someone else responsible, if you have time constraints, but I really think we should make reporting these things a priority. Especially regressions and things not related to concepts are fixed really quickly by the GCC people.
If fixing them is not a priority we accept the permanent error state in the nightlies and won't see new issues. Then we might as well not have nightlies of gcc10 at all.

**Comment by marehr** [comment]
I could reduce this ICE to

```c++
template <typename> struct a { a(int); };
template <typename> struct b : a<b<int>> { using a<b>::a; };
template <typename c> b(c)->b<c>;
struct e {
  template <typename d> e(d);
} e{b{2}};
```

I'll do a bug report on gcc.

**Comment by marehr** [comment]
Created a bug report https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91121

**Comment by marehr** [comment]
> Related? https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90764
> (Type deductions are broken, so `lower_bound{3}` = ICE, `lower_bound<int64_t>{3}` = OK)

Didn't see your comment. Yes it seems to be the same error.

**Comment by h-2** [comment]
All unit tests now pass with the latest snapshot.

**Comment by h-2** [comment]
Hm, peculiarly, we have a failure again. But only a single one in the config system. @rrahn can you have a look?

**Comment by rrahn** [comment]
I'll look into it.

**Comment by h-2** [comment]
All current errors on GCC10 are not related to the config system.

**Comment by rrahn** [comment]
>All current errors on GCC10 are not related to the config system.

Of course not. It was ingeniously engineered 🚀  😆
