### ISSUE TITLE
secure version checker

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#1101]
1. The version checker uses an insecure connection to the server. Can't we use https?
2. The `command` variable is executed in a `system` call. The following link explains vulnerability issues with this: https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87152177

---

Resolution:
- [ ] Tübingen should use https (a card was added: https://github.com/seqan/seqan3/projects/7#card-27118779)
- [x] `/usr/bin/env -i` before `wget` call
- [x] harden app name => allow only `[aZ_-09]` app names
- [x] evaluate if system calls can be escaped, ala https://docs.python.org/dev/library/shlex.html#shlex.quote

**Comment by smehringer** [comment]
@seqan/core All of this was fixed except what we cannot influence directly. Should be leave this issue open or close this?

**Comment by rrahn** [comment]
Can we not bug them again? Ask what the state about this is?

**Comment by smehringer** [comment]
Go ahead :D

**Comment by smehringer** [comment]
For the remaining task a card was added
