### ISSUE TITLE
AlignedRange and gap_decorator TODOs

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#1103]
1. random access iterators for gap_decorators
  - [x]  `begin_ra()` and `end_ra()` for `gap_decorator` (@smehringer )
  - [ ]  `view::make_random_access` (#1237 )
  2. Concept changes (@smehringer):
  - [ ] AlignedRange (reference_t is weakly comparable to `gap`)
  - [ ] WritableAlignedRange (current `AlignedSequence`)
  - [ ] make customisation point objects of stuff required for WritableAlignedRange
  - [ ] ~add `assign_gaps(ForwardRange<std::pair<source_position, length>>)`~ Make gap_decorator make use of the hint when inserting to make it constant time.
  - [ ] make random access += more efficient by using the current position as a hint when advancing instead of searching from scratch
  3. merge benchmarks (#789, @mariehoffmann @h-2 )
  4. merge `gap_decorator_anchor_block` ( #917 @mariehoffmann )
  5. discuss and maybe implement `gap_decorator_read_only`
  6. The non-random-access decorator requires that the underlying sequence is random access. This should not be necessary.

We also need a `is_gap` function to query a gappable :grin:  range for gaps without accessing it's values directly (dummy sequence in SAM needs this).

**Comment by rrahn** [comment]
> add `assign_gaps(ForwardRange<std::pair<source_position, length>>)`

What would be the use case for this?

**Comment by smehringer** [comment]
Currently, you can only insert a single gap symbol. This is highly inefficient for the gap_decorator if you want to insert a gap of length 10. While just thinking about it, this should be rather done by adding a size paramter to the `insert_gap` function.

In addition, Marie proposed an insert gap with multiple positions that can be sorted (or required to be sorted) and inserted as a batch which is also more efficient than calling `insert_gaps` many times because in the gap_decorator each `insert_gap` triggers a logarithmic  search for in the std::set that stores the gap information.

**Comment by rrahn** [comment]
> Currently, you can only insert a single gap symbol. 

Oh really? 

> While just thinking about it, this should be rather done by adding a size paramter to the insert_gap function.

Exactly! Like the vector interface `insert_gap(iterator pos, size_t count)`

**Comment by rrahn** [comment]
> In addition, Marie proposed an insert gap with multiple positions that can be sorted (or required to be sorted) and inserted as a batch which is also more efficient than calling insert_gaps many times because in the gap_decorator each insert_gap triggers a logarithmic search in the std::set that stores the gap information.

I know but I am not yet highly convinced that it gives us a real advantage over inserting gap intervals. At least for the regular alignment code, you usually have  a quadratic runtime opposed to a linear runtime when building the gap structure. And when I insert the gaps with a hint (the iterator position), then it should not really matter. I guess that depends on the underlying data structure at the end (which I proposed to be simply a sorted vector)

**Comment by smehringer** [comment]
>  And when I insert the gaps with a hint (the iterator position), then it should not really matter.

You are giving a hint to the position in the virtual sequence. Unfortunately, this does not help the gap decorator to know the physical position in the gap-set (stores position and length of the gaps). 
 
Alternatively, we could think about a push_back/append_gaps functionality because inserting at the end provides enough hints for constant time insertions.

**Comment by mariehoffmann** [comment]
To avoid confusion, of course `insert_gap` can handle contiguous gaps of arbitrary length with defaulted insert length of one. 
`insert_gaps` is intended to handle a list of contiguous gaps. Use cases: read in and processing of MSA files, hardware outsourced MSA computation, e.g. you would want to have minimal data transfer between GPU and main memory and therefore collect the computed gaps before sending them to the memory owned by the parent process.

**Comment by mariehoffmann** [comment]
> > In addition, Marie proposed an insert gap with multiple positions that can be sorted (or required to be sorted) and inserted as a batch which is also more efficient than calling insert_gaps many times because in the gap_decorator each insert_gap triggers a logarithmic search in the std::set that stores the gap information.
> 
> I know but I am not yet highly convinced that it gives us a real advantage over inserting gap intervals. At least for the regular alignment code, you usually have a quadratic runtime opposed to a linear runtime when building the gap structure. And when I insert the gaps with a hint (the iterator position), then it should not really matter. I guess that depends on the underlying data structure at the end (which I proposed to be simply a sorted vector)

Do you mean the approach where gaps are stored as anchors (relative or accumulate)? If so, then just a little reminder that I tested this exhaustively [here](https://github.com/mariehoffmann/seqan3_benchmarks/tree/master/gap_decorators) with plots posted [here](https://github.com/seqan/seqan3/issues/382) (Scroll down) . Result discussion was then in the Journal Club 1 year ago.  
For larger sequences (> (1 << 10)), the anchor set (log k search time to traverse the red-black-tree to get the closest gap for a random position) outperforms the anchor list (linear). However, if the latter approach is modified in the sense that we store virtual positions (accumulated gaps are added to the sequence position) and additionally use block-wise gap sum statistics, we can do binary search to locate the block and then go forward linearly inside this block (constant size). If you thought of using just the vector approach with virtual gap start positions, insertion/deletion comes with the cost of updating the tailing gap positions. The only use-case where these costs can be omitted is de novo gap insertion from left to right. However, we decided for a more general purpose decorator. If you think that's a serious and very frequent use-case which can not be covered by the bulk insertion (i.e. collect all gaps first to create a list and then use the more efficient`insert_gaps(gap_list)`), we could add this approach, too, but should then. 
But if you want to insert gaps from left to right, does the computation always needs the updated sequence state, or could you just collect/read out all gaps and then hand them over to `insert_gaps`?

**Comment by rrahn** [comment]
I think the general use case is to construct the gapped range from an alignment. In this case you always can insert from left to right and depending on the underlying data structure this would be as efficient as it can be. No updating of tails/virtual positions etc. At the moment I consider random inserts/erases as not the standard use case. So I am puzzled about the added value of such a bulk insert function. This also means to bloat the concept and the interface and I think it should be as lean as possible. So I recommend to postpone this until we have actual use cases for this. Then we can reevaluate this interface.

**Comment by smehringer** [comment]
We will re-evaluate this when we work on the range module
