### ISSUE TITLE
[BUG] Including file io does not work without zlib

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#1106]
Because in line 105 of `misc_input.hpp`

```cpp
if (read_chars == magic_number.size() && contrib::_bgzfCheckHeader(magic_number.data())) // BGZF
```

the function `_bgzfCheckHeader` is used although declared in the bgzf_stream header which is **not included** if zlib is not available.

**Comment by h-2** [comment]
We need nightlies without zlib
