### ISSUE TITLE
ArgumentParser version check deactivation

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1113]
shouldn't be done via `true` or `false`, but via strong types, as per our policy.

**Comment by smehringer** [comment]
Really? For the one-and-only boolean constructor parameter? I thought this was for situation with multiple parameters of the same type that can not be distinguished otherwise.

**Comment by rrahn** [comment]
But if you add one in the future it is strange because you have to add a strong type but to provide stable API you cannot get rid of the old constructor. So it is in gerenal better to use strong types for built-in types. Also if there is only a single argument (yet).
