### ISSUE TITLE
Processing returned ranges from search segfaults

### ISSUE THREAD

**Issue by johnlees** [seqan/seqan3#1121]
I have the following code, compiled with GCC 7.2.0 (c++17) and SeqAn 3.0.0:
```
void seq_search(const dna5_vector& query, const std::vector<fm_index<true,default_sdsl_index_type>& seq_idx)
{
   for (auto ref_it = seq_idx.begin(); ref_it != seq_idx.end(); ref_it++)
   {
      auto results = search(query, *ref_it);
      debug_stream << "There are " << results.size() << " hits.\n";
      debug_stream << results << '\n';
      if (results.size() > 0)
      {
         std::cerr << "found" << std::endl;
      }
   }
}
```
If `query` cannot be found then it's ok, but as soon as there is a match I get a segfault, I think at `results.size() > 0`. The number of hits doesn't print, and the result print line appears as `[1]` (which is wrong).

Any ideas what is causing this?
Is this because my libgcc/libstdc++ doesn't have an implementation of ranges?

**Comment by marehr** [comment]
Hi John!

Thank you for reporting.

We only support the most recent version of 7, which should be 7.4.x right now. Can you upgrade your compiler and try it out again? 

I can remember that we had problems with the 7.2 release cycle in the search module. 

Am 22. Juni 2019 00:52:39 MESZ schrieb John Lees <notifications@github.com>:

**Comment by johnlees** [comment]
Thanks for the quick response! 

I am now trying to get this to work with `conda build`, which has GCC 7.3.0, but more recent versions of `libgcc` and `libstdc++`. So, I think it should be possible, but I get confused around the distinction between what is needed with each of these...

Also of potential relevance is `cmake` changing sysroot options:
https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#an-aside-on-cmake-and-sysroots

I guess this might be useful for others trying to use seqan 3 in conda projects, so will continue to update any progress here.

**Comment by marehr** [comment]
I for myself never worked with bioconda, so if you have any progress with it that we can include into our documentation or directly providing a bioconda (scaffold) package it would be much appreciated.

I remember that we have a bioconda section in http://docs.seqan.de/seqan/3-master-user/setup.html

But I guess that you already tried it out and didn't work. 

Am 25. Juni 2019 21:15:12 MESZ schrieb John Lees <notifications@github.com>:

**Comment by johnlees** [comment]
I am trying again with GCC 8.2.0 but am having the same issue. Here is an edited backtrace using the same code as above:
```
 stop reason = EXC_BAD_ACCESS (code=1, address=0xadce8)
invoke.h:60:67
   57  	  template<typename _Res, typename _Fn, typename... _Args>
   58  	    constexpr _Res
   59  	    __invoke_impl(__invoke_other, _Fn&& __f, _Args&&... __args)
-> 60  	    { return std::forward<_Fn>(__f)(std::forward<_Args>(__args)...); }
   61
   62  	  template<typename _Res, typename _MemFun, typename _Tp, typename... _Args>
   63  	    constexpr _Res
sd_vector.hpp:481:13
fm_index_cursor.hpp:534:23
search.hpp:151:17
search.hpp:208:49
search.hpp:86:58
search.hpp:151:46
auto results = search(query, *ref_it);
```

Any ideas why this might be happening? Could it be that I am still picking up an old libgcc and libstdc++?

**Comment by johnlees** [comment]
Perhaps it is not this, the results of `otool -L` suggests it's using the gcc-8 ones:
```
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/local/opt/gcc/lib/gcc/8/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by johnlees** [comment]
Apologies, the backtrace above was when this was threaded. The offending line appears to be in `sd_vector.hpp`:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x2)
    frame #0: 0x000000010005115d map_strings`sdsl::rank_support_sd<(unsigned char)1, sdsl::int_vector<(unsigned char)1>, sdsl::select_support_mcl<(unsigned char)1, (unsigned char)1>, sdsl::select_support_mcl<(unsigned char)0, (unsigned char)1> >::rank(this=0x0000000102000d80, i=711913) const at sd_vector.hpp:480:27
   477 			assert(i <= m_v->size());
   478 			// split problem in two parts:
   479 			// (1) find  >=
-> 480 			size_type high_val = (i >> (m_v->wl));
   481 			size_type sel_high = m_v->high_0_select(high_val + 1);
   482 			size_type rank_low = sel_high - high_val; //
   483 			if (0 == rank_low) return rank_support_sd_trait<t_b>::adjust_rank(0, i);
fm_index_cursor.hpp:534:23
search.hpp:151:17
search.hpp:208:49
search.hpp:86:58
search.hpp:151:46
auto results = search(query, *ref_it);
```

**Comment by h-2** [comment]
Ok, that does look like a bug in our code. @eseiler can you have a look at this?

@johnlees Does it happen for any input or can you provide us with sample argument to above example that trigger the problem?

Regarding compiler versions: We are currently very much at the bleeding edge of C++ and (unfortunately have to) report mulitple GCC bugs on average per month. Since we don't want to riddle our code with `#ifdef`s we target the most recent patch release of the compilers. If you are based on macOS you can get both gcc-7.4 and gcc-8.3 from homebrew!

We expect the situation with compilers to settle down in the next year when the code that we use has matured more.

**Comment by johnlees** [comment]
Ok, thanks a lot for the help!

I've attached an archive, [seqan_3_sdsl_segfault.tar.gz](https://github.com/seqan/seqan3/files/3331577/seqan_3_sdsl_segfault.tar.gz), which has the above code with a main function providing data that produces this error. I've also included the cmake file I've been using. The threaded code has been commented out and replaced with a single function call for ease of debugging.

I tried both the gcc-8.2 from homebrew and gcc-7.3 from anaconda. I'm actually now more confident the latter will work with SeqAn 3 given that it uses v9 libraries, which would be great news for distribution of seqan dependent tools through bioconda!

**Comment by eseiler** [comment]
Thanks for reporting!

Here is a reduced test case
```cpp
#include <seqan3/alphabet/nucleotide/dna4.hpp>
#include <seqan3/search/algorithm/search.hpp>
#include <seqan3/search/fm_index/fm_index.hpp>

using namespace seqan3;

int main()
{
    std::vector<std::vector<dna4>> genomes{"ATTTTATAATATCAGAAAATACTTTTTTTAAAAAGCAAATATGATACAATTTTATTTGAA"
                                           "AAAAAATAAAAAAGGAGATTTTATTATGAAATCAAGTGGTATCGTCGGTCTTGTGGGAGG"_dna4,
                                           "CTTGGTAACCTCCTTCTTGCCCAAGAAGAAATCTCTCACTCATATCCATTTGACTGGCGT"
                                           "ACTAAGAAACCAATCATCTGGCGTGCAGTTCCACAATGGTTTGCCTCAGTTTCTAAATTC"_dna4};

    std::vector<fm_index<true>> vec;
    // vec.push_back(fm_index<true>{genomes}); // Segfault when searching
    // vec.emplace_back(fm_index<true>{genomes}); // Segfault when searching
    vec.emplace_back(genomes); // OK

    auto hits = search("AAAAAAAATAAAAAAGGAGATTTTATTATGA"_dna4, *vec.begin());

    return 0;
}
```

**Comment by smehringer** [comment]
@johnlees The fix was merged. Can you check out the newest master and check if your code works now?

**Comment by johnlees** [comment]
It works!!
Thank you all for quick and helpful support, and the construction of such a useful project

(also this worked in conda with gcc 7.3.0 too - so a bioconda package should certainly be possible)

**Comment by smehringer** [comment]
Thank you :tada:

**Comment by marehr** [comment]
@johnlees Can you open a new issue with a feature request for a bioconda package? (Otherwise we will forget it.)

As you seem to have experience with bioconda, I would like to invite you to walk us through the initial shenanigans to get a bioconda package working. It is much easier to work on something existing than to do it for the first time alone.

**Comment by eseiler** [comment]
> @johnlees Can you open a new issue with a feature request for a bioconda package? (Otherwise we will forget it.)
> 
> As you seem to have experience with bioconda, I would like to invite you to walk us through the initial shenanigans to get a bioconda package working. It is much easier to work on something existing than to do it for the first time alone.

Alternatively, I can be assigned. I did a few packages in the past.
(The main problem will be that conda usually does not provide the most recent release of a compiler.)
