### ISSUE TITLE
Doxygen stricter warnings

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1123]
Do we want to enable

```python
WARNINGS               = YES # we already have this
WARN_IF_UNDOCUMENTED   = YES # we already have this
WARN_IF_DOC_ERROR      = YES # we already have this
WARN_NO_PARAMDOC       = YES # NEW!!!111
```
---

`WARN_NO_PARAMDOC` warns about missing / mismatching parameters `\param` AND missing `return` descriptions.

There seems to be no warning level for missing `\tparam`

**Comment by rrahn** [comment]
I am not so sure. In general yes. But many simple functions like iterator operator need to be documented accordingly. In this case I think the return type etc. is trivial and does not need to be documented. So if this would produce warnings this might get out of hand.
