### ISSUE TITLE
Reading from fastq.gz crashes

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan3#1129]
Hi SeqAn-team :)

I'm trying to open a large fastq.gz file with reads [1] and access the first sequence. It works with SeqAn2 but crashes with SeqAn3. It works however on the unzipped fastq file. So there might be something wrong with the decompression. As @smehringer pointed out both library versions use the same wrapper and zlib? Unfortunately I couldn't create a smaller example that failed.

SeqAn2 (works):

```cpp
CharString id;
Dna5String seq;
SeqFileIn seqFileIn(toCString(path));
readRecord(id, seq, seqFileIn);
cout << seq << '\n';
```

SeqAn3 (crashes):

```cpp
sequence_file_input fin{path};
debug_stream << get<field::SEQ>(fin.front()) << '\n';
```

```
terminate called after throwing an instance of 'seqan3::unhandled_extension_error'
  what():  No valid format found for this extension.
```

I'm working on both master branches of SeqAn2 and SeqAn3 and use ZLIB-1.2.11.

[1] https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/NIST_Illumina_2x250bps/reads/D1_S1_L001_R2_001.fastq.gz

**Comment by h-2** [comment]
Maybe this got broken recently by bgzf code that was hurried in. Can you comment out the first if block in
https://github.com/seqan/seqan3/blob/master/include/seqan3/io/detail/misc_input.hpp#L105
And try again?

**Comment by cpockrandt** [comment]
Awesome, it works!

**Comment by rrahn** [comment]
Ok, the issue is that this file is in fact a bgzf file and the compression format gz was not handled correctly. There is an open PR for the fix.
