### ISSUE TITLE
Search module issues

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1142]
## Documentation

The only thing regarding result_type I could find was:

```
An object modelling std::ranges::Range containing the hits (the type depends on the specification in cfg), or void if an on_hit delegate has been specified.
```

Well, what is a hit? And what does it mean that it depends on a config? Neither the documentation for module or sub-module cover this, nor the documentation of search() or search_cfg. Also the API documentation for search stuff in general is very scarce.

**Comment by h-2** [comment]
Maybe we should discuss what we want the return type to be. I am mildly in favour of having a `search_result` struct that enables us to add more stuff later. And it would be more in line with the alignment module.

**Comment by h-2** [comment]
it is also not documented which headers you need to include to be able to search.

**Comment by h-2** [comment]
## Bugs

* search doesn't enforce that queries model SizedRange, but then calls `std::ranges::size()` on them

**Comment by rrahn** [comment]
In general I would propose gathering these tings in cards on the correspondent project page. These things should to be converted into multiple issues anyway.

**Comment by eseiler** [comment]
> In general I would propose gathering these tings in cards on the correspondent project page. These things should to be converted into multiple issues anyway.

I agree. (and maybe send me a message, so I know that there are issues.)

**Comment by eseiler** [comment]
> ## Bugs
> * search doesn't enforce that queries model SizedRange, but then calls `std::ranges::size()` on them

But generally the expression `std::ranges::size(rng)` on a range `rng` that does not model `SizedRange` is not ill-formed, if `SizedSentinel` is defined for the `rng` iterators.
`SizedRange` just guarantees that it works (and is constant).

I'll add `SizedRange` since I actually do want a constant `size`.

**Comment by eseiler** [comment]
> ## Meta / documentation
> * it is also not documented which headers you need to include to be able to search.
> * search has a "configuration" sub-module in the documentation, but it doesn't exist in the library.
> * search has an algorithm sub-module and a configuration sub-sub-module; we decided we don't have sub-sub-modules so this needs to be changed.

Currently:
```
search
├── algorithm
│   ├── all.hpp
│   ├── configuration
│   │   └── *.hpp
│   ├── detail
│   │   └── *.hpp
│   └── search.hpp
├── all.hpp
└── fm_index
    ├── detail
    │   └── *.hpp
    └── *.hpp
```

Maybe like this?
```
search
├── algorithm
│   ├── all.hpp
│   ├── detail
│   │   └── *.hpp
│   └── search.hpp
├── all.hpp
├── configuration
│   └── *.hpp
└── fm_index
    ├── detail
    │   └── *.hpp
    └── *.hpp
```

**Comment by eseiler** [comment]
> ## Return type
> Maybe we should discuss what we want the return type to be. I am mildly in favour of having a `search_result` struct that enables us to add more stuff later. And it would be more in line with the alignment module.

Agreed. I'll have a look at how the alignment module does it.

**Comment by h-2** [comment]
> But generally the expression std::ranges::size(rng) on a range rng that does not model SizedRange is not ill-formed if SizedSentinel is defined for the rng iterator/sentinel pair.
> SizedRange just guarantees that it works (and is constant).

I think you are mixing up some things. If the iterator-sentinel pair models `SizedSentinel` than the range does indeed model `SizedRange`. Both concepts imply that the size can be retrieved in O(1). `std::ranges::size()` is only defined for `SizedRange`s. 
Independent of `std::ranges::size()` there is also `std::ranges::distance()` which may be in O(n).

> Maybe like this?

:+1:

**Comment by rrahn** [comment]
Regarding the structure the proposed structure would be the right one since we only allow module structure with a depth of 2 if it is public API. Every submodule can have a detail directory though.

**Comment by rrahn** [comment]
For the return type let us discuss what you need so we can keep them in sync as much as possible.

**Comment by eseiler** [comment]
Mhm, we require either that the query models `RandomAccessRange` I would think that this implies `SizedRange`?
If it's a Range of queries `q_rng`, we require `ForwardRange` for the outer range and `RandomAccessRange` for the inner range (actual queries). At some point we call `std::distance(q_rng.begin(), q_rng.end())`. Is this safe?

**Comment by rrahn** [comment]
No RA does not imply Sized. Like an infinity repeat view which is RA but not Sized. You should also use ranges::distance as it gives you the size in O(1) when the ForwardRange is Sized. The std::distance function requires RA iterator for this.
