### ISSUE TITLE
seqan2_test unit test is broken

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#1152]
## Description

The test does not compile if seqan2 is present

Seqn3 revision (current master): f4e8fd450b8e6bbc3c1b8152370fbe56d4fdea45
Seqan2 revsision (current master): 55b8b1f2da587c96f38f572299d01f4ff44af351

```
/srv/public/smehringer/seqan3/test/unit/test/seqan2_test.cpp:107:1:   required from here
/srv/public/smehringer/seqan3/submodules/range-v3/include/range/v3/range/access.hpp:674:38: error: no match for call to ‘(const ranges::_begin_::fn) (seqan::String<int>&)’
```

**Comment by marehr** [comment]
Can you provide the error message and the your current commit id? For me it is working f4e8fd450b8e6bbc3c1b8152370fbe56d4fdea45. Do you have the most recent seqan2 checked out (upstream/develop)?

**Comment by smehringer** [comment]
The test compiles on most recent seqan2/upstream/develop
but not on most recent seqan2/upstream/master. 
If this is fine with our setup this issue can be closed

**Comment by rrahn** [comment]
yes this is ok. Since we haven't merged develop into master yet. So we need another release of SeqAn soon anyway. Maybe until end of this year, depending on how much of compatibility we can expect
