### ISSUE TITLE
Other file formats support "GFT, BED, etc.."

### ISSUE THREAD

**Issue by mr-eyes** [seqan/seqan3#1163]
## Question
Is there a plan for supporting other file formats that were supported by older Seqan versions like GTF, BED, VCF?

Thanks.

**Comment by smehringer** [comment]
Hi @mr-eyes,

Yes, there certainly is! We just don't have the capacities for this right now so this feature won't be ready before next summer. 

If you are interested in contributing, we happily accept pull request and would of course support the process :smiley:

**Comment by marehr** [comment]
Hi @mr-eyes,

we are adding this to our long term todo list. As soon as someone is working on it, we will reopen the issue. Thank you for reporting!

See https://github.com/seqan/seqan3/projects/17#card-27121065
