### ISSUE TITLE
Change build system to support detail tests that are excluded from coverage.

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#1166]
Check if tests can be excluded from code coverage build with a regex. E.g., have all detail tests named `xxx_detail_test.cpp` and exclude them from coverage.

**Comment by eseiler** [comment]
Mhm, one more thing came to my mind.
As example: You implement some algorithm and need an *internal* (reusable?) data structure. You want the new data structure to model `ReserveableContainer` and hence implement a plethora of functions, most of which you just do not need or just cannot use in your algorithm. But this would lead to a decrease in coverage, wouldn't it?

**Comment by marehr** [comment]
Yes and we talked about it. If it is something that models for example a Container when it is not considered as a detail test, because we could reuse the class for other use cases.

**Comment by smehringer** [comment]
Hm this is indeed a use case where the new test design has to make exceptions.. if we consider the small_vector as an example, @marehr is right, we decided that independent data structures that are reused in different models may be tested publicly, but what about detail data structures that e.g. are only used in the search module and nowhere else?

**Comment by eseiler** [comment]
No specific use case. I think it's fine as you outlined it.

**Comment by rrahn** [comment]
Is it not possible to tell gcov to not set counters for any object/function defined in a file that has detail in it‘s name? 

In this is not possible, and we have something that models a public Concept we might have a test template for it that tests all the interfaces like the iterator tests right now. So it must be tested separately for the testcoverage to reach 100%.
