### ISSUE TITLE
ArgParser: extension containing . accepted, but fail

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1176]
In my attempt to support `.fasta.gz`, I added `fasta.gz` as an extension. But the argument parser tells me:
```
Validation failed for option -d/--database: Expected one of the following valid extensions: [fa,fq,fasta,fastq,fa.gz,fq.gz,fasta.gz,fastq.gz]! Got gz instead!
```

One could argue whether extensions containing the dot should be allowed, but I think they should. If not, there should be an error when setting up such an extension, not a silent failure.

In any case, we also need handling of compression formats.

**Comment by smehringer** [comment]
Solution 1:
The user only needs to supply the formats without the additional compression extension and the file extension validator should check those depending which library is present.
The same way, the argument parser should add compression extension automatically. 
I guess then we need to prevent users from supplying multi-extension extensions (containing another dot). But this might limit pipelines?

Solution 2
We adapt the extension validator to allow multi-extensions. The validator nor the argument parser add compression extension automatically but the user must provide them. This can be facilitated by providing a get_file_extensions function from the file object which adds all format and compression extensions

If I remember correctly we agreed on solution 2? @rrahn @h-2
Then the extension validator needs to be fixed.

**Comment by h-2** [comment]
Hm, I have thought about this a bit more, and I would propose the following:

1. We add `seqan3::input_stream` and `seqan3::output_stream`, they transparently apply (de)compression if needed (similar to SeqAn2's VirtualStream). We need this anyway, because we want to easily use compression and decompression for things that are not our formatted_files. This will also obsolete the two-stream-mechanism in our formatted-files.
2. Since the above is the recommended way of doing all I/O, the ArgumentParser adds a `Valid input file compressions: gz, bz2, bgzf.` to all input file validator descriptions (this can be disabled, but is enabled by default). Users only supply the actual extensions. This also prevents the list from becoming too long ( `[a, b]` and [gz, bz]` vs `[a, a.gz, a.bz2, b, b.gz, b.bz2]`)
3. Our formatted files get the `valid_format_extensions()` static member function we have been discussing for a while. It only prints the actual format extensions.


Indepedent of all the above, I propose we also allow extensions to contain `.`, because it's a valid use-case independent of compression, or not? (This point I am less sure about, but not allowing it seems like an arbitrary limitation)

**Comment by rrahn** [comment]
I am absolutely for point 1. That makes a lot of stuff much easier in the handling, especially when working with stream compressors. The 2. point we already agreed on. The list of extensions is handled separately from the compression formats. Still for the CTD parser we can build a list of all combinations. In my current PR for extracting the valid extensions I added a similar mechanism to get the compression formats. If we resolve the issue with formats can themselves handle compressions, e.g. bam then we don‘t need to worry about possible incompatibilities. Anyway, I have thought about the same design. So the user can initialise the file validator with the file and the extensions would be selected from the valid formats. The compression is added internally, possibly opt-out via a flag. For handling the file extensions I agree `.ext` and `ext` should both be valid. I guess that is more of a personal preference and has nothing to do with semantic differences.

**Comment by smehringer** [comment]
> For handling the file extensions I agree .ext and ext should both be valid. I guess that is more of a personal preference and has nothing to do with semantic differences.

But the discussion was about: Do we allow  `ext1.ext2` :) ?

**Comment by rrahn** [comment]
and we said yes. Plus some additional design decisions ;)

**Comment by eseiler** [comment]
This should be fixed by https://github.com/seqan/seqan3/pull/2363
