### ISSUE TITLE
Add nightly without zlib/bzip support

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#1182]
When using formatted files with compression we require the dependency of zlib or bzip2. Since all our systems on which we test our software have these dependencies installed we might not see errors that could occur in the code if we do not have the dependencies (see #1106). 
To test without zlib or bzip make a seperate docker build on jenkins that does not install the dependencies upon start.

**Comment by smehringer** [comment]
Related to #1106

**Comment by h-2** [comment]
You can pass a macro and it won't be used, even if present on the system. So there is no need for an extra docker.

**Comment by rrahn** [comment]
But it is already there. Our docker containers are vanilla containers and install the dependencies on invocation. You just need another rule that omitd installing  these dependencies. I think that is a more natural use case.
