### ISSUE TITLE
[Follow-up #1157] view_take_exactly fails on PPC gcc8 release

### ISSUE THREAD

**Issue by eseiler** [seqan/seqan3#1183]
```console
seiler@???:~/build$ ./range/view/view_take_test 
Running main() from /home/seiler/build/vendor/googletest/googletest/src/gtest_main.cc
[==========] Running 11 tests from 3 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from view_take
[ RUN      ] view_take.regular
[       OK ] view_take.regular (0 ms)
[ RUN      ] view_take.concepts
[       OK ] view_take.concepts (0 ms)
[ RUN      ] view_take.underlying_is_shorter
[       OK ] view_take.underlying_is_shorter (0 ms)
[ RUN      ] view_take.type_erasure
[       OK ] view_take.type_erasure (0 ms)
[----------] 4 tests from view_take (0 ms total)

[----------] 4 tests from view_take_exactly
[ RUN      ] view_take_exactly.regular
/home/seiler/seqan3/test/unit/range/view/view_take_test.cpp:53: Failure
Expected equality of these values:
  "rab"
  v3b
    Which is: "rabof"
[  FAILED  ] view_take_exactly.regular (0 ms)
[ RUN      ] view_take_exactly.concepts
[       OK ] view_take_exactly.concepts (0 ms)
[ RUN      ] view_take_exactly.underlying_is_shorter
[       OK ] view_take_exactly.underlying_is_shorter (0 ms)
[ RUN      ] view_take_exactly.shrink_size_on_input_ranges
[       OK ] view_take_exactly.shrink_size_on_input_ranges (0 ms)
[----------] 4 tests from view_take_exactly (0 ms total)

[----------] 3 tests from view_take_exactly_or_throw
[ RUN      ] view_take_exactly_or_throw.regular
[       OK ] view_take_exactly_or_throw.regular (0 ms)
[ RUN      ] view_take_exactly_or_throw.concepts
[       OK ] view_take_exactly_or_throw.concepts (0 ms)
[ RUN      ] view_take_exactly_or_throw.underlying_is_shorter
[       OK ] view_take_exactly_or_throw.underlying_is_shorter (1 ms)
[----------] 3 tests from view_take_exactly_or_throw (1 ms total)

[----------] Global test environment tear-down
[==========] 11 tests from 3 test cases ran. (1 ms total)
[  PASSED  ] 10 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] view_take_exactly.regular

 1 FAILED TEST
```

---

The failing `v3b` is 
```cpp
std::string v3b = vec | std::view::reverse | adaptor(3) | ranges::view::unique | std::ranges::to<std::string>;
```
where `vec = "foobar"` and `adaptor = view_take_exactly`. If you remove, e.g., `ranges::view::unique`, it works. You can also remove some of the other views to make it work.

---

Fail matrix (:x: = fail, :white_check_mark: = passes)

|                | no flags           | -fsanitize=unused  | -fsanitize=address |
|----------------|--------------------|--------------------|--------------------|
| Release        | :x:                | :white_check_mark: | :white_check_mark: |
| RelWithDebInfo | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| Debug          | :white_check_mark: | :white_check_mark: | :white_check_mark: |

---

I'll ask the IT to install valgrind on the server (and some more compilers besides gcc-8.3.0), but I'd vote for making this a follow-up issue?

---

**Update**

This bug is gcc8 only, gcc7 and gcc9 work fine.
I attached the valgrind log for gcc8
[Release_valgrind.log](https://github.com/seqan/seqan3/files/3372794/Release_valgrind.log)

**Update 2**
Tests pass with head of googletest, valgrind still finds errors
[Release_live_googletest_valgrind.log](https://github.com/seqan/seqan3/files/3372823/Release_live_googletest_valgrind.log)

**Update 3**
Most interesting log is probably the one with tracking origins
[Release_with_origin_valgrind.log](https://github.com/seqan/seqan3/files/3372858/Release_with_origin_valgrind.log)

_Originally posted by @eseiler in https://github.com/seqan/seqan3/pull/1157#issuecomment-509404929_

**Comment by rrahn** [comment]
Well, I have also some gcc-8 issues on macos (only on sierra and high-sierra). Not sure if the compiler is in general broken. Also it had some severe performance regressions that were fixed in gcc-9 again, if I remember correctly.

**Comment by eseiler** [comment]
Mhm, maybe it is the compiler.
Which things are failing on macos?

Btw, is updating googletest to master also fixing the tests for macos?

**Comment by rrahn** [comment]
I have to check. But I experienced segfaults in the alignment configuration. Neither valgrind nor sanitizer brought any luck

**Comment by eseiler** [comment]
Will be fixed by updating google test.
