### ISSUE TITLE
Introduce new product development cycle

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#119]

**Comment by h-2** [comment]
I am supportive of a better structured cycle, but I am strongly against increasing the amount of tooling. We should be able to do all of this with GitHub projects and not resort to Trello :pray:

**Comment by rrahn** [comment]
As a matter of fact, we can do this workflow also on a organisation wide project in GitHub, which I prefer over trello. So we would first try it there, and see how it works out for us.

**Comment by marehr** [comment]
Since we settled for github projects, I close this issue.
