### ISSUE TITLE
BAM unknown reference name

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1201]
Maybe we are too strict?

I am seeing this on random files from the internet:
```
terminate called after throwing an instance of 'seqan3::format_error'
  what():  Unknown reference name 'chr1' found in BAM file header (header.ref_ids():[]).
```
e.g. http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeUwRepliSeq/wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam

```cpp
#include <seqan3/core/debug_stream.hpp>
#include <seqan3/io/sam_file/input.hpp>

int main()
{
    seqan3::sam_file_input fin{"wgEncodeUwRepliSeqBg02esG1bAlnRep1.bam"};
    seqan3::debug_stream << fin.header().format_version << '\n';
}
```

**Comment by smehringer** [comment]
I guess we are. samtools only emits a warning, maybe we should too? Or just debug assert this and ignore in release.

**Comment by rrahn** [comment]
It depends. Is the format specification such that it is an ill-formed BAM file if the reference names are not present? 
I guess, what we need is kind of a property that allows people to parse strict (ensuring the format is correct) and a less strict versions so users can disable the strict parsing on purpose. That could be a simple strong typed bool flag added to the constructor.

**Comment by h-2** [comment]
> I guess, what we need is kind of a property that allows people to parse strict (ensuring the format is correct) and a less strict versions so users can disable the strict parsing on purpose. That could be a simple strong typed bool flag added to the constructor.

We discussed this idea previously in the context of FastA and came to the conclusion that it is not feasible in general. Enforcing a strict format is much more expensive and enforcing it conditionally would mean adding a huge amount of if-checks that are also too expensive. We decided then that it is not important to reject wrong files as long as we accept all correct files. If someone wants strict format handling, they can add an extra format for this.

**Comment by rrahn** [comment]
> Enforcing a strict format is much more expensive and enforcing it conditionally would mean adding a huge amount of if-checks that are also too expensive. We decided then that it is not important to reject wrong files as long as we accept all correct files. If someone wants strict format handling, they can add an extra format for this

Given the complexity of the format already, I doubt that anyone is writing it's own format. But my initial question was, is that a requirement by the specification? If not we don't have to do anything but remove this check. If it is a requirement by the specification we cannot remove the check. Having a option that allows some control of error logging is not a bad thing and I hardly doubt that this will have a measurable impact on the runtime.

**Comment by smehringer** [comment]
> But my initial question was, is that a requirement by the specification?

The specification is not clear about this. It just assumes that header and record information are consistent.

It is necessary for our implementation though because we assign indices to our reference names to avoid storing redundant information. If we do not want to throw an error, we need to decide what happens with an "unknown" reference name. The easiest thing (and might be done by samtools, I need to check) is to discard the unknown reference name and treat the record as unmapped (This includes altering record information).

**Comment by rrahn** [comment]
I think that would be a good solution, but not without a diagnostic message that the ref could not be found and that all records depending on that ref are treated as unmapped records.

**Comment by marehr** [comment]
@eseiler Wants to look at this, as this might already be fixed.

**Comment by eseiler** [comment]
The files does not have a header set, i.e. `l_text` is `0`. Hence, there are no information to parse via `read_header` and we try to verify the existing references with an empty header -> error.
samtools does not give me errors or warnings. When requesting the header, it seems to generate it from the `l_name`/`name`/`l_ref` block.

That means we could do something like this:

```patch
diff --git a/include/seqan3/io/sam_file/format_bam.hpp b/include/seqan3/io/sam_file/format_bam.hpp
index 99f5217d..b1decb05 100644
--- a/include/seqan3/io/sam_file/format_bam.hpp
+++ b/include/seqan3/io/sam_file/format_bam.hpp
@@ -333,17 +333,18 @@ inline void format_bam::read_alignment_record(stream_type & stream,
         if (!std::ranges::equal(stream_view | views::take_exactly_or_throw(4), std::string_view{"BAM\1"}))
             throw format_error{"File is not in BAM format."};
 
-        int32_t tmp32{};
-        read_field(stream_view, tmp32);
+        int32_t l_text{};
+        read_field(stream_view, l_text);
 
-        if (tmp32 > 0) // header text is present
-            read_header(stream_view | views::take_exactly_or_throw(tmp32), header, ref_seqs);
+        if (l_text > 0) // header text is present
+            read_header(stream_view | views::take_exactly_or_throw(l_text), header, ref_seqs);
 
         int32_t n_ref;
         read_field(stream_view, n_ref);
 
         for (int32_t ref_idx = 0; ref_idx < n_ref; ++ref_idx)
         {
+            int32_t tmp32{};
             read_field(stream_view, tmp32); // l_name (length of reference name including \0 character)
 
             string_buffer.resize(tmp32 - 1);
@@ -352,6 +353,14 @@ inline void format_bam::read_alignment_record(stream_type & stream,
 
             read_field(stream_view, tmp32); // l_ref (length of reference sequence)
 
+            if (l_text == 0)
+            {
+                header.ref_ids().push_back(string_buffer);
+                header.ref_id_info.emplace_back(tmp32, "");
+                header.ref_dict[(header.ref_ids())[(header.ref_ids()).size() - 1]] = (header.ref_ids()).size() - 1;
+                continue;
+            }
+
             auto id_it = header.ref_dict.find(string_buffer);
 
             // sanity checks of reference information to existing header object:
```

If there is no `text` to be parsed, we allow to gather the reference information from within the BAM file.

**Comment by marehr** [comment]
```
@SQ	SN:ref2	LN:45
r001	99	ref	7	30	8M2I4M1D3M	=	37	39	TTAGATAAAGGATACTG	*
r002	99	ref3	7	30	8M2I4M1D3M	=	37	39	TTAGATAAAGGATACTG	*
```

is also an accepted sam file with the following warning

```
> samtools view samfile.sam
[W::sam_parse1] unrecognized reference name "ref"; treated as unmapped
[W::sam_parse1] unrecognized reference name "ref3"; treated as unmapped
r001	103	*	7	30	8M2I4M1D3M	*	37	39	TTAGATAAAGGATACTG	*
r002	103	*	7	30	8M2I4M1D3M	*	37	39	TTAGATAAAGGATACTG	*
```

This file will not be accepted
```
r001	99	ref	7	30	8M2I4M1D3M	=	37	39	TTAGATAAAGGATACTG	*
r002	99	ref3	7	30	8M2I4M1D3M	=	37	39	TTAGATAAAGGATACTG	*
```

```
> samtools view samfile.sam
[E::sam_parse1] no SQ lines present in the header
samtools view: error reading file "samfile.sam"
```

That means at least one `@SQ` line must be present in header, but can be a mismatch of sequence.

On the flip side that means only `@SQ` is needed and a bam header can be empty since all the sequences are stored separately.

Patch looks fine to me :)

**Comment by marehr** [comment]
2021-04-20 Core Meeting

We'll implement the patch. We should create a new issue for above comment.
