### ISSUE TITLE
macOS nightlies broken

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1206]
Looks like there was an operating system update which killed all the high sierra tests and many sierra tests.

**Comment by rrahn** [comment]
I‘ll check in the evening

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rrahn** [comment]
I checked and I can at least build everything locally. so either some one else already fixed it or I need to further investigate it. So let's see what the nightlies and other ci builds will say.

**Comment by rrahn** [comment]
fixed
