### ISSUE TITLE
Cigar documentation uses snippets from qualfied alphabet

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#1216]
## Platform

  - SeqAn version: master

## Description

The documentation of the cigar alphabet shows examples for the qualified alphabet in many member function documentations.

**Comment by rrahn** [comment]
@joshuak94 Not sure if this is already taken care of in the snippets fix for the alignment file?

**Comment by joshuak94** [comment]
I figured this was intentional because there is this note in the examples in the documentation:

"Note: Since the alphabet_tuple_base is a CRTP base class, we show the working examples with one of its derived classes (seqan3::qualified)."

Should this not be the case?

**Comment by rrahn** [comment]
Well I personally find it less understandable. Also usually the documentation is not necessarily read from top to bottom when I am searching for something specific. Seeing a snippet with a different context might be noticed as a wrongly placed snippet.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joshuak94** [comment]
Okay, I can change it. But I think I'll wait until the three pull requests I have are merged before I do that one!

**Comment by joshuak94** [comment]
@rrahn I'm working on this now, but I'm not sure what snippets to put for the `indirect_component_type` snippets. For qualified, it uses the rna4 alphabet to construct a dna4q object. But for CIGAR, there is no subtype for the cigar_op alphabet...

**Comment by rrahn** [comment]
But then this documentation is not relevant for the CIGAR. So why not leave it away?

**Comment by joshuak94** [comment]
I can remove the documentation for it.
