### ISSUE TITLE
SAM/BAM: access to optional fields

### ISSUE THREAD

**Issue by eldariont** [seqan/seqan3#1218]
Hi,

I'm reading SAM/BAM files using seqan3's Alignment IO module in order to call variants. I now need to access the optional fields of a SAM/BAM file and as far as I can see this is not implemented yet. The optional fields can contain lots of useful information, e.g. about the supplementary alignments of a read (see Section 1.5 of the [specs](https://samtools.github.io/hts-specs/SAMv1.pdf)).
Do you think this could be added to seqan3?

Cheers
David

**Comment by h-2** [comment]
Yes, this is planned, absolutely! I am not sure if we have a time-frame, yet, I will discuss it with @smehringer on Monday.

**Comment by eldariont** [comment]
Cool, thanks Hannes!

**Comment by smehringer** [comment]
Hi @eldariont 

What do you mean by optional fields? The tags (e.g. NM:i:3)?
Because this is already implemented when reading the `seqan3::TAGS` field into a `seqan3::sam_tag_dictionary`.

**Comment by eldariont** [comment]
Thanks! The `seqan3::TAGS` field is exactly what I need. 😃 
Sorry for not finding it myself. I guess I only looked in the Tutorial (http://docs.seqan.de/seqan/3-master-user/tutorial_alignment_file.html#autotoc_md78) where it's not mentioned yet.

**Comment by smehringer** [comment]
I will add a tutorial section for it!
