### ISSUE TITLE
Our random access iterator adaptor has broken equality semantics

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#122]
According to this [article](https://stackoverflow.com/questions/35390835/is-comparison-of-const-iterator-with-iterator-well-defined) the equality comparison between `iterator` and `const_iterator` obtained from the same container must be valid.
However, our adaptor fails when comparing `iterator` with `const_iterator`.
Furthermore, our tests do test non-standard conform behaviour.
That is the comparison of two iterators over to ranges results in undefined behaviour. ([see discussion](https://stackoverflow.com/questions/4657513/comparing-iterators-from-different-containers))

**Comment by h-2** [comment]
Please also see the huge amount of changes to this file in #104

**Comment by h-2** [comment]
I specifically think that 
```diff
+    //!\brief This friend declaration is required to allow non-const to const-construction.
+    template <typename t>
+        requires std::is_const_v<t> && !std::is_const_v<container_type>
+    friend class random_access_iterator;
```
 addresses this.

**Comment by marehr** [comment]
@rrahn Can you point to a code location where you think this bug is still there?

**Comment by rrahn** [comment]
@marehr I will to look into the code soon.

**Comment by h-2** [comment]
@rrahn ping

**Comment by rrahn** [comment]
I think the iterator template tests this now and everything is fine
