### ISSUE TITLE
gcc 9.2.1: internal compiler error: in equal, at cp/constexpr.c:1088

### ISSUE THREAD

**Issue by mr-c** [seqan/seqan3#1220]
## Platform

  - SeqAn version: 3.0.0
  - Operating system: `Linux 370b2ea81811 5.0.0-20-generic #21~18.04.1-Ubuntu SMP Thu Jun 27 04:04:37 UTC 2019 x86_64 GNU/Linux` (Debian "unstable" Docker software container running on Ubuntu)
  - Compiler: `c++ (Debian 9.2.1-1) 9.2.1 20190813`

### How to repeat the problem

Use the following `Dockerfile`
```
FROM debian:unstable

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
  debhelper \
  cmake \
  zlib1g-dev \
  libboost-dev \
  libgtest-dev \
  liblemon-dev \
  help2man \
  python \
  libbz2-dev \
  build-essential \
  git \
  ca-certificates \
  devscripts

WORKDIR /build
RUN git clone --depth=1 https://salsa.debian.org/med-team/seqan3.git
WORKDIR /build/seqan3
RUN uscan --force && dpkg-buildpackage -uc -us

# or
WORKDIR /build
RUN git clone --recursive https://github.com/seqan/seqan3.git && mkdir seqan3/debug
WORKDIR /build/seqan3/debug
RUN cmake ../test/unit -DCMAKE_BUILD_TYPE=debug -DCMAKE_CXX_COMPILER=g++-9
```

### Expected behaviour

Compilation suceeds

### Actual behaviour

> [ 23%] Building CXX object alphabet/CMakeFiles/custom_alphabet_test.dir/custom_alphabet_test.cpp.o
 cd /build/seqan3/build/alphabet && /usr/bin/c++  -DSEQAN3_HAS_BZIP2=1 -DSEQAN3_HAS_ZLIB=1 -I/build/seqan3/build/vendor/googletest/googletest/include -I/build/seqan3/test/include -I/build/seqan3/include -isystem /build/seqan3/submodules/sdsl-lite/include -isystem /build/seqan3/submodules/range-v3/include -isystem /build/seqan3/submodules/cereal/include  -g -O2 -fdebug-prefix-map=/build/seqan3=. -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -O3   -pedantic -Wall -Wextra -Werror -std=c++17 -fconcepts -o CMakeFiles/custom_alphabet_test.dir/custom_alphabet_test.cpp.o -c /build/seqan3/test/unit/alphabet/custom_alphabet_test.cpp
In file included from /build/seqan3/test/unit/alphabet/custom_alphabet_test.cpp:11:
/build/seqan3/test/unit/alphabet/alphabet_constexpr_test_template.hpp: In instantiation of 'void gtest_case_alphabet_constexpr_::global_to_char<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = my_namespace::my_alph]':
/build/seqan3/test/unit/alphabet/alphabet_constexpr_test_template.hpp:124:1:   required from here
/build/seqan3/test/unit/alphabet/alphabet_constexpr_test_template.hpp:127:70:   in 'constexpr' expansion of 'seqan3::to_char.seqan3::detail::adl::only::to_char_fn::operator()<my_namespace::my_alph>(((gtest_case_alphabet_constexpr_::global_to_char<my_namespace::my_alph>::TypeParam)t0))'
/build/seqan3/test/unit/alphabet/alphabet_constexpr_test_template.hpp:127:59: internal compiler error: in equal, at cp/constexpr.c:1088
  127 |     [[maybe_unused]] constexpr alphabet_char_t<TypeParam> c = to_char(t0);
      |

**Comment by h-2** [comment]
We are also seeing this in the nightlies since http://cdash.seqan.de/index.php?project=SeqAn3&date=2019-08-27

**Comment by h-2** [comment]
Reported upstream as https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91607

**Comment by eseiler** [comment]
Mitigated by #1310
