### ISSUE TITLE
File Input options are set after the first record is read

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#1232]
## Description

Big program in file i/o. If you want to set options on the file, this can only be done AFTER an instance of sequence_file_input is created. This means that **the first record is always read with default options** :(

### How to repeat the problem

```cpp
    std::istringstream istream{std::string
    {
        "> ID1 lala\n"
        "ACGTTTTTTTTTTTTTTT\n"
        "> ID2\n"
        "ACGTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT\n"
        "> ID3 lala\n"
        "ACGTTTA\n"
    }};

    sequence_file_input fin{istream, format_fasta{}};

    fin.options.truncate_ids = true;

    auto it = fin.begin();
    std::cout << get<field::ID>(*it) << std::endl; // ID1 lala
   ++it;
    std::cout << get<field::ID>(*it) << std::endl; // ID2
    ++it;
    std::cout << get<field::ID>(*it) << std::endl; // ID3
```

:sob: 

This was never caught by our test because we only do detail tests of the formats but never with sequence files. I started to change this because the read function of the format will soon not be accessible anymore.

**Comment by smehringer** [comment]
I see two ways to solves this.
1. Make options a construction parameter.
2. Make a set_option function that alters the first record...

both are ugly

**Comment by h-2** [comment]
I only see one way to solve this:
Not reading the first record on construction and doing `if (first_run) ...` check everytime the iterator is dereferenced.

**Comment by smehringer** [comment]
This will be heavy on the run time :(

**Comment by smehringer** [comment]
what about reading the first record when `begin` is called?
