### ISSUE TITLE
Use HTTPS URL in GitHub description

### ISSUE THREAD

**Issue by paulmenzel** [seqan/seqan3#1239]
Please use https://www.seqan.de/.

**Comment by eseiler** [comment]
Thanks for spotting!

I remember that we had some trouble with the `s` when the certificate was expired, but this is fixed now.

@core I'd just change it to `https` everywhere. We also have quite a few other links in the docs, and to `cppreference.com` in the code documentation.

**Comment by eseiler** [comment]
Actually, I can't change the the github description, but I did it everywhere else!

```
The modern C++ library for sequence analysis. Contains version 3 of the library and API docs. http://www.seqan.de
```

@h-2, @rrahn or @smehringer should have sufficient permissions.

**Comment by smehringer** [comment]
Good catch!
I changed the description.
