### ISSUE TITLE
Replace meta:: with our own stuff

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1247]
replace meta library usage with our traits in seqan3::list_traits:: / seqan3::pack_traits::

**Comment by joshuak94** [comment]
`pack_traits::contains<type, pack_t>` will compile when `pack_t` is a `seqan3::type_list<>`, but then it always evaluates to false... Should it accept a type_list as a valid pack type?

**Comment by h-2** [comment]
No, that's what we have `list_traits::contains` for. The pack traits treat all types (possibly after the first) as elements of the pack.

**Comment by smehringer** [comment]
Can't we explicitly delete the case that pack_t is a type_list to avoid errors?

**Comment by h-2** [comment]
It doesnt evalauete to false if the type that you are looking for is a type_list. That's a valid scenario. You can have list of lists.

**Comment by smehringer** [comment]
hm... Is that really a use case?
This can cause quite a hassle if you misuse it. But I guess prohibiting it would be too restrictive

**Comment by h-2** [comment]
> hm... Is that really a use case?

Sure, why not?

> This can cause quite a hassle if you misuse it. 

Well they are in different namespaces. 

> But I guess prohibiting it would be too restrictive

Some of the trait implementations use each other so forbidding pack of type_list might also forbit type_list of type_list.

**Comment by joshuak94** [comment]
I'm going to use this comment to make a list of things in meta that I don't think we have good alternatives for:

1. `meta::for_each(valid_formats{}, [&] (auto && fmt)` in io/detail/misc.hpp

**Comment by smehringer** [comment]
> I'm going to use this comment to make a list of things in meta that I don't think we have good alternatives for:
> 
>     1. `meta::for_each(valid_formats{}, [&] (auto && fmt)` in io/detail/misc.hpp

we do have that but in a detail namespace: 
[`for_each_value`](http://docs.seqan.de/seqan/3-master-dev/group__algorithm.html#gab5e6830103075818b98cb48f099ff4ef)
an for_each_type
