### ISSUE TITLE
pseudoknot_support should have the base class std::false_type

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#128]
I don't know what pseudoknots are, but the current definition:

```c++
template<typename alphabet_type>
struct pseudoknot_support{};

template<typename alphabet_type>
constexpr bool pseudoknot_support_v = pseudoknot_support<alphabet_type>::value;
```

looks to me as it should be `is_pseudoknot` and `is_pseudoknot_v`?

Whatever the name is it should inherit from `std::false_type` or `std::true_type`.

Any thoughts?

**Comment by rrahn** [comment]
As discussed. The naming should be `has_pseudoknot_support` and it must either evaluate to `false` or `true` if the trait is fulfilled.

**Comment by joergi-w** [comment]
This is outdated, as the variable contains the maximum pseudoknot depth now and was renamed to `max_pseudoknot_depth`.
