### ISSUE TITLE
Hashing algorithm in kmer_hash view?

### ISSUE THREAD

**Issue by JensUweUlrich** [seqan/seqan3#1280]
## Platform

  - SeqAn version: 3.0.0
  - Operating system: Linux
  - Compiler: gcc-7.4.0

## Question

I wonder which hashing algorithm the kmer_hash view does use internally. MurmurHash? Or something really trivial? Do you know where I can find information about the collision rate for certain kmer sizes?

Thanks!
Jens

**Comment by eseiler** [comment]
Hey Jens,

the `kmer_hash_view` just uses a form of arithmetic coding. A string/symbol is interpreted as a number to base sigma - there cannot be collisions.
E.g. for dna4
```
A  C  G  T
0  1  2  3
```
results in `0 * 4^3 + 1 * 4^2 + 2 * 4^1 + 3 * 4^0 = 27`.


Best,
Enrico

**Comment by JensUweUlrich** [comment]
Hi Enrico,

thanks for your quick response.

How will positions masked by a shape count in this equation? Are they just ignored?

Best,
Jens

**Comment by eseiler** [comment]
Just ignored, e.g. `ACGT` and a shape `101` will result in `AG`(2) and `CT`(7) being hashed.

**Comment by eseiler** [comment]
Feel free to reopen if you have any further questions!
