### ISSUE TITLE
Write wiki entry for HowTo write Doxygen

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#132]
Some of the fixes of  the documentation seem not trivial. 
It would be good to add a `good practice` documentation on the developer wiki, so that others do not run into the same issues as a follow up for #127.

## Known issues
- [ ] issue with `\relates` statement
- [ ] issue unresolvable references, e.g. `typename seqan3::underlying_char<alphabet_type>::type`
- [ ] `\defgroup gap` ➡️  `\defgroup gap Gap`
- [ ] `operator "" _aa27s` ➡️ `operator""_aa27s`

**Comment by SGSSGene** [comment]
Not relevant anymore. Many entities are documented and serve as great templates for new documentation.
