### ISSUE TITLE
Question: For the Dna alphabet, is ACGT stored in 4 bytes or one?

### ISSUE THREAD

**Issue by mstankus** [seqan/seqan3#134]
I am a newbie.

Is ACGT stored in 4 bytes or one? 

If I have an alphabet of size 2^k, I want to store them is k bits. In particular, I want to be able to pack them into as few bytes as possible. I would also like k to be specified at run time.

Where do I start looking at the code if the answer to the above question is yes.

Mark Stankus

**Comment by marehr** [comment]
Hello @mstankus,

the dna4 alphabet (ACGT) uses one byte.

seqan3 is in an alpha state and should (currently) not be used in production. Of course we welcome you to play around with it! We are working on porting code from seqan2 (https://github.com/seqan/seqan) to seqan3 s.t. it can be used in production. This will take some time and we recommend to use the seqan2 repository at the moment.

Can you open a new issue at the seqan2 repository? There are some tricks to do bit/byte packing in seqan2 that are currently not implemented/ported yet.

Marcel
