### ISSUE TITLE
Change seqan3::cigar variable names in doc

### ISSUE THREAD

**Issue by ppericard** [seqan/seqan3#1344]
In the documentation for how to get CIGAR fields from alignment files (for example https://docs.seqan.de/seqan/3-master-user/tutorial_alignment_file.html) the variable containing that CIGAR is named "cigar", which clashes with the seqan3::cigar class when using namespace seqan3.
Just saying ;-)
Cheers and thanks for all the good work

**Comment by rrahn** [comment]
thanks for the hint. We'll look at this.
