### ISSUE TITLE
Equivalent to Seqan2 BamFlags operations

### ISSUE THREAD

**Issue by ppericard** [seqan/seqan3#1345]
Is there an equivalent to Seqan2 BamFlags operations when reading Alignment files?
Something like `bool hasFlagRC(flag)` that would do the correct bitwise operations on a field::FLAG variable?

If not, could you give me an example how to correctly do the bitwise operations with Seqan3 to determine for example if a read was reverse-complemented before being aligned ?

Thanks
Pierre

**Comment by h-2** [comment]
I thought that we implemented `field::FLAG` as an enum type, but apparently this is not the case and it currently is just a `uint16_t`. That's definitely something we need to change.

**Comment by h-2** [comment]
@smehringer This should be a fairly simple issues, maybe you can assign it to one of the new team members.

**Comment by smehringer** [comment]
Oh, this was a todo that got lost in the process.
Thanks for opening this issue @ppericard.

I'll see when we have time to work on this but since it is fairly simple it shouldn't be too long from now.

**Comment by smehringer** [comment]
@ppericard You can check out the new master branch and test if the feature works for you. Our documentation will probably be up to date tomorrow.

**Comment by ppericard** [comment]
Hi. I'm back developing after several months. So I've been using the new sam_flag feature and it works great. Thank you for your continued work ^^

**Comment by ppericard** [comment]
Hi @smehringer. I'm back developing after several months. So I've been using the new sam_flag feature and it works great. Thank you for your continued work ^^
