### ISSUE TITLE
concatenated_sequences uses more functionality of a iterator type than required

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#135]
See:

https://github.com/seqan/seqan3/blob/5404a17afd978785305db37c929161f3bdb9b839/include/seqan3/range/container/concatenated_sequences.hpp#L997-L1045

It requires a `forward_iterator`, but `last - first` is only available for `random_acesss_iterator`s

We need a test case for this, where we use `std::forward_list`.

**Comment by h-2** [comment]
Good catch!

**Comment by rrahn** [comment]
Is this still open?

**Comment by smehringer** [comment]
This was fixed by #212 long ago.
