### ISSUE TITLE
Remove "using namespace seqan3;" from DOC - Tutorial

### ISSUE THREAD

**Issue by Irallia** [seqan/seqan3#1364]
Chapters:
- [x] First steps
- [x] Parsing command line arguments
- [x] C++ Concepts
- [x] Alphabets
- [x] Ranges
- [x] Sequence file I/O
- [x] Computing pairwise alignments
- [x] Index and Search
- [x] Alignment file I/O
- [x] Implement your own read mapper

**Comment by smehringer** [comment]
Maybe make one PR per tutorial and in the code per module, such that the PRs don't become too big :)
