### ISSUE TITLE
add an EditorConfig for code formatting

### ISSUE THREAD

**Issue by mr-c** [seqan/seqan3#1383]
https://editorconfig.org/

**Comment by marehr** [comment]
This seems to be a subset of what you can specify in clang-format, which is currently on hold because of missing concept support (see https://github.com/seqan/seqan3/projects/22#card-27117674), and I think it would be a good addition.

If you want to provide a PR, I would review it.

**Comment by mr-c** [comment]
Thanks @marehr , I opened a PR at https://github.com/seqan/seqan3/pull/1384
