### ISSUE TITLE
uppercase field IDs are broken not deprecated

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1452]
While keeping and deprecating the values might have been well-intended, it doesn't work anyway because the files complain that they don't know the values...

We are seriously breaking everything anyway, we might as well remove the uppercase version directly.

**Comment by smehringer** [comment]
I know but the error message is nicer that way because it first warns you that it is deprecated and can be simply replaced by the lowercase version... 
Since this is a feature that is probably used already, I would favour the depreciation anyway.
