### ISSUE TITLE
build failure on simple BAM i/O

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1456]
The following program fails to build with some errors in debug_stream.

```cpp
#include <seqan3/io/alignment_file/all.hpp>

using namespace seqan3;

int main(int, char ** argv)
{
    alignment_file_input{argv[1]} | alignment_file_output{argv[2]};
}
```

Adding `#include <sstream>` fixes it. Possibly related to #1423

**Comment by Irallia** [comment]
I built your snippet with GCC7 and GCC9, but couldn't reproduce the error.

**Comment by h-2** [comment]
I cannot reproduce anymore, either.
