### ISSUE TITLE
Exception on opening example bam file

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1457]
This file:
https://figshare.com/articles/Example_BAM_file/1460736

triggers:
```
terminate called after throwing an instance of 'seqan3::format_error'
  what():  Illegal SAM header tag in @HG starting with:L
```

According to samtools view, the entire header is:
```
@SQ     SN:1    LN:30427671
@SQ     SN:2    LN:19698289
@SQ     SN:3    LN:23459830
@SQ     SN:4    LN:18585056
@SQ     SN:5    LN:26975502
@SQ     SN:M    LN:366924
@SQ     SN:C    LN:154478
```

And according to the SAM spec this is very valid, it gives the following example itself: `@SQ SN:ref LN:45`...

**Comment by h-2** [comment]
The problem is that our I/O always expects a "@HD line" but this isn't always present. SeqAn2 and samtools don't complain about this. The spec says:

>   Each  SAM  and  BAM  file  mayoptionally specify the version being used via the@HD VN tag.

So it's only optional.

**Comment by smehringer** [comment]
Damn. I really thought the header line is required :expressionless:
