### ISSUE TITLE
Design of error configurations

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1458]
This didn't fit into a card, so I'll post it here. The following is really overly verbose:
```cpp
    seqan3::configuration const default_cfg = seqan3::search_cfg::max_error{seqan3::search_cfg::total{0},
                                                                            seqan3::search_cfg::substitution{0},
                                                                            seqan3::search_cfg::insertion{0},
                                                                            seqan3::search_cfg::deletion{0}}
```

And the implementation of the config also has it's complexity with being agnostic of the order of parameter...

I would instead propose the following:

```cpp
struct max_error
{
    int32_t total = 0;
    int32_t substitutions = -1;
    int32_t insertions = -1;
    int32_t deletions = -1;

    max_error set_total(int32_t const new_total)
    {
        total = new_total;
        return *this;
    }
    
    max_error set_substitutions(int32_t const new_substitutions)
    {
        substitutions = new_substitutions;
        return *this;
    }

    max_error set_insertions(int32_t const new_insertions)
    {
        insertions = new_insertions;
        return *this;
    }

    max_error set_deletions(int32_t const new_deletions)
    {
        deletions = new_deletions;
        return *this;
    }
};

// ...

// GCC == 7
auto cfg = seqan3::search_cfg::max_error{}.set_total(1).set_deletions(0);

// GCC >= 8
auto cfg = seqan3::search_cfg::max_error{.total = 1, .deletions = 0};

// works everywhere:
auto cfg = seqan3::search_cfg::max_error{1, 1, 1, 0};
```

Designated initialisers actually work since GCC8 so most of our users will be able to use the very simple style. Even on GCC7 the style above looks much simpler to me. It also avoids having to write the nested namespace again and again.

In general, I am unhappy that we have "config elements" and then we also "config element arguments" that appear just like config elements but are actually "configurators" for other config elements. It already confuses me, and I am sure our users will also be confused about what is a configuration element and what isn't.

**Comment by smehringer** [comment]
I agree that we are missing a clear separation of config elements and config element arguments.
But your solution is what we wanted to avoid in the first place because
```
auto cfg = seqan3::search_cfg::max_error{1, 1, 1, 0};
```
is error prone without strong types. and with strong types it will be just as verbose :(
I don't know if we need to discuss this again since we already had a lengthy discussion about the namespace that was related to this.

**Comment by rrahn** [comment]
There is another problem to that. Not all configuration elements are at the moment aggregates and thus there would be inconsistencies in the usage. Changing, if possible, this needs some more design discussions.

**Comment by rrahn** [comment]
This was extensively discusse in https://github.com/orgs/seqan/projects/4#card-31347419 and we have found a resolution that will be implemented now for the search and later subsequently for the alignment.
