### ISSUE TITLE
build fails: latest seqan3 dev + rangv3 0.10 on Debian dev 

### ISSUE THREAD

**Issue by mr-c** [seqan/seqan3#1479]
## Platform

  - SeqAn version:
Using https://github.com/seqan/seqan3/commit/b42671eac39ba0b47c054c4e9767268840dbbdca and range-v3 0.10.0-1
  - Operating system: `Linux mrc-tux 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 GNU/Linux`

  - Compiler: `c++ (Debian 9.2.1-22) 9.2.1 20200104`

### How to repeat the problem

I can provide a Dockerfile, if needed

### Expected behaviour

Successful build followed by tests passing

### Actual behaviour

Build fails:

`/build/seqan3-3.0.0.0.git.20200110.b42671eac39/include/seqan3/range/decorator/gap_decorator.hpp:297:13: error: no match for ‘operator=’ (operand types are ‘seqan3::gap_decorator<std::span<seqan3::dna4, -1> >’ and ‘seqan3::detail::view_take<std::span<seqan3::dna4, -1>, false, false>’)`

https://gist.github.com/mr-c/12d1031685d347b88cc2bae4140d1dfd

**Comment by marehr** [comment]
Will be fixed with #1471

**Comment by mr-c** [comment]
@marehr I can confirm, thanks! I thought the [other commit](https://github.com/seqan/seqan3/pull/1471/commits/dac26d5610b4478176e250eafb4181f1f1f202e4) wasn't needed; pardon the noise.
