### ISSUE TITLE
Get rid of trailing white-spaces

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#1505]
We have some places with trailing white-spaces (found by #1503):

* [x] https://github.com/seqan/seqan3/blob/6391aaa014db4d04b8220a2041014295c4134f33/include/seqan3/alignment/scoring/all.hpp#L18
* [x] https://github.com/seqan/seqan3/blob/6391aaa014db4d04b8220a2041014295c4134f33/test/unit/search/search_scheme_algorithm_test.cpp#L137
* [x] https://github.com/seqan/seqan3/blob/6391aaa014db4d04b8220a2041014295c4134f33/include/seqan3/alignment/scoring/all.hpp#L18
* [x] This one is a bit more complicated, every line should be wrapped in "" and have a explicit endline "\n":
  https://github.com/seqan/seqan3/blob/0388ed42586ebe6617870aa2c8169fe1dfd358c5/test/unit/argument_parser/detail/format_man_test.cpp#L27-L85

**Comment by smehringer** [comment]
@simonsasse Can you look into this? If you have any questions you can ask me or @marehr
