### ISSUE TITLE
views::translate_join | views::deep{std::views::reverse} causes ICE

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1520]
[ see #1519 for code example] 

This small test case leads to a very complex build failure on GCC7 and to an ICE on GCC9.

It is triggered e.g. when wanting to create a bidirectional index using views::translate_join which is arguably a very useful use-case.

I have spent several hours trying to get to the bottom of this, but was not successfull. I recommend opening an issue with GCC.

Here are my notes:

  * It is neither specific to views::deep (you can trigger it by doing a std::views::transform on the outer range and manually calling std::views::reverse inside)
  * nor is it specific to std::views::reverse. I implemented an entire custom seqan3::views::reverse to verify this, it also triggers the problem and also a few other views that I tested (but not all of them).
  * Surprisingly it is not the statement defining the view that triggers the compiler problem, instead it happens on access. [Code compiles cleanly if the view is never accessed] But it is also not the comparison, simply reading the first element is sufficient.

**Comment by marehr** [comment]
One reduced test case is:

```
template <typename> concept bool a = true;
template <int> struct b {};
template <typename g> using c = b<a<g>>;
struct h {
  template <typename g> auto operator()(g) noexcept(noexcept(c<g>{})) {}
};
template <typename d> concept bool e = requires(d f) { h{}(f); };
static_assert(e<int>);
```
This one is fixed in gcc-10, and only ices in gcc9 and works in gcc 7 and 8.

**Comment by marehr** [comment]
I guess it is this bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93345

**Comment by eseiler** [comment]
As we already dropped gcc-9, there's nothing to fix any more. We will add https://github.com/seqan/seqan3/pull/1519 as regression test.
