### ISSUE TITLE
can't run the v3.0.1 tests against an installed copy of seqan

### ISSUE THREAD

**Issue by mr-c** [seqan/seqan3#1521]
## Platform

  - SeqAn version: 3.0.1
  - Operating system: Linux mrc-tux 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
  - Compiler: g++ (Debian 9.2.1-23) 9.2.1 20200110

### How to repeat the problem

Build and install the libseqan3-dev version 3.0.1 Debian package
and run this script: https://salsa.debian.org/med-team/seqan3/blob/master/debian/tests/run-tests from the root of the source package

### Expected behaviour
Tests build and execute successfully

### Actual behaviour

```
[  7%] Building CXX object alignment/matrix/CMakeFiles/edit_distance_trace_matrix_full_test.dir/edit_distance_trace_matrix_full_test.cpp.o
cd /tmp/autopkgtest.ZZbmhm/autopkgtest_tmp/build_unit/alignment/matrix && /usr/bin/ccache /usr/bin/c++  -DSEQAN3_HAS_BZIP2=1 -DSEQAN3_HAS_ZLIB=1 -I/tmp/autopkgtest.ZZbmhm/autopkgtest_tmp/build_unit/vendor/googletest/googletest/include -I/tmp/autopkgtest.ZZbmhm/autopkgtest_tmp/unit/SEQAN3_CLONE_DIR-NOTFOUND/test/include -isystem /usr/include/seqan3/submodules/sdsl-lite/include  -O3 -DNDEBUG   -pedantic -Wall -Wextra -Werror -std=c++17 -fconcepts -pthread -o CMakeFiles/edit_distance_trace_matrix_full_test.dir/edit_distance_trace_matrix_full_test.cpp.o -c /tmp/autopkgtest.ZZbmhm/autopkgtest_tmp/unit/alignment/matrix/edit_distance_trace_matrix_full_test.cpp
/tmp/autopkgtest.ZZbmhm/autopkgtest_tmp/unit/alignment/matrix/edit_distance_trace_matrix_full_test.cpp:11:10: fatal error: seqan3/test/pretty_printing.hpp: No such file or directory
   11 | #include <seqan3/test/pretty_printing.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by mr-c** [comment]
I'm guessing `SEQAN3_CLONE_DIR-NOTFOUND` is the issue

**Comment by marehr** [comment]
To build our test we need additional header files that are only used for tests.

You somehow miss an include to <code>[seqan3/test/include/](https://github.com/seqan/seqan3/tree/master/test/include)</code>.

**Comment by mr-c** [comment]
Yep, cmake didn't find it, so we ended up with `-I/tmp/autopkgtest.ZZbmhm/autopkgtest_tmp/unit/SEQAN3_CLONE_DIR-NOTFOUND/test/include ` instead

**Comment by mr-c** [comment]
I'm trying out https://github.com/seqan/seqan3/pull/1386 again

**Comment by marehr** [comment]
Yes, I thought this change was already merged. I think with that patch it should work again.
