### ISSUE TITLE
[DOC] Move documentation to seqan3 subdirectory

### ISSUE THREAD

**Issue by eseiler** [seqan/seqan3#1540]
Context: https://github.com/seqan/seqan3/pull/1526#discussion_r371670872

* [ ] SetUp Documentation builds on push to master via GitHub Actions

**Comment by eseiler** [comment]
On second thought, it would be better to redirect the old URLs to the new one, such that when someone visits `https://docs.seqan.de/seqan/3-master-user/` they get redirected to the new URL.
We link to the documentation in some places outside the repository (packages, etc.).

**Comment by rrahn** [comment]
So if I understand the resolution from today correctly we can close this. Please, reopen if I am  wrong about this. It is late 😴
