### ISSUE TITLE
Search on bi_fm_index finds too many results

### ISSUE THREAD

**Issue by SGSSGene** [seqan/seqan3#1542]
## Platform

  - SeqAn version: master (b0b27968), also happens on older master (3937c594)
  - Operating system: `linux schenker 5.4.13-arch1-1 #1 SMP PREEMPT Fri, 17 Jan 2020 23:09:54 +0000 x86_64 GNU/Linux`
  - Compiler: gcc 9.2.0

## Description
Searches on an bi_fm_index can lead to results which have more errors than specified.

### How to repeat the problem
Code that I used

```c++
// swapping format.h and ranges will "fix" the issue
#include <fmt/chrono.h>
#include <fmt/color.h>
#include <fmt/format.h>


#include <seqan3/alphabet/all.hpp>
#include <seqan3/core/debug_stream.hpp>
#include <seqan3/io/sequence_file/all.hpp>
#include <seqan3/io/sequence_file/all.hpp>
#include <seqan3/search/algorithm/search.hpp>
#include <seqan3/search/fm_index/bi_fm_index.hpp>
#include <seqan3/std/filesystem>
#include <seqan3/std/ranges>
#include <seqan3/test/performance/sequence_generator.hpp>

using namespace seqan3;

int main(int argc, char * argv[]) {

	auto genome = std::vector<std::vector<seqan3::dna4>>{seqan3::test::generate_sequence<seqan3::dna4>(100'000'000, 0, 0)};

    auto index = seqan3::bi_fm_index{genome};
    // Note: instead of creating a new index, we reload the index
    //decltype(seqan3::bi_fm_index{genome}) index;
	//{
		//std::ifstream is{"index-random.file", std::ios::binary};
		//cereal::BinaryInputArchive iarchive{is};
		//iarchive(index);
	//}


	// create query - since it uses the same seed as an the index creation, we will have a result at pos 0
	auto queries = std::vector<std::vector<seqan3::dna4>>{};
	for (int i{0}; i < 1; ++i) {
		queries.push_back(seqan3::test::generate_sequence<seqan3::dna4>(20, 0, i));
	}

	{
		seqan3::configuration const cfg = seqan3::search_cfg::max_error{
		    seqan3::search_cfg::total{3},
		    seqan3::search_cfg::substitution{3},
		    seqan3::search_cfg::insertion{0},
		    seqan3::search_cfg::deletion{0}};

		auto all_hits = seqan3::search(queries, index, cfg);
		for (auto hits : all_hits) {
			for (auto [genome_index, pos] : hits) {
				// print query
				seqan3::debug_stream << queries[0] << "\n";

				// print segment in genome
				auto seq = genome[genome_index] | std::ranges::views::drop(pos) | std::ranges::views::take(20);
				seqan3::debug_stream << seq << "\n---\n";
			}
		}

	}

    return 0;
}
```

### Expected behaviour
Expected all results to differ in up to 3 positions.

### Actual behaviour
the 2nd result differs in way more then 3 positions.

Output:
```
GGTGTGTCGGCCCTATCCCT
GGTGTGTCGGCCCTATCCCT
---
GGTGTGTCGGCCCTATCCCT 
GAGCCAGCGGCCCTATCGCT # to many errors here!
---
GGTGTGTCGGCCCTATCCCT
GGTGTGTCCTCCCTATCCCT
---
GGTGTGTCGGCCCTATCCCT
GGTGTGACGGCCCTATTCGT
---
```

**Comment by eseiler** [comment]
Doesn't happen with `auto genome = std::vector<seqan3::dna4>{seqan3::test::generate_sequence<seqan3::dna4>(100'000'000, 0, 0)};`, i.e. index over single text instead of collection.
Will have a look at it.

**Comment by eseiler** [comment]
"Smaller" example:

```cpp
#include <seqan3/alphabet/nucleotide/dna4.hpp>
#include <seqan3/core/debug_stream.hpp>
#include <seqan3/io/sequence_file/output.hpp>
#include <seqan3/search/algorithm/search.hpp>
#include <seqan3/test/performance/sequence_generator.hpp>

int main(int argc, char * argv[]) {

	auto genome = std::vector<seqan3::dna4_vector>{seqan3::test::generate_sequence<seqan3::dna4>(100'000'000, 0, 0)};

    {
        seqan3::sequence_file_output fout{"genome.fasta"};
        fout.emplace_back(genome[0], "GENOME");
    }

    auto index = seqan3::bi_fm_index{genome};

	auto query = seqan3::dna4_vector{seqan3::test::generate_sequence<seqan3::dna4>(20, 0, 0)};

    {
        seqan3::sequence_file_output fout{"query.fasta"};
        fout.emplace_back(query, "QUERY");
    }

	seqan3::configuration const cfg = seqan3::search_cfg::max_error{
	    seqan3::search_cfg::total{3},
	    seqan3::search_cfg::substitution{3},
	    seqan3::search_cfg::insertion{0},
	    seqan3::search_cfg::deletion{0}};

	auto hits = seqan3::search(query, index, cfg);

	for (auto [genome_index, pos] : hits)
    {
		seqan3::debug_stream << pos << '\n';
        (void) genome_index;
	}

    return 0;
}
```
Output
```
0
19457938
80378021
89870243
```

SeqAn2 version:

```cpp
#include <seqan/index.h>
#include <seqan/seq_io.h>

using namespace seqan;

int main()
{
    CharString id;
    DnaString genome;

    {
        SeqFileIn seqFileIn("genome.fasta");
        readRecord(id, genome, seqFileIn);
    }

    Index<DnaString, BidirectionalIndex<FMIndex<> > > index(genome);

    std::vector<size_t> positions;

    auto delegate = [&positions](auto & iter, DnaString const & needle, uint8_t errors)
    {
        for (auto occ : getOccurrences(iter))
            positions.push_back(occ);
    };


    DnaString pattern("GGTGTGTCGGCCCTATCCCT");
    std::cout << "Hits with up to 3 errors (HammingDistance):" << std::endl;
    find<0, 3>(delegate, index, pattern, HammingDistance());

    std::sort(positions.begin(), positions.end());
    auto last = std::unique(positions.begin(), positions.end());
    positions.erase(last, positions.end());
    for (int i : positions)
        std::cout << i << '\n';

    return 0;
}
```
Yields correct results:
```
0
80378021
89870243
```

Bug does not occurr if at least one of the following is true:
* Use single genome instead of a collection
* Use `fm_index` instead of `bi_fm_index`
* Do not use OSS but backtracking

**Comment by SGSSGene** [comment]
I tried to reduce your example even more:
I used `24` as my genome length, and `9` as my query length.
This finds exactly one match which is wrong.

Even more interestingly, if I use `23` as my genome length, the program crashes.

**Comment by SGSSGene** [comment]
Hier noch ein kleiner Fund: wenn ich die Zeile
https://github.com/seqan/seqan3/blob/bafab581bddf3d523c0c816629db42008966b442/include/seqan3/search/fm_index/fm_index.hpp#L283

nach
```
sdsl::int_vector<8> tmp_text(text_size - 1);
```
ändere und die nach folgende Zeilen entferne:

https://github.com/seqan/seqan3/blob/bafab581bddf3d523c0c816629db42008966b442/include/seqan3/search/fm_index/fm_index.hpp#L310-L311

Dann scheint das zu funktionieren. Da wir aber auf den fwd_index `locate` ausführen würde ich erwarten das wir beliebig viele delemiter an Ende unseres Textes hängen können, ohne das es zu problemen kommt.

**Comment by eseiler** [comment]
Thanks for find the way shorter example text 👍 

Removing the lines as you described also fixes the issue for _this_ case.
However, it also reintroduces a previously fixed issue:

https://github.com/seqan/seqan3/blob/e1e93182908aea002959c38dde57fd3b6d8bc86b/test/unit/search/search_collection_test.cpp#L126-L136

With the lines removed, it will find, e.g., "ACG", "ACGT", "ACGA", "ACGAT", but "ACGAX" with X from {A,C,G} already fails.

**Comment by SGSSGene** [comment]
Some more findings:

https://github.com/seqan/seqan3/blob/e1e93182908aea002959c38dde57fd3b6d8bc86b/include/seqan3/search/fm_index/bi_fm_index_cursor.hpp#L330-L338

I believe these lines are wrong.
It should be `c <= sigma` and `if (c <= sigma)`. Otherwise highest symbol from the alphabet dosn't gets searched for. (Same issue in `extend_left`, `cycle_back` and `cycle_front`).

(Still digging more)

**Comment by SGSSGene** [comment]
I hope any of this, is any helpful:

```
  // equal to GGTGTGTCGGCCCTATCCCTTGC
  auto genome = std::vector<std::vector<seqan3::dna4>>{seqan3::test::generate_sequence<seqan3::dna4>(23, 0, 0)};

auto cur = index.begin();
// cur should be fwd_lb=0, fwd_lb=24, rev_lb=0, rev_lb=24 - which is true
cur.extend_right("G"_dna4);
// cur should be fwd_lb=10, fwd_lb=16, rev_lb=10, rev_lb=16 - which is true
cur.extend_left("C"_dna4);
// cur should be fwd_lb=7, fwd_lb=7, rev_lb=12, rev_lb=12 - which is not true (maybe fwd/rev are swapped, not sure, than it would be wrong)
cur.locate(); // this crashes
```

**Comment by SGSSGene** [comment]
About the crash, I believe it has to do with this line:

https://github.com/seqan/seqan3/blob/e1e93182908aea002959c38dde57fd3b6d8bc86b/include/seqan3/search/fm_index/bi_fm_index_cursor.hpp#L953

Where offset() is just `return index->size() - depth - 1`.
The issue is that `depth` is the amount of steps to the left and the right.
But since we are using the `fwd_index` for locating, we should only count the amount of steps we did only on the `fwd_index` (current `depth` counts all steps (fwd_index and rev_index))

With this fix it looks a lot more like it. Just need to figure out what is going wrong with `cur.extend_left("C"_dna4)`.

**Comment by SGSSGene** [comment]
Ok, I think I found the final piece. `wavelet_tree::lex_count` doesn't do what we expect it to do.
(I changed a few `private:` to `public:`)
```
for (int i{0}; i < 5; ++i) {
  auto [r, s, b] = index.rev_fm.index.wavelet_tree.lex_count(0, 24, i);
  fmt::print("count: {} {}\n", i, s);
}
```
The output looks as follows:
```
count: 0 0
count: 1 0 // unexpected. This should be 1, every other entry from here should be one bigger
count: 2 1
count: 3 9
count: 4 16
```

This would explain all errors we have seen.
So in summary:
• The old fix, which added a delimiter at the end, wasn't fixing anything
• search is broken, by leaving out some searches `c < sigma` => `c <= sigma`.
• locate is broken, it uses the query_length, instead of the steps that the search made on the `fwd_index`
• `wavelet_tree::lex_count` doesn't return the value we expect for "smaller" (same for bigger?). It seems to be off by one, because it isn't counting its own delimiter.

**Comment by eseiler** [comment]
Thanks for all the work!

> Ok, I think I found the final piece. `wavelet_tree::lex_count` doesn't do what we expect it to do.
> (I changed a few `private:` to `public:`)
> 
> ```
> for (int i{0}; i < 5; ++i) {
>   auto [r, s, b] = index.rev_fm.index.wavelet_tree.lex_count(0, 24, i);
>   fmt::print("count: {} {}\n", i, s);
> }
> ```

You need to call `auto [r, s, b] = index.rev_fm.index.wavelet_tree.lex_count(0, 25, i);` since it's an half open interval (with 24 you exclude the sentinel).

**Comment by SGSSGene** [comment]
Oh no, you are right. It should be 25. But why am I excluding the sentinel with 24?

Our Index should look roughly like this:
```
F                      L
$GGTGTGTCGGCCCTATCCCTTGC
ATCCCTTGC$GGTGTGTCGGCCCT
C$GGTGTGTCGGCCCTATCCCTTG
CCCTATCCCTTGC$GGTGTGTCGG
CCCTTGC$GGTGTGTCGGCCCTAT
CCTATCCCTTGC$GGTGTGTCGGC
CCTTGC$GGTGTGTCGGCCCTATC
CGGCCCTATCCCTTGC$GGTGTGT
CTATCCCTTGC$GGTGTGTCGGCC
CTTGC$GGTGTGTCGGCCCTATCC
GC$GGTGTGTCGGCCCTATCCCTT
GCCCTATCCCTTGC$GGTGTGTCG
GGCCCTATCCCTTGC$GGTGTGTC
GGTGTGTCGGCCCTATCCCTTGC$
GTCGGCCCTATCCCTTGC$GGTGT
GTGTCGGCCCTATCCCTTGC$GGT
GTGTGTCGGCCCTATCCCTTGC$G
TATCCCTTGC$GGTGTGTCGGCCC
TCCCTTGC$GGTGTGTCGGCCCTA
TCGGCCCTATCCCTTGC$GGTGTG
TGC$GGTGTGTCGGCCCTATCCCT
TGTCGGCCCTATCCCTTGC$GGTG
TGTGTCGGCCCTATCCCTTGC$GG
TTGC$GGTGTGTCGGCCCTATCCC
```

As far as I understand `lex_count` check how many chars smaller than `c` exists in column L between row i and j. If we leave out the last column we would forget to count a C not an `$`

**Comment by SGSSGene** [comment]
I disagree on my finding yesterday. locate is not broken.
It is correct the way it is implemented.

**Comment by SGSSGene** [comment]
Oh. The issue is just the final delemiter we add.
The problem is how we "reverse" text.
Usually we have text "AACC$" and the reversed text "CCAA$". 
Notice how the '$' is always at the end (it might always be always at the beginning, not sure how sdsl does it). This doesn't matter for single text. but this is no problem since "$CCAA" is a shifted version of "CCAA$" and will be included in our index.

In collection we have another special delimiter called "Z".
So a text would look like this:
"AACCZGGTT$" and reversed "TTGGZCCAA$"
Here is also no problem. Since "$TTGGZCCAA" is a shifted version of "TTGGZCCAA$"

But for collections with a single entry, we add our delimiter "Z" in the wrong way
"AACCZ$" and reversed "CCAAZ$".
The correct inverse would be "$ZCCAA" but this is not a shifted version of "CCAAZ$".

What do you think?

**Comment by eseiler** [comment]
Yes, that seems to be the problem 👍 

```
In bifm ctor [GGTGTGTCGGCCCTATCCCTTGC]
FWD
In FM ctor [GGTGTGTCGGCCCTATCCCTTGC]
In FM ctor; input for SDSL [5,2,3,4,4,2,2,2,4,1,4,2,2,2,3,3,2,4,3,4,3,4,3,3]
REV
In FM ctor [CGTTCCCTATCCCGGCTGTGTGG]
In FM ctor; input for SDSL [5,3,3,4,3,4,3,4,2,3,3,2,2,2,4,1,4,2,2,2,4,4,3,2]
```

Obviously, one result is not the reverse of the other.

Here is a simple patch that fixes the issue (without breaking other tests)

```patch
From 4a52027f2bb44e1bb4e469c742993ad7df3b1e84 Mon Sep 17 00:00:00 2001
From: Enrico Seiler <enrico.seiler@hotmail.de>
Date: Thu, 13 Feb 2020 13:40:42 +0100
Subject: [PATCH 1/1] Fix #1542

---
 .../seqan3/search/fm_index/bi_fm_index.hpp    |  2 +-
 include/seqan3/search/fm_index/fm_index.hpp   | 27 ++++++++++++++-----
 2 files changed, 21 insertions(+), 8 deletions(-)

diff --git a/include/seqan3/search/fm_index/bi_fm_index.hpp b/include/seqan3/search/fm_index/bi_fm_index.hpp
index d8b3d101..2126faa8 100644
--- a/include/seqan3/search/fm_index/bi_fm_index.hpp
+++ b/include/seqan3/search/fm_index/bi_fm_index.hpp
@@ -156,7 +156,7 @@ private:
         auto rev_text = text | views::deep{std::views::reverse} | std::views::reverse;
 
         fwd_fm = fm_index_type{text};
-        rev_fm = fm_index_type{rev_text};
+        rev_fm = fm_index_type{rev_text, true};
     }
 
 public:
diff --git a/include/seqan3/search/fm_index/fm_index.hpp b/include/seqan3/search/fm_index/fm_index.hpp
index d7ec5c42..6d36f14f 100644
--- a/include/seqan3/search/fm_index/fm_index.hpp
+++ b/include/seqan3/search/fm_index/fm_index.hpp
@@ -230,7 +230,7 @@ private:
     //!\cond
         requires text_layout_mode_ == text_layout::collection
     //!\endcond
-    void construct(text_t && text)
+    void construct(text_t && text, bool rev = false)
     {
         static_assert(std::ranges::bidirectional_range<text_t>, "The text collection must model bidirectional_range.");
         static_assert(std::ranges::bidirectional_range<reference_t<text_t>>,
@@ -280,7 +280,7 @@ private:
         text_begin_rs = sdsl::rank_support_sd<1>(&text_begin);
 
         // last text in collection needs no delimiter if we have more than one text in the collection
-        sdsl::int_vector<8> tmp_text(text_size - (std::ranges::distance(text) > 1));
+        sdsl::int_vector<8> tmp_text(text_size - 1);
 
         constexpr uint8_t delimiter = sigma >= 255 ? 255 : sigma + 1;
 
@@ -306,11 +306,18 @@ private:
                           std::ranges::begin(tmp_text));
 
 
-        // we need at least one delimiter
-        if (std::ranges::distance(text) == 1)
-            tmp_text.back() = delimiter;
-
-        std::ranges::reverse(tmp_text);
+        if (rev)
+        {
+            std::ranges::reverse(tmp_text);
+            if (std::ranges::distance(text) == 1)
+                tmp_text.push_back(delimiter);
+        }
+        else
+        {
+            if (std::ranges::distance(text) == 1)
+                tmp_text.push_back(delimiter);
+            std::ranges::reverse(tmp_text);
+        }
 
         sdsl::construct_im(index, tmp_text, 0);
     }
@@ -392,6 +399,12 @@ public:
     }
     //!\}
 
+    template <std::ranges::range text_t>
+    fm_index(text_t && text, bool rev)
+    {
+        construct(std::forward<text_t>(text), rev);
+    }
+
     /*!\brief Returns the length of the indexed text including sentinel characters.
      * \returns Returns the length of the indexed text including sentinel characters.
      *
-- 
2.17.1


```

Since we plan to only support text collections anyway, we might fix this issue while changing the fm_index.

**Comment by SGSSGene** [comment]
Ah, now I see how the sigma stuff works, and why Oo.
`sdsl_index_type` automatically detects `sigma` but checking which is the biggest letter.
`bi_fm_index_cursor` on the other hand computes `sigma` as `_index.fwd_fm.index.sigma - index_t::text_layout_mode`

Since we always add another delimiter `Z` for collection the `sdsl_index_type::sigma` is always 5.
But if we forget to add it, suddenly the whole thing can shrink to what ever the biggest letter is in the text. That also explains why I thought it must be `c <= sigma` instead of `c < sigma`.

Wow, there is a lot of magic going on. Also preventing some optimizations (which might not matter so much).

**Comment by SGSSGene** [comment]
Why do we actually another sentinel? couldn't we just use `0` from the sdsl?

**Comment by eseiler** [comment]
> Why do we actually another sentinel? couldn't we just use `0` from the sdsl?

SDSL adds the delimiter itself and will throw if there is already a `0` in the text (the algorithm needs exactly one `0` as sentinel)
