### ISSUE TITLE
value_list_validator{"foobar"} deduces to value_list_validator<double>

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1545]
... instead of to `value_list_validator<std::string>`, because `char` satisfies `arithmetic`. `char` should be excluded from arithmetic *for the deduction guide*.

**Comment by marehr** [comment]
Example code?

**Comment by h-2** [comment]
Well the example code is exactly the title. If I had time to write a test-case for this, I would have just made a PR that fixes it ^^

**Comment by marehr** [comment]
Please provide code that shows your issue, because as it is right now, your description makes no sense. A string literal "foobar" i.e. of type `char const *` shouldn't deduce to `std::string`.

It shouldn't take to much time to write something like this:

```c++
#include <...>

int main()
{
   ... // should be ..
}
```

**Comment by h-2** [comment]
This works as expected:

```cpp
        parser.add_option(alphabetReductionTmp, 'r', "alphabet-reduction", "Alphabet Reduction for seeding phase.",
            seqan3::option_spec::ADVANCED, seqan3::value_list_validator{"none", "dna4"});
```

Because the mult-argument constructor is picked correctly and CTAD results in the type of `seqan3::value_list_validator` being deduced to `seqan3::value_list_validator<std::string>`.

But the following does not work as expected:

```cpp
        parser.add_option(alphabetReductionTmp, 'r', "alphabet-reduction", "Alphabet Reduction for seeding phase.",
            seqan3::option_spec::ADVANCED, seqan3::value_list_validator{"none"});
```

Because now the deduction guide for "single argument range of arithmetic" is selected and the type is deduced to `seqan3::value_list_validator<double>`.

[Please see the deduction guides in the file if it is unclear why one would want either `string` or `double` ]
