### ISSUE TITLE
create seqan3/core/filesystem.hpp

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#155]
with roughly this content which is currently in test/include/seqan3/test/tmp_file_name.hpp

```cpp
#if __has_include(<filesystem>)
#include <filesystem>
namespace seqan3::filesystem = std::filesystem;
#else
#include <experimental/filesystem>
namespace seqan3::filesystem = std::experimental::filesystem;
#endif // __has_include(experimental/filesystem)
```
Thereby we can just include <seqan3/core/filesystem.hpp> instead of doing a check for the header and also we can use our sub-namespace instead of doing a check for the namespace.

Also add a check to platform.hpp that either <filesystem> or <experimental/filesystem> need to exist.

**Comment by marehr** [comment]
done in #178 by @pirovc
