### ISSUE TITLE
Discuss whether to give up the <alphabet>_vector aliases

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#156]
Should we remove the type alias `dna4_vector`, `dna5_vector`,...?

Observations:
* We don't need those type aliases within the library code itself, because we will always assume containers of alphabet.
* They are simply convenient for our users and for our example codes

Pro arguments for removing:
* They are not much shorter than `std::vector<dna4>`
* They don't obscure the true type behind the `<alphabet>_vector` alias (easier for beginners to understand)
* No (future) developer will assume that the backend of the container is always vector

Pro argument for keeping:
* It is convenient
* It enforces a certain structure on our users (they will adopt to use `dna4_vector` from our examples)
* ...

@rrahn commented on https://github.com/seqan/seqan3/pull/146#pullrequestreview-100350588:
> The main obstacle IMPOV is that we should drop the `dna|rna` alias and maybe also the `dna\d+_vector` as there seems to be no benefit over std::vector<dna\d+>, does it? But we can discuss this offline.

@h-2 said on https://github.com/seqan/seqan3/pull/146#issuecomment-369883319:
> Hm, I would prefer not to. It's really long. Maybe even something shorter, like `dna4vec`? But that would go against our principle of not abbreviating... :thinking: 
I really want something short, though, because it is written often.

**Comment by smehringer** [comment]
We will keep it for now
