### ISSUE TITLE
[MISC] Refactor search algorithm to only work on collections.

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#1596]
A single text will be modelled as a collection of size 1.

This simplified the interface and unifies the return type.

- [x] Beforehand: Check if there is a performance regression for a collection of size 1 compared to a single text right now

**EDIT**: 
The performance drops by roughly 10% if we search for `std::vector<dna4_vector>` instead of `dna4_vector`... So I think this is stalled until the performance regression for collections is improved upon?

**Comment by rrahn** [comment]
I am closing this in favour of seqan/product_backlog#28. I also copied the important informtion about the performance.

**Comment by smehringer** [comment]
You could have just transferred the isssue?

**Comment by rrahn** [comment]
But the other issue was already open. So having two times the same does not help, does it?
