### ISSUE TITLE
fm_index_cursor::path_label for 2D texts should not return views::join | views::slice

### ISSUE THREAD

**Issue by Irallia** [seqan/seqan3#1646]
`fm_index_cursor::path_label` for two-dimensional texts that are random_access_ranges over random_access_ranges should not return `views::join | views::slice` because `views::join` is slow and breaks random access. Instead return a slice on the i-th element of the text.

(Added by h-2)

**Comment by rrahn** [comment]
@Irallia @smehringer do we have benchmarks for this? Did it make returning and/or printing or working with the path label faster?
