### ISSUE TITLE
preview docs for each pull request

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#166]
Make it possible to review the result of documentation from a pull request.

A possible way to implement this:
* [x] #165 builds the doc
* [ ] The generated html files will be uploaded to ~~`api.seqan.de/pr/<id>`~~ `docs.seqan.de/pr/<id>`
* [ ] (Optional) The documentation can be directly opened in the "All checks have..." section

![screen](https://user-images.githubusercontent.com/103778/37033755-53e6ed12-2147-11e8-94c4-8c1b300ffeb6.png)

difficulty: medium - hard

**Comment by rrahn** [comment]
I can work on this, on the next sprint (July) But I guess I can do it for 3.0.1

**Comment by smehringer** [comment]
I think this has no priority though :)
