### ISSUE TITLE
setup code coverage

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#167]
* [x] Find out which tools are available for code coverage
* [x] Where to run the tool? Jenkins, external project?
* [x] We have a lot of small test cases that cover only a small portion; How does the tool handle the merging of different code paths? 
* [x] Coverage of .hpp files instead of .cpp files? Ask @smehringer what she means.
* [x] What tools are there to show the results in a nice way?
* [ ] Github badge for coverage?

difficulty: hard

**Comment by rrahn** [comment]
There is gcov, which has support in cmake. I see some issues with the external libs, though. Not sure if gcov gives us wrong impressions because we can‘t select the scope of what is tested. But maybe there is way.

**Comment by rrahn** [comment]
@marehr can you finish this until next Monday. Otherwise, I'll block it because we need other stuff done.

**Comment by marehr** [comment]
@rrahn Then please see #271; it still awaits your re-review.

**Comment by rrahn** [comment]
@marehr the last open point would be to add badge. I would make for this a new ticket and let someone else work on the badges. We could have them for CI and other toolings as well.

**Comment by marehr** [comment]
resolved by #271; badges should be a separate issue
