### ISSUE TITLE
setup automatic styleguide checking

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#168]
* [ ] What tool should we use?
* [ ] Is it easy to setup locally?
* [ ] Add a ci to test it, is there a external project that handles it for us?

**Comment by rrahn** [comment]
Given my last comment from #172 I think, we can add a git commit hook, so that files are formatted correctly on every commit. Thus, no one needs to hustle with editor setup and there is no need for a CI job I guess.

**Comment by marehr** [comment]
We could also use `clang-tidy` ([1],[2]) and add rules for style-checking [3] ourselves. This would than only issue a warning and no automatic code formatting, but we could specify rules ourselves.

[1] - http://www.labri.fr/perso/fleury/posts/programming/using-clang-tidy-and-clang-format.html
[2] - https://clang.llvm.org/extra/clang-tidy/
[3] - https://clang.llvm.org/extra/clang-tidy/#writing-a-clang-tidy-check

**Comment by h-2** [comment]
I had considered both of these a while a go and came to the conclusion that both will always generate false positives with concepts, especially with `requires requires ` clauses that have something that looks like a function body preceding the function body.
If you can hack around this, this would of course be great, but maybe we should just wait for the next clang release in august which will almost definitely support concepts.

**Comment by h-2** [comment]
For completeness: I also checked uncrustify which at the time didn't even support C++11 properly and said it was years from C++17 support.
