### ISSUE TITLE
[Argument Parser] Make list of options available that were set by the user

### ISSUE THREAD

**Issue by tloka** [seqan/seqan3#1741]
### Situation
I follow a concept that makes program settings based on several sources, including:

- Command line arguments
- Config file
- Other input files (in my case, run info files of Illumina)

### Problem
As far as I understand, there is no easy access to check whether a parameter was set via the command line or not. The only was to find out is to compare to the default value after parsing.
However, this approach would not work if the user should be allowed to reset the default value that would be changed from an external resource (e.g., the Illumina run info file).

### Example
The file doesn't really look like this. However, I hope you get what I mean.

Default read length: 150bp

```
RunInfo.xml
<read_length>250bp</read_length>
```

The user wants to reset the value to 150bp via the command line.  
There is currently no (simple) way to detect whether the internal value of 150 for the respective field comes from the command line or is simply the default - the program therefore can't decide whether to use the value from the RunInfo.xml or not.

### Solution
It would be nice to have a function like `bool argument_parser::option_is_set(std::string long_id)` (and the same for `short_id`) that returns `true` if the option was set by the user (can only be called after parsing).  
Further, it would be convenient if the user could explicitly reset the default without knowing about its value with a `default` keyword, regardless of the option type (`--read-length default`).

**Comment by marehr** [comment]
Thank you for the input. We have put it on our discussion list.

**Comment by tloka** [comment]
I am currently finding several limitations of the argument parser I would like to throw into discussion. Should I open new issues for each point or collect everything here? @marehr @smehringer

**Comment by marehr** [comment]
Very nice! Yeah, I think a ticket for each concern would be better for us to manage. But you can also just create one "meta" ticket and we split that later to work on the single points. Do as you see fit.

**Comment by marehr** [comment]
2020-04-20 Core-Meeting Resolution: We want this; We put it in the next sprint iteration.

**Comment by tloka** [comment]
Btw, For my purpose, I designed a way for me to solve this a bit differently by abusing validators (thanks for the inspiration from [this thread](https://github.com/seqan/seqan3/issues/1744#issuecomment-616956197)):

I defined a set of possible option sources:
```
enum OPTION_SOURCE {
    DEFAULT=0,
    RUNINFO=1,
    SAMPLESHEET=2,
    CONFIGFILE=3,
    COMMANDLINE=4
};
```

Then, for each option I create a pair:
```
std::pair<uint64_t, OPTION_SOURCE> block_size{65536, OPTION_SOURCE::DEFAULT};
```

I created a validator type. Not optimal to use pointers here I guess, I would prefer references. But it looks like I have to use pointers to fulfill the validator requirements. Maybe you have some hint here for me. However, I think in the argument parser this would also be fine for me:
```
template <typename option_value_t>
struct set_option_source_validator
{
    using option_value_type = option_value_t;

    /**
     * The constructor.
     * @param src_ Reference to the source field.
     */
    set_option_source_validator(OPTION_SOURCE * src_) :
        source_{src_}
    {}

    // Constructor
    void operator()(option_value_t const & /*cmp*/) const noexcept
    {
        *source_ = OPTION_SOURCE::COMMANDLINE;
    }

    //!\brief Help message is empty.
    std::string get_help_page_message() const
    {
        return "";
    }

    private:
    OPTION_SOURCE * source_;
};
```

Now, I can use:
```
	parser.add_option(options.block_size.first, 'b', "block-size","Description",
		seqan3::option_spec::ADVANCED, 
                set_option_source_validator<uint64_t>{&options.program.block_size.second});
```

In the main:
```
    if (options.block_size.second == OPTION_SOURCE::COMMANDLINE)
    {
        std::cout   << "Block size set from commandline to "  
                    << options.block_size.first << ".\n";
    }
    else
    {
        std::cout   << "Block size defaulted to " 
                    << options.block_size.first << ".\n";
    }
```

Voila:
```
> ./my_tool --compression gz
Block size defaulted to 65536.
> ./my_tool --block-size 0
Block size set from commandline to 0.
> ./my_tool --block-size 65536
Block size set from commandline to 65536.
```

When building a proper structure around this, this could actually be a nice workaround doing everything automatically for me. Still, I think the originally proposed feature will catch this issue in a much more integrated and easy-to-use way.

However, there remains an obstacle and I am actually not sure what I did wrong here. When trying to chain the new validator like this:
```
	parser.add_option(options.block_size.first, 'b', "block-size","Description",
		seqan3::option_spec::ADVANCED, 
                seqan3::arithmetic_range_validator{1, 65536} | 
                set_option_source_validator<uint64_t>{&options.program.block_size.second});
```

I get:
```
error: no match for ‘operator|’ (operand types are ‘seqan3::arithmetic_range_validator’ and ‘livetools::set_option_source_validator<long unsigned int>’)
```

I already found out that `arithmetic_range_validator` seems to only work with `double`, there is no template type to define. This is, for example, different for `value_list_validator`. There, I can specify to use `uint64_t` which makes it work. However, when not stating it explicitely, it seems to also be using double type although the underlying type of the option is `uint64_t`. Not sure if everything is working with the types here as it should. Am I doing something totally wrong, is this the intended behavior or should I open an issue for this?
