### ISSUE TITLE
Complement view is not working with bitcompressed dna vector

### ISSUE THREAD

**Issue by MitraDarja** [seqan/seqan3#1743]
The seqan3::views::complement given a static_assert error, when using a seqan3::bitcompressed_vector. (Error mesage. "The innermost value type must satisfy the nucleotide_alphabet.") I would expect complement to work on bitcompressed vectors as well.

```cpp
#include <seqan3/alphabet/nucleotide/dna4.hpp>
#include <seqan3/core/debug_stream.hpp>
#include <seqan3/range/container/bitcompressed_vector.hpp>
#include <seqan3/range/views/complement.hpp>

using seqan3::operator""_dna4;

int main()
{
    seqan3::bitcompressed_vector<seqan3::dna4> text1{"ACGTAGC"_dna4};
    auto hashes2 = text1 | seqan3::views::complement;
    seqan3::debug_stream << hashes2 << '\n';
}
```

**Comment by marehr** [comment]
`test/unit/range/views/view_minimiser_test.cpp` has a test which was disabled because of this bug.

**Comment by smehringer** [comment]
> `test/unit/range/views/view_minimiser_test.cpp` has a test which was disabled because of this bug. This should be re-enabled again.

@marehr I don't see the out commented test, can you point me to it?

**Comment by MitraDarja** [comment]
@smehringer It is a test case in the PR #1751 because that is where I need the reverse complement, in the current minimiser view test there was no need for the complement because it only considers one range.

**Comment by smehringer** [comment]
:facepalm: of course. sorry :sweat_smile:
