### ISSUE TITLE
take_until does not work with reverse

### ISSUE THREAD

**Issue by MitraDarja** [seqan/seqan3#1754]
Combining the view take_until with reverse and then using kmer_hash did lead to two separate problems.

First, the static assert in kmer_hash fails, because kmer_hash expects a const-iterability view, which is not true for `seqan3::views::take_until | std::views::reverse`.
Removing the const from the static assert in kmer_hash should solve this problem.

```cpp
auto stop_at_t = seqan3::views::take_until([] (seqan3::dna4 const x) { return x == 'T'_dna4; });
std::vector<seqan3::dna4> textt{"ACGTAGC"_dna4};
seqan3::debug_stream << (textt | stop_at_t | seqan3::views::complement | std::views::reverse
                                                    | seqan3::views::kmer_hash(seqan3::ungapped{4})
                                                    | std::views::reverse) << "\n";
// Leads to a static assert failure
```

Second, using only take_until with reverse did not lead to the correct result:

```cpp
auto stop_at_t = seqan3::views::take_until([] (seqan3::dna4 const x) { return x == 'T'_dna4; });
std::vector<seqan3::dna4> textt{"ACGTAGC"_dna4};
seqan3::debug_stream << (textt | stop_at_t | seqan3::views::complement | std::views::reverse
                                                    | seqan3::views::kmer_hash(seqan3::ungapped{4})
                                                    | std::views::reverse) << "\n";
seqan3::debug_stream << (textt | stop_at_t  | std::views::reverse ) << "\n"; // prints: CGATGCA, not as expected GCA
```

The reason for this behaviour is that take_until does not model `sized_sentinel_for`. A solution for this should be returning `std::ranges::default_sentinel` in the end function of take until.

**Comment by marehr** [comment]
This seems to not have fixed your problem.

**Comment by MitraDarja** [comment]
@marehr 
As you point out in #1751 the problem seems to be that #1751 assumes sizedness, so the bug reported here is solved.

**Comment by marehr** [comment]
Okay I thought that code in that PR was your reason you created this issue.
