### ISSUE TITLE
Add SDSL tests to Jenkins

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan3#176]
We offered to include the SDSL and its tests to our nightlys on Jenkins (and nightlys only so far such that we don't need write-access to the repo) and also include it in CDash.

@rrahn Are you willing to give me access to our Jenkins server so I can set it up myself? :)

**Comment by eseiler** [comment]
Do we want an integration into cdash or can we close this now since SDSL has CI (Travis+Jenkins)?

**Comment by cpockrandt** [comment]
I think we should integrate the SDSL into cdash.
