### ISSUE TITLE
Is field::offset still supported for input SAM files ?

### ISSUE THREAD

**Issue by ppericard** [seqan/seqan3#1765]
## Platform

  - SeqAn version: 3.0.2
  - Operating system: Linux ppericard-matam-dev 5.4.0-21-generic #25-Ubuntu SMP Sat Mar 28 13:10:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  - Compiler: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

## Question

I'm back to developing with SEQan after more than 6 months and a few things changed, which is good ;-)

Previously, when reading SAM files, the field::offset would store the read offset (for soft clipped reads). I noticed that in the current documentation, it is not anymore in the list of fields from reading SAM files. 
https://docs.seqan.de/seqan/3-master-user/tutorial_alignment_file.html#autotoc_md85

Is that a documentation mistake or is it now the case. This read offset is easy to get using the cigar (amazing work BTW adding the cigar field) but I would just need clarification on this point.

**Comment by smehringer** [comment]
Welcome back :)

> I noticed that in the current documentation, it is not anymore in the list of fields from reading SAM files.

Either way, it should just be the documentation. Your link points to the list of fields in the section `Alignment Fields`, and I see `3. seqan3::field::offset`. But the order in the documentation did change (as I noticed inconsistencies) so you might have missed it because of that? Or do you mean something different?

**Comment by ppericard** [comment]
No, you're right that's my mistake. I was thinking the following table indicated which fields were used when reading a SAM file, but it's just a correspondence between the SAM columns and some of these fields. I probably read a bit fast ;-)

**Comment by smehringer** [comment]
No worries :)
