### ISSUE TITLE
Possibly guard non-functional concepts

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#182]
We have situations where concepts enforced lead to differences in overload resolution, i.e.
```cpp
template <integral_concept t>
void name(t const &)
{
    std::cout << "Integral";
}

template <container_concept t>
void name(t const &)
{
    std::cout << "container";
}
```
This is desired and the concepts are required for the functionality.

But we also have cases, where it "only" provides added safety in programming and better documentation, e.g.
```cpp
template <integral_concept t>
void my_special_function(t const &)
{
    // do something with ints, but it doesn't matter whether concept is actually enforced
}
```

Since concept checks are starting to drastically increase compile-time, we could provide a macro that deactivates this during "fast builds":
```cpp
template <SEQAN3_C_GUARD(integral_concept) t>
void my_special_function(t const &)
{
    // do something with ints, but it doesn't matter whether concept is actually enforced
}
```
E.g. in "FAST_MODE" `SEQAN3_C_GUARD` would resolve to just `typename`.

PRO:
 * faster compiles when developing

CON:
* macros and reduced readability

When the io module is finished, we should measure the difference and evaluate this question.

**Comment by rrahn** [comment]
Mhmm, not sure if it is worth the effort, given that compilers will probably optimize this in the future?

**Comment by smehringer** [comment]
We could also use debug asserts in "cases of safety checks" instead of concepts. IMHO this would be more readable than a fast mode macro and gives the opportunity for even more readable error messages if we decide to allow for assert messages.
