### ISSUE TITLE
gcc10: Compile failure on search snippet

### ISSUE THREAD

**Issue by SGSSGene** [seqan/seqan3#1877]
## Platform

  - SeqAn version: cf2505c (6. June)
  - Operating system: `Linux schenker 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux`
  - Compiler: `gcc (GCC) 10.1.0 `

## Description
The snippet `test/snippet/search/search.cpp` does not compiling.

### How to repeat the problem
I used seqan3/app-template and updated seqan3 and replaced `main.cpp` with the content of `test/snippet/search/search.cpp` (Is there a easier way to test compile snippets?)

### Expected behaviour
Expected to compile.

### Actual behaviour
Compile error:
```
In file included from /home/gene/app-template/lib/seqan3/include/seqan3/search/configuration/result_type.hpp:20,
                 from /home/gene/app-template/lib/seqan3/include/seqan3/search/detail/search_configurator.hpp:21,
                 from /home/gene/app-template/lib/seqan3/include/seqan3/search/search.hpp:22,
                 from /home/gene/app-template/src/main.cpp:5:
/home/gene/app-template/lib/seqan3/include/seqan3/search/search_result.hpp: In instantiation of ‘class seqan3::search_result<long unsigned int, seqan3::detail::empty_type, long unsigned int, long unsigned int>’:
/home/gene/app-template/lib/seqan3/include/seqan3/search/detail/search_configurator.hpp:158:68:   required from ‘static auto seqan3::detail::search_configurator::configure_algorithm(const configuration_t&, const index_t&) [with query_t = std::vector<seqan3::dna4>&; configuration_t = seqan3::configuration<seqan3::search_cfg::max_error, seqan3::search_cfg::output<seqan3::detail::search_output_text_position>, seqan3::detail::hit_all_tag>; index_t = seqan3::fm_index<seqan3::dna4, seqan3::collection, sdsl::csa_wt<sdsl::wt_pc<sdsl::balanced_shape, sdsl::int_vector<1>, sdsl::rank_support_v<1, 1>, sdsl::select_support_scan<>, sdsl::select_support_scan<0>, sdsl::byte_tree<> >, 16, 10000000, sdsl::sa_order_sa_sampling<>, sdsl::isa_sampling<>, sdsl::plain_byte_alphabet> >]’
/home/gene/app-template/lib/seqan3/include/seqan3/search/search.hpp:156:79:   required from ‘auto seqan3::search(queries_t&&, const index_t&, const configuration_t&) [with index_t = seqan3::fm_index<seqan3::dna4, seqan3::collection, sdsl::csa_wt<sdsl::wt_pc<sdsl::balanced_shape, sdsl::int_vector<1>, sdsl::rank_support_v<1, 1>, sdsl::select_support_scan<>, sdsl::select_support_scan<0>, sdsl::byte_tree<> >, 16, 10000000, sdsl::sa_order_sa_sampling<>, sdsl::isa_sampling<>, sdsl::plain_byte_alphabet> >; queries_t = std::vector<std::vector<seqan3::dna4> >&; configuration_t = const seqan3::configuration<seqan3::search_cfg::max_error, seqan3::search_cfg::output<seqan3::detail::search_output_text_position>, seqan3::detail::hit_all_tag>]’
/home/gene/app-template/src/main.cpp:20:56:   required from here
/home/gene/app-template/lib/seqan3/include/seqan3/search/search_result.hpp:110:44: error: declaration of template parameter ‘class query_range_t’ with different constraints
  110 |     template <typename search_algorithm_t, typename query_range_t>
      |                                            ^~~~~~~~
In file included from /home/gene/app-template/lib/seqan3/include/seqan3/search/search.hpp:24,
                 from /home/gene/app-template/src/main.cpp:5:
/home/gene/app-template/lib/seqan3/include/seqan3/search/search_result_range.hpp:36:40: note: original declaration appeared here
   36 | template <typename search_algorithm_t, std::ranges::view query_range_t>
      |                                        ^~~
make[2]: *** [src/CMakeFiles/myProject.dir/build.make:83: src/CMakeFiles/myProject.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:197: src/CMakeFiles/myProject.dir/all] Error 2
make: *** [Makefile:115: all] Error 2
```

**Comment by marehr** [comment]
Did you compile in c++17 mode or in c++20 mode?

We currently only support `g++-10 -std=c++17 -fconcepts` (#1502). Support for `g++-10 -std=c++2a` is still in progress (seqan/product_backlog#61).

Everything build at some point, but we unfortunately don't have a CI for gcc10, yet.
So I'm playing a reactive game right now, someone broke something I fix it.

As you can see:
* https://cdash.seqan.de/index.php?project=SeqAn3&parentid=466203 everything build (f397aded8c32a08651c5c5ae55092559ea50694c), one day later
* https://cdash.seqan.de/index.php?project=SeqAn3&parentid=467349 three new build errors (c6f49c4687981b07bbb746a1fbc3846eb50fcf0a), a couple days later
* https://cdash.seqan.de/index.php?project=SeqAn3&parentid=469458 8 new build errors ( 4fcbeb81054318528418dab74d97ec7e9687e2eb) (the one you reported)

I would recommend to use gcc-9 if you need the bleeding edge master,  or you use f397aded8c32a08651c5c5ae55092559ea50694c for now.

**Comment by SGSSGene** [comment]
Hey, thanks for the quick response.
I'm compiling with `-std=c++17 -fconcepts`. (`-std=c++20` didn't seem to work even close)
I assumed that #1502  indicates that gcc10 is working. I probably switch to #f397ade for now.

>> So I'm playing a reactive game right now, someone broke something I fix it.

Doesn't sound like so much fun :/

**Comment by marehr** [comment]
I added gcc-10 to our CI, so I hope we don't have new regressions.
