### ISSUE TITLE
Argument Parser - Port the Version Checker from seqan2

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#189]
* Port only the unix based stuff because windows is not supported yet anyway.
* Adapt functions and interfaces to seqan3 style if necessary
* Check for external libraries again to replace the hacky system calls

**Comment by rrahn** [comment]
We need to check what we need to do, to confirm the DSGVO. Probably, there must be a flag, that prints the legal notice, e.g. what data is stored where. We also need to check if we need to ask for the consent of the user/developer of the app, or if the flag in the argument parser is enough.
