### ISSUE TITLE
[Bug] seqan3::is_in_alphabet has wrong results with gapped alphabets

### ISSUE THREAD

**Issue by joergi-w** [seqan/seqan3#1972]
## Platform

  - SeqAn version: 3.0.2
  - Operating system: macOS 10.15.5
  - Compiler: gcc9

## Description

The implementation for `seqan3::is_in_alphabet` is not correct for gapped alphabets.
I would expect to see the correct results or a compiler error if this case is not implemented.

Hint for a possible solution: There is a function `bool char_is_valid(char_type const chr)` in `alphabet_variant.hpp:578` which is supposed to do the job, but it is actually never called.

### How to repeat the problem

Simply paste the lines below in a snippet like this:

```cpp
using namespace seqan3;
std::cout << std::boolalpha << (is_in_alphabet<gapped<rna5>>('a')) << std::endl;
```

### Expected behaviour

```cpp
is_in_alphabet<gapped<rna5>>('a')    // true
is_in_alphabet<gapped<rna5>>('c')    // true
is_in_alphabet<gapped<rna5>>('g')    // true
is_in_alphabet<gapped<rna5>>('u')    // true
is_in_alphabet<gapped<rna5>>('-')    // true
is_in_alphabet<gapped<rna5>>('n')    // true
is_in_alphabet<gapped<rna5>>('s')    // false
```

### Actual behaviour

```cpp
is_in_alphabet<gapped<rna5>>('a')    // false
is_in_alphabet<gapped<rna5>>('c')    // false
is_in_alphabet<gapped<rna5>>('g')    // false
is_in_alphabet<gapped<rna5>>('u')    // false
is_in_alphabet<gapped<rna5>>('-')    // true
is_in_alphabet<gapped<rna5>>('n')    // false
is_in_alphabet<gapped<rna5>>('s')    // false
```

**Comment by smehringer** [comment]
The problem is that `seqan3::is_in_alphabet` is using the CPO `seqan3::char_is_valid_for` which checks is the following functionality is present:
```cpp
    SEQAN3_CPO_IMPL(3, (deferred_type_t<seqan3::custom::alphabet<alph_t>, decltype(v)>::char_is_valid(v))) // expl. cst.
    SEQAN3_CPO_IMPL(2, (char_is_valid_for(v, s_alph_t{})                                                )) // ADL
    SEQAN3_CPO_IMPL(1, (deferred_type_t<remove_cvref_t<alph_t>, decltype(v)>::char_is_valid(v)          )) // member
    SEQAN3_CPO_IMPL(0, (seqan3::to_char(seqan3::assign_char_to(v, s_alph_t{})) == v                     )) // fallback
```

Unfortunately, the `char_is_valid` member function of `alphabet_variant` was marked protected and could not be found by the CPO so it used the fallback `seqan3::to_char(seqan3::assign_char_to(v, s_alph_t{})) == v`. (Note that checking for upper case letters, e.g. `A`, works as espected.)

I'll submit a patch :)
