### ISSUE TITLE
Error: invalid use of incomplete type 'struct std::tuple_size<std::thread>'

### ISSUE THREAD

**Issue by sagitter** [seqan/seqan3#2010]
Hi all.

Seqan3 building is failing with the reported error:

## Platform

  - SeqAn version: commit bf04354bab903dc7f8c12f3bb478c02cd5f2c553
  - Operating system: Fedora 33
  - Compiler: GNU-10.2.1

## Description

```
/builddir/build/BUILD/seqan3/test/unit/alignment/pairwise/align_pairwise_test.cpp:288:64:   required from here
/usr/include/concepts/concepts.hpp:966:13: error: invalid use of incomplete type 'struct std::tuple_size<std::thread>'
  966 |             META_IS_BASE_OF(U, T) &&
      |             ^~~~~~~~~~~~~~~
In file included from /usr/include/c++/10/bits/unique_ptr.h:36,
                 from /usr/include/c++/10/memory:83,
                 from /usr/include/gtest/gtest.h:57,
                 from /builddir/build/BUILD/seqan3/test/unit/alignment/pairwise/align_pairwise_test.cpp:8:
/usr/include/c++/10/utility:88:12: note: declaration of 'struct std::tuple_size<std::thread>'
   88 |     struct tuple_size;
      |            ^~~~~~~~~~
make[2]: *** [alignment/pairwise/CMakeFiles/align_pairwise_test.dir/build.make:85: alignment/pairwise/CMakeFiles/align_pairwise_test.dir/align_pairwise_test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3060: alignment/pairwise/CMakeFiles/align_pairwise_test.dir/all] Error 2
```

### How to repeat the problem

Compiling `seqan` with `gcc-10.2.1`, `cereal-1.3.0`  `range-v3-0.10.0` `gtest-1.10.0` from system, bundled `sdsl-lite-3.0.0`, on Fedora 33 (devel branch).

### Expected behaviour

No error.

### Actual behaviour

Full build log: https://kojipkgs.fedoraproject.org//work/tasks/8376/48808376/build.log

**Comment by rrahn** [comment]
Mhmm, this looks really really strange. There is no indication of where the std::thread is coming from. Also the respective test that fails does not do anything with parallel execution. So, from purely looking it there seems to be no rational explanation for the error.
And in c++20 mode this compiles through? 
And can you tell me where the `/usr/include/concepts` is coming from? Is that something related to the ranges library? Since in c++17 mode we are using the ranges library as backend and if nothing changed then also the concept implementation is used from the ranges library. But here it looks like we are finding a special concept implementation?

**Comment by marehr** [comment]
@sagitter Thank you for reporting. Could you try to use our pinned version of the ranges-v3 library? 

Your reported issue is actually a defect in the ranges library, see https://github.com/ericniebler/range-v3/issues/1430.

See https://github.com/seqan/seqan3/tree/master/submodules for our pinned versions.

**Comment by rrahn** [comment]
range-v3 has just released a new version :)

**Comment by sagitter** [comment]
> Mhmm, this looks really really strange. There is no indication of where the std::thread is coming from. Also the respective test that fails does not do anything with parallel execution. So, from purely looking it there seems to be no rational explanation for the error.
> And in c++20 mode this compiles through?

```
In file included from /usr/include/c++/10/string:54,
                 from /usr/include/c++/10/bits/locale_classes.h:40,
                 from /usr/include/c++/10/bits/ios_base.h:41,
                 from /usr/include/c++/10/streambuf:41,
                 from /usr/include/c++/10/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/10/iterator:66,
                 from /usr/include/c++/10/bits/ranges_algobase.h:36,
                 from /usr/include/c++/10/bits/ranges_uninitialized.h:36,
                 from /usr/include/c++/10/memory:69,
                 from /usr/include/gtest/gtest.h:57,
                 from /builddir/build/BUILD/seqan3/test/unit/alignment/debug_stream_aligned_sequence_test.cpp:8:
/usr/include/c++/10/bits/range_access.h:862:13:   required for the satisfaction of 'range<_Range>' [with _Range = seqan3::detail::combined_adaptor<ranges::zip_view<ranges::ref_view<const std::vector<seqan3::alphabet_variant<seqan3::rna5, seqan3::gap>, std::allocator<seqan3::alphabet_variant<seqan3::rna5, seqan3::gap> > > >, ranges::ref_view<const std::vector<seqan3::alphabet_variant<seqan3::rna5, seqan3::gap>, std::allocator<seqan3::alphabet_variant<seqan3::rna5, seqan3::gap> > > > >, seqan3::detail::adaptor_from_functor<seqan3::detail::slice_fn, long int, long int> >]
/usr/include/c++/10/bits/range_access.h:862:21:   in requirements with '_Tp& __t' [with _Tp = seqan3::detail::combined_adaptor<ranges::zip_view<ranges::ref_view<const std::vector<seqan3::alphabet_variant<seqan3::rna5, seqan3::gap>, std::allocator<seqan3::alphabet_variant<seqan3::rna5, seqan3::gap> > > >, ranges::ref_view<const std::vector<seqan3::alphabet_variant<seqan3::rna5, seqan3::gap>, std::allocator<seqan3::alphabet_variant<seqan3::rna5, seqan3::gap> > > > >, seqan3::detail::adaptor_from_functor<seqan3::detail::slice_fn, long int, long int> >]
/usr/include/c++/10/bits/range_access.h:864:15: note: the required expression 'std::ranges::__cust::begin(__t)' is invalid
  864 |  ranges::begin(__t);
      |  ~~~~~~~~~~~~~^~~~~
/usr/include/c++/10/bits/range_access.h:865:13: note: the required expression 'std::ranges::__cust::end(__t)' is invalid
  865 |  ranges::end(__t);
      |  ~~~~~~~~~~~^~~~~
make[2]: *** [alignment/CMakeFiles/debug_stream_aligned_sequence_test.dir/build.make:85: alignment/CMakeFiles/debug_stream_aligned_sequence_test.dir/debug_stream_aligned_sequence_test.cpp.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/seqan3/build'
make[1]: *** [CMakeFiles/Makefile2:1791: alignment/CMakeFiles/debug_stream_aligned_sequence_test.dir/all] Error 2
```

> And can you tell me where the `/usr/include/concepts` is coming from? Is that something related to the ranges library? Since in c++17 mode we are using the ranges library as backend and if nothing changed then also the concept implementation is used from the ranges library. But here it looks like we are finding a special concept implementation?

Yes, it comes from the `range-v3` rpm:

```
$ rpm -q --list range-v3-devel | grep concepts
/usr/include/concepts
/usr/include/concepts/concepts.hpp
/usr/include/concepts/swap.hpp
/usr/include/concepts/type_traits.hpp
/usr/include/range/v3/action/concepts.hpp
/usr/include/range/v3/functional/concepts.hpp
/usr/include/range/v3/iterator/concepts.hpp
/usr/include/range/v3/range/concepts.hpp
/usr/include/range/v3/range_concepts.hpp
/usr/include/range/v3/utility/concepts.hpp
/usr/include/range/v3/utility/iterator_concepts.hpp
```
I'm trying to compile with your `range-v3` library.

**Comment by rrahn** [comment]
Yes, I've just learned that there are compatibility issues between range-v3 and the stl ranges. And it seems that it is no easy fix. 

> Yes, it comes from the range-v3 rpm:

Ok, thank you for the info. As @marehr already pointed to this seems to be a fixed bug. So c++17 mode should work with the right ranges version. We'll see that we go to the next ranges-v3 version asap.

**Comment by marehr** [comment]
@sagitter I'll close this issue since it is done from my POV. If you think this issue still persists, please reopen it :)
