### ISSUE TITLE
Confusing Snippet for SAM/BAM bitflag

### ISSUE THREAD

**Issue by tloka** [seqan/seqan3#2100]
In  seqan3/test/snippet/io/alignment_file/sam_flags.cpp  you write:
```c++
if (seqan3::get<seqan3::field::qual>(rec)[0] < seqan3::assign_char_to('@', seqan3::phred42{})) // low quality
{
    // Set a flag value (bit):
    seqan3::get<seqan3::field::flag>(rec) &= seqan3::sam_flag::failed_filter;
    // Note that this does not affect other flag values (bits),
    // e.g. `seqan3::get<seqan3::field::flag>(rec) & seqan3::sam_flag::unmapped` may still be true
}
```

I think, with the description given, it should be (in line 4)
```c++
 seqan3::get<seqan3::field::flag>(rec) |= seqan3::sam_flag::failed_filter;
```
, as `&=` would actually affect other flag values (it would actually set all other flags to 0). 
At least for me, `|=` did what I would expect from your description.

**Comment by eseiler** [comment]
Seems like it should be a `|=`, @smehringer ?

here is the link to the docs https://docs.seqan.de/seqan/3-master-dev/group__alignment__file.html#ga12cf4f15e81e65c02a1a5899b75ca962

**Comment by smehringer** [comment]
Yes, good catch!
