### ISSUE TITLE
field::seq_qual not available for Alignment IO

### ISSUE THREAD

**Issue by tloka** [seqan/seqan3#2101]
Your documentation states that `field::seq_qual` should be available for alignment output (see table in http://docs.seqan.de/seqan/3-master-dev/group__io.html#ga2511b22375848e1bedbc5013c952a817).
However, it's not. I get an assertion failure, and when inspecting the code it's not listed in the enum.

Would be nice to include this to make writing alignment output easier when using qualified alphabets.
Until then, is there an easy way to extract a range / vector of only the quality values from a vector of qualified to pass it separately? I didn't find an easy / efficient way of transforming a qualified vector to a vector of qualities so far, only looping and get<1> worked for me so far...

**Comment by eseiler** [comment]
I'm not sure, if the docs are wrong or the implementation is mssing, but

> Until then, is there an easy way to extract a range / vector of only the quality values from a vector of qualified to pass it separately? I didn't find an easy / efficient way of transforming a qualified vector to a vector of qualities so far, only looping and get<1> worked for me so far...

`seqan3::views::get` should do this: https://docs.seqan.de/seqan/3-master-dev/group__views.html#ga495774efe28bbb266a416eb16b285ba1

**Comment by tloka** [comment]
> `seqan3::views::get` should do this: https://docs.seqan.de/seqan/3-master-dev/group__views.html#ga495774efe28bbb266a416eb16b285ba1

Well, this makes sense .. thanks.

**Comment by smehringer** [comment]
I'll check the documentation but I think we did not implement this as it additionally extends the already huge parameter list for alignment IO. It is a good point though so we will re-evalute this once we starting with IO (I think in October). Either way we should adapt the documentation for now.

**Comment by marehr** [comment]
We'll remove seq_qual from sequence io, see #2379.
