### ISSUE TITLE
Different (wrong) results for FM index search with qualified sequences

### ISSUE THREAD

**Issue by tloka** [seqan/seqan3#2115]
## Platform

  - SeqAn version: 3.0.2
  - Operating system: Ubuntu
  - Compiler: GCC 9.2.1

## Description
When searching a qualified sequence in an FM index using seqan3::search, I get wrong results.  
No idea if this behavior is expected as the ranks are different than with the non-qualified alphabet I create the index with. However, for me the behavior was unexpected, is highly non-intuitive and can quickly lead to wrong behavior when not being aware of this.
See below for a minimal example.

### How to repeat the problem

Code:
```cpp
#include <seqan3/alphabet/nucleotide/dna5.hpp>
#include <seqan3/alphabet/quality/phred42.hpp>
#include <seqan3/alphabet/quality/qualified.hpp>
#include <seqan3/core/debug_stream.hpp>
#include <seqan3/search/fm_index/fm_index.hpp>
#include <seqan3/search/search.hpp>

using seqan3::operator""_dna5;

int main()
{
   // Build Index
   std::vector<seqan3::dna5_vector> genomes{"ACAG"_dna5};
   seqan3::fm_index index{genomes};

   // Create qualified query
   std::vector<seqan3::qualified<seqan3::dna5, seqan3::phred42>> dnaq_query{{'A'_dna5, seqan3::phred42{0}},
                                                                            {'C'_dna5, seqan3::phred42{15}},
                                                                            {'G'_dna5, seqan3::phred42{30}},
                                                                            {'G'_dna5, seqan3::phred42{41}}};

   // Create non-qualified query
   std::vector<seqan3::dna5> dna5_query = "ACGG"_dna5;

   // Search config: allow 1 substitution
   seqan3::configuration cfg = seqan3::search_cfg::max_error_total{seqan3::search_cfg::error_count{1}} |
                               seqan3::search_cfg::max_error_substitution{seqan3::search_cfg::error_count{1}} |
                               seqan3::search_cfg::max_error_insertion{seqan3::search_cfg::error_count{0}} |
                               seqan3::search_cfg::max_error_deletion{seqan3::search_cfg::error_count{0}} |
                               seqan3::search_cfg::hit_all_best;

   // Search both queries in the index
   auto dnaq_search_hits = seqan3::search(dnaq_query, index, cfg);
   auto dna5_search_hits = seqan3::search(dna5_query, index, cfg);

   // Create output
   seqan3::debug_stream << "DNAQ query: " << dnaq_query << "\n";
   seqan3::debug_stream << "DNA5 query: " << dna5_query << "\n";

   seqan3::debug_stream << "DNAQ search output:\n";
   for (auto && result : dnaq_search_hits)
      seqan3::debug_stream << result << '\n';

   seqan3::debug_stream << "DNA5 search output:\n";
   for (auto && result : dna5_search_hits)
      seqan3::debug_stream << result << '\n';
}
```

### Expected behaviour

The output I expected is:
```
DNAQ query: ACGG
DNA5 query: ACGG
DNAQ search output:
<query_id:0, reference_id:0, reference_pos:0>
DNA5 search output:
<query_id:0, reference_id:0, reference_pos:0>
```

I would expect the quality to be ignored for the search. Therefore, I would expect the same search results using `dna5` and `qualified<dna5, ...>` queries.

### Actual behaviour

The output I get is:
```
DNAQ query: ACGG
DNA5 query: ACGG
DNAQ search output:
DNA5 search output:
<query_id:0, reference_id:0, reference_pos:0>
```

Thus, the hit is missing when using the qualified query for the search.
When changing the config to allow 2 errors, I get the hit for the `qualified` version as well, which is even more confusing.
Changing quality values doesn't seem to change anything (though, I just tried few combinations).

### Additional note
Is there any workaround for now? I tried to do `auto dnaq_search_hits = seqan3::search(dnaq_query | seqan3::views::get<0>, index, cfg);` to search only with the `dna5` part of the qualified sequence. However, in this case I get errors when compiling.

**Comment by eseiler** [comment]
Hello Tobias,

this indeed should work. I'll have a look.


In the meantime, you can use `seqan3::views::convert`:
```cpp
auto dnaq_search_hits = seqan3::search(dnaq_query | seqan3::views::convert<seqan3::dna5>, index, cfg);
```

The corresponding header is `<seqan3/range/views/convert.hpp>`

**Comment by tloka** [comment]
Thanks!

**Comment by eseiler** [comment]
https://github.com/seqan/seqan3/pull/2116 Should fix the issue.

**Comment by tloka** [comment]
Thanks, just tried it out, seems to produce correct results now (also tested it in the full scope of my code)!
