### ISSUE TITLE
Open issues with doxygen

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#22]
ordered by priority: 
  - [ ] need a `\complexity` keyword for functions
  - [ ] requires statements in function signatures are ugly
  - [ ]  user defined literals are completely ignored; or has this changed in a newer version?
  - [ ] concept are treated as template variables, is ugly
  - [ ] ```explicit``` constructor attribute not displayed. 
  - [ ] concept documentation should be added to/displayed for classes fulfilling this concept
  - [ ] doxygen uses its own style, not the one in code, e.g.
```
insert (const_iterator pos, value_type const &value)
//                                            ^ there should be a space 
```

**Comment by xenigmax** [comment]
Why don't we move these issues to doc. repository?

**Comment by xenigmax** [comment]
I made issues on seqan3-doc repository.
Please check 

https://github.com/seqan/seqan3-doc/issues/10
https://github.com/seqan/seqan3-doc/issues/11
https://github.com/seqan/seqan3-doc/issues/12
https://github.com/seqan/seqan3-doc/issues/13
https://github.com/seqan/seqan3-doc/issues/14
https://github.com/seqan/seqan3-doc/issues/15
https://github.com/seqan/seqan3-doc/issues/16
