### ISSUE TITLE
Fast5 format support and signal qualities

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#227]
This is the format generated by Oxford Nanopore sequencers. We should try to support it before releasing SeqAn3, as it would be a functional improvement (vs just structural or interface improvements).

This could be a project for Forschungspraktikum or for a good student that does their Programming Praktikum+Bachelor-Thesis with us.

**Comment by smehringer** [comment]
There is a card for this in the projects so I am going to close this issue for now
