### ISSUE TITLE
Add tokenisation support

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#228]
- [x] clean up and merge #207 
- [x] clean up and merge #154 
- [x] add tokenisation functions
- [x] document stream module
- [x] add user doc for parse_conditions properly
- [x] Update parse_conditions to work for `wchar_t`.
- [x] Add to_upper/to_lower functions.
- [x] Add unsupported character exception.
- [x] Gcc bug with concept definition.

**Comment by marehr** [comment]
I checked #207, since it was merged.
