### ISSUE TITLE
Read the T-Coffee library format with block support

### ISSUE THREAD

**Issue by joergi-w** [seqan/seqan3#2281]
Support the full specification of the [T-COFFEE_LIB_FORMAT_01](https://tcoffee.readthedocs.io/en/latest/tcoffee_technical_documentation.html#t-coffee-lib-format-01) such that the t-coffee application can read in the t-coffee library format with ranges of residues. 
Note at the moment only alignment information given as single residue pair is supported, which is quite limiting as many programs can write out the extended format version. 

To the developers: In SeqAn2 there exists only a partial implementation of this format, as the ranges are not supported (`BadLexicalCast` error). 

We received a feature request for this by a user of SeqAn2's T-Coffee app and I'm posting it here such that it will be considered for SeqAn3.

**Comment by smehringer** [comment]
Tracked in https://github.com/seqan/product_backlog/issues/104 but no-one is working on tcoffee currently
