### ISSUE TITLE
[GCC-11] Multiple undefined reference to `std::span<std::tuple...`

### ISSUE THREAD

**Issue by sagitter** [seqan/seqan3#2300]
Hi everyone.

## Platform

  - SeqAn version: 3.0.2 commit ec4c7047baef043c88a557d87ade811d0852eeb4 (+ bundled `sldl-lite` code)
  - Operating system: Fedora 34 (devel branch)
  - Compiler: gcc-11.0.0

## Description
Linker returns multiple errors like:

```
Linking CXX executable global_affine_unbanded_test
cd /builddir/build/BUILD/seqan3/build/alignment/pairwise && /usr/bin/cmake -E cmake_link_script CMakeFiles/global_affine_unbanded_test.dir/link.txt --verbose=1
/usr/bin/g++ -O2  -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -std=c++2a -fconcepts -lstdc++fs -DNDEBUG -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld CMakeFiles/global_affine_unbanded_test.dir/global_affine_unbanded_test.cpp.o -o global_affine_unbanded_test  -pthread /usr/lib64/libz.so /usr/lib64/libbz2.so -lrt -lpthread -lgtest_main -lgtest 
make[2]: Leaving directory '/builddir/build/BUILD/seqan3/build'
/usr/bin/ld: CMakeFiles/global_affine_unbanded_test.dir/global_affine_unbanded_test.cpp.o: in function `seqan3::detail::alignment_matrix_column_major_range_base<seqan3::detail::alignment_trace_matrix_full<seqan3::detail::trace_directions, false> >::alignment_column_type::alignment_column_type()':
/builddir/build/BUILD/seqan3/include/seqan3/alignment/matrix/detail/alignment_matrix_column_major_range_base.hpp:226: undefined reference to `ranges::zip_view<std::span<seqan3::detail::trace_directions, 18446744073709551615ul>, std::span<seqan3::detail::trace_directions, 18446744073709551615ul>, std::ranges::iota_view<seqan3::detail::advanceable_alignment_coordinate<(seqan3::detail::advanceable_alignment_coordinate_state)2>, seqan3::detail::advanceable_alignment_coordinate<(seqan3::detail::advanceable_alignment_coordinate_state)2> > >::zip_view()'
/usr/bin/ld: CMakeFiles/global_affine_unbanded_test.dir/global_affine_unbanded_test.cpp.o: in function `seqan3::detail::alignment_matrix_column_major_range_base<seqan3::detail::alignment_score_matrix_one_column<int> >::alignment_column_type::alignment_column_type()':
/builddir/build/BUILD/seqan3/include/seqan3/alignment/matrix/detail/alignment_matrix_column_major_range_base.hpp:226: undefined reference to `std::span<std::tuple<int, int>, 18446744073709551615ul>::span()'
collect2: error: ld returned 1 exit status
```

### Info

Build log: https://kojipkgs.fedoraproject.org//work/tasks/4369/57264369/build.log
Software used: https://kojipkgs.fedoraproject.org//work/tasks/4369/57264369/root.log

**Comment by eseiler** [comment]
Hello @sagitter,

we currently do not support gcc-11, but we are working on it:

https://github.com/seqan/product_backlog/issues/255
https://github.com/seqan/product_backlog/issues/106

IIRC there are also some undefined references to other symbols (e.g. `std::deque`).

**Comment by marehr** [comment]
I'm not completely sure if this is an error on our side. Can you double-check, if your gcc-11 version uses the stdlib bundled with it and not a different one installed in the system?

**Comment by sagitter** [comment]
> I'm not completely sure if this is an error on our side. Can you double-check, if your gcc-11 version uses the stdlib bundled with it and not a different one installed in the system?

It should be bundled.

**Comment by sagitter** [comment]
This error could be related to a GCC-11 bug: [98231](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98231)

**Comment by sagitter** [comment]
> This error could be related to a GCC-11 bug: [98231](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98231)

This GCC bug should be [fixed](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98231#c2) now.

**Comment by marehr** [comment]
@sagitter Does this mean we can close this issue? The original problem was that std::span is undefined.

**Comment by sagitter** [comment]
> @sagitter Does this mean we can close this issue? The original problem was that std::span is undefined.

I don't know, SeqAn looks failing for different causes now (see #2368)

**Comment by marehr** [comment]
Okay! We leave the ticket open and it is part of our gcc-11 release.

**Comment by marehr** [comment]
We made a push to support gcc-11 and https://github.com/seqan/seqan3/pull/2551  and https://github.com/seqan/seqan3/pull/2550 will be the last PRs to support gcc-11 (at least the gcc-build of today), see https://github.com/seqan/product_backlog/issues/106 for overall progress.

I'll close for now, please report any errors that come up :)
