### ISSUE TITLE
Add wchar_t to char_adaptation

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#231]
Currently our char_adaptation does not work with the type `wchar_t`, which is a distinct type.

**Comment by rrahn** [comment]
@mitra
`wchar_t` must be guaranteed to be at least 32 bit large on unix systems and 16 bit on windows systems.
This means, that the underlying integer type is supposed to be `uint_least32_t ` for unix. 
Please add a TODO, that once Windows-support is enabled, we need to add a condition to use `uint_least16_t` instead.
See here for a reference for the underlying integer type 
https://github.com/seqan/seqan3/blob/512bfd82d4f2e5dfb01b4a3bc59bd7476e772d60/include/seqan3/alphabet/adaptation/char.hpp#L74-L76

**Comment by h-2** [comment]
implemented via #298
