### ISSUE TITLE
charconv code broken in GCC10

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#2352]
## Platform

  - SeqAn version: master from December
  - Operating system: RHEL 7.8
  - Compiler: GCC 10.2.0

### How to repeat the problem

```c++
#include <seqan3/std/charconv>
#include <charconv>

int main(int argc, char ** argv)
{}
```

Build the above code directly with GCC.
I don't know if this depends on whether CMake is used or not.
I had a look at the code, but everything has been moved around since I last saw it, so I couldn't immediately spot what the problem is 😺 

Thanks for your help!

### Expected behaviour

No error.

### Actual behaviour

Error.

edit: shorter example

**Comment by h-2** [comment]
![image](https://user-images.githubusercontent.com/2996863/105730047-d1031180-5f25-11eb-89d2-214d7f0f7b63.png)

Here's the error message.

**Comment by h-2** [comment]
The code used to be in anonymous sub-namespaces of `std` to give preference to actual things in `std` (as a fallback if a compiler doesn't set the correct feature macro). Is this workaround not working or was this approach given up when moving things around?

**Comment by eseiler** [comment]
https://github.com/gcc-mirror/gcc/blob/10c83fb7131779ee27fbaa9091065ca6cfedc0c5/libstdc%2B%2B-v3/include/std/charconv#L48

macro is not defined, so we need a workaround for  https://github.com/seqan/seqan3/blob/896ac7d9f1b529e1786f31b052e20eac74c2e946/include/seqan3/std/charconv#L22

**Comment by eseiler** [comment]
> The code used to be in anonymous sub-namespaces of `std` to give preference to actual things in `std` (as a fallback if a compiler doesn't set the correct feature macro). Is this workaround not working or was this approach given up when moving things around?

It is, and it should work, but only if the order is
```cpp
#include <charconv>
#include <seqan3/std/charconv>
```

**Comment by h-2** [comment]
> It is, and it should work, but only if the order is

That fixes it for me, but I still think it is weird, because:
https://godbolt.org/z/3shqod

As a workaround, I would recommend adding the following to the top of `<seqan3/std/charconv>`
```c++
#if __has_include(<charconv>)
#include <charconv>
#endif
```
I think we used to have this for all our std-headers. In any case, it doesn't hurt to have it.

**Comment by eseiler** [comment]
```patch
diff --git a/include/seqan3/std/charconv b/include/seqan3/std/charconv
index c912a751..d6bc341e 100644
--- a/include/seqan3/std/charconv
+++ b/include/seqan3/std/charconv
@@ -19,9 +19,11 @@
 
 #include <utility> // __cpp_lib_to_chars may be defined here as currently documented
 
-#if __cpp_lib_to_chars >= 201611
+#if __has_include(<charconv>)
 #include <charconv>
-#else // else include our own implementation below
+#endif // __has_include(<charconv>)
+
+#if !defined(__cpp_lib_to_chars)
 
 #include <seqan3/std/concepts>
 #include <sstream>
```

Should probably be good for now

**Comment by marehr** [comment]
> ```diff
> diff --git a/include/seqan3/std/charconv b/include/seqan3/std/charconv
> index c912a751..d6bc341e 100644
> --- a/include/seqan3/std/charconv
> +++ b/include/seqan3/std/charconv
> @@ -19,9 +19,11 @@
>  
>  #include <utility> // __cpp_lib_to_chars may be defined here as currently documented
>  
> -#if __cpp_lib_to_chars >= 201611
> +#if __has_include(<charconv>)
>  #include <charconv>
> -#else // else include our own implementation below
> +#endif // __has_include(<charconv>)
> +
> +#if !defined(__cpp_lib_to_chars)
>  
>  #include <seqan3/std/concepts>
>  #include <sstream>
> ```
> 
> Should probably be good for now

This will probably work, but it is still not complete.

I think it is generally better to have a dedicated `SEQAN3_CPP_LIB_TO_CHARS` macro that tells you whether some parts were implemented by the std-library or not.

----

Whatever we do: I think we need a header test that does 

```c++
#if __has_include(<stdheader>)
#include <stdheader>
#endif // __has_include(<stdheader>)

#include <seqan3/std/stdheader>
```

to ensure that a direct include will always work.

**Comment by h-2** [comment]
> Whatever we do: I think we need a header test that does 
> [...]
> to ensure that a direct include will always work.

The other way around was the actually problematic case here. But, yes, definitely good to have!

**Comment by h-2** [comment]
Hm, if I do the proposed fix, `from_chars()` on int works (takes GCC's version), but passing a double doesn't work -> can't find SeqAn's version.

**Comment by h-2** [comment]
The only "workaround" I found was never to include the standard library header. 

Have you considered maybe dropping the following into contrib (instead of libc++'s code):
https://github.com/fastfloat/fast_float
And using that? It has a proper implementation of the floating behaviour. Unlike GCC which is adding slow, non-conforming code with GCC11:
https://gcc.gnu.org/pipermail/gcc-patches/2020-July/550331.html
(Essentially the hack we had as well, but wose, because they will be setting the feature macro which implies that the function is non-allocating and fast)

fast_float is really nice. However, the code is Apache licensed which is difficult for SeqAn3 (makes code incompatible with GPLv2 which we don't want). But maybe they could be asked to relicense or dual-license.

**Comment by marehr** [comment]
Thank you for the suggestions, we'll have a look at it.

> And using that? [1]  [1] not doing any std namespace stuff. Just using it from `fast_float::` or `seqan3::contrib::`.

Yeah, the main problem is that we can't easily drop in the float implementation into a partial defined std-library implementation.

Since our `std/` module has the purpose of emulating standard "behaviour" and "syntax", I would say it suffices for now that charconv has the correct behaviour and might not be fully optimised. This should be fine, since Microsoft already offers that dragon algorithm and hopefully other std-lib implementations will do so as well. There was this awesome talk https://www.youtube.com/watch?v=4P_kbF0EbZM that discussed the endeavour of implementing that.

In the long-run I would hope that the standard libraries implement the float overloads properly, but we might use that implementation in the meantime. I'm not sure where **we** actually use float-parsing, so it might be also not worthwhile to package that.

**Comment by eseiler** [comment]
### Core meeting 27-1-2021

Resolution: 
* We will change the way we detect `charconv` support
* Since we currently only support GCC, we will add a check for the STL version and include the float overloads if the STL version does not have float overloads
