### ISSUE TITLE
Extensions with dot don't work in argument parser

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#2353]
## Platform

  - SeqAn version: master from around December
  - Operating system: RHEL 7
  - Compiler: gcc10.2

### How to repeat the problem

```cpp
parser.add_positional_option(p1, "FOO", seqan3::input_file_validator{{"foo.bar"}});
```

This code is accepted and nothing in the documentation suggests that this doesn't work. But when I pass a file called  `X.foo.bar` to the program, the argument parser throws and says 

```
... the following valid extensions: [foo.bar]. Got ".bar" instead!"
```

I know that we have special treatment for files now (which is nice but might be better served by a different validator), but having an extension with a dot is quite common, even independent of compression.

### Expected behaviour

This should work.

### Actual behaviour

It doesn't.

### Possible fix

This should be quite simple. Just check if the path ends_with the respective string instead of calling `.extension()`.

**Comment by marehr** [comment]
How is this related to https://github.com/seqan/seqan3/issues/1176?

**Comment by eseiler** [comment]
This would work:

```patch
diff --git a/include/seqan3/argument_parser/validators.hpp b/include/seqan3/argument_parser/validators.hpp
index b177467d..59192522 100644
--- a/include/seqan3/argument_parser/validators.hpp
+++ b/include/seqan3/argument_parser/validators.hpp
@@ -374,7 +374,8 @@ protected:
                                                      " one of the following valid extensions:", extensions, "!")};
 
         // Drop the dot.
-        std::string drop_less_ext = path.extension().string().substr(1);
+        std::string const filename = path.filename().string();
+        std::string drop_less_ext = filename.substr(filename.find(".") + 1);
 
         // Compares the extensions in lower case.
         auto case_insensitive_equal_to = [&] (std::string const & ext)

```

Question: 
* `foo.bar.bax.baz` would then also only validate if `bar.bax.bax` is given as valid extension, etc.

----

> How is this related to #1176?

Similar, we may allow for compression. Passing `fastq` as valid extension should allow `fastq.gz`, `fastq.bz2`, etc. without the user explicitly specifying the compression extensions.
Svenja worked on it, but then we decided to do it differently...

**Comment by marehr** [comment]
### 2021-02-01 Core-Meeting

We match the suffix. We need an implementation for c++17 for `seqan3::detail::string_ends_with` which behaves like C++20 `std::string::ends_with`.
