### ISSUE TITLE
String to seqan3::dna4_vector

### ISSUE THREAD

**Issue by chegrane** [seqan/seqan3#2383]
## Platform

  - SeqAn version: SeqAn3 3.0.0
  - Operating system: ubuntu 16.04
  - Compiler: gcc/g++ 7

## Question

I want to convert a simple string to "seqan3::dna4_vector"
instead of doing : seqan3::dna4_vector s1 = "ACGTGAACTGACT"_dna4;
I want : 
**string str = "ACGTGAACTGACT";** // this can be also char*,  my goal is to get the string from argv[] like str = argv[1];....
**seqan3::dna4_vector s1 = some_function_to_convert_to_dna(str);**
do something with s1...

Thank you for your help.

**Comment by marehr** [comment]
Hi @chegrane,

thank you for writing us. Can you help us improve our documentation? Where did you expect to find this information?

We have a similar use case here: https://docs.seqan.de/seqan/3-master-user/cookbook.html#autotoc_md46

This would be a view onto the std::string where the actual sequence will be stored within the std::string and the view will convert the data on-the-fly. We would generally advise not to copy data if you don't need to.

If you explicitly want to copy the data into a  `seqan3::dna4_vector` you need to do one more thing:

Since `seqan3::dna4_vector ` is of type `std::vector<seqan3::dna4>` you can't directly "convert" them, but you can do

```c++
#include <string_view>

#include <seqan3/alphabet/nucleotide/dna4.hpp> // for seqan3::dna4
#include <seqan3/range/views/char_to.hpp> // for seqan3::views::char_to
#include <seqan3/range/views/to.hpp> // for seqan3::views::to

int main(int argc, char** argv)
{
    // the original sequence as string view (no-copy)
    std::string_view sequence_raw{argv[1]};
    seqan3::dna4_vector dna4_sequence =
        sequence_raw |
        // convert char-by-char from char to seqan3::dna4 (lazily per view)
        seqan3::views::char_to<seqan3::dna4> |
        // copy the data from the view into a temporary seqan3::dna4_vector
        seqan3::views::to<seqan3::dna4_vector>;
}
```

// TODO this is just out of my head and untested, I will update the answer to complete the example if something does not compile

**Comment by chegrane** [comment]
Hi @marehr 

Thank you very much for your fast response.  I will tray the code you provide.

For : **Where did you expect to find this information?**
Since I am beginner with SeqAn, I started to read the first steps, and then a searched in SeqAn IO, and then I searched in the Alphabets, and after that I try Parsing command line arguments ... And of course I searched using google also.

All the documentation I found use the hard coded ("ACGT..."_dna4), it was so bizarre, because to me, string (char*) is the basic thing to manipulate in this case, before converting it to seqan3::dna4_vector.

since yesterday I have struggled with that to find a solution, but nothing. So I was about to create a fasta file with Biopythong, so that I could import it with SeqAn IO. But this is only a work around, because my data are in CSV file.

Thank you very much.

**Comment by chegrane** [comment]
hi @marehr 

your code work fine

so in my case I use : 

```
std::vector<seqan3::dna4> convert_str_to_dna4Sequence(char* inStr)
 {
	// the original sequence as string view (no-copy)
    std::string_view sequence_raw{inStr};
    
	seqan3::dna4_vector dna4_sequence =
        sequence_raw |
        // convert char-by-char from char to seqan3::dna4 (lazily per view, no-copy)
        seqan3::views::char_to<seqan3::dna4> |
        // copy the data from the view into a temporary seqan3::dna4_vector
        seqan3::views::to<seqan3::dna4_vector>;
		
	return dna4_sequence;
 }
```

Thank you again 👍

**Comment by marehr** [comment]
> For : **Where did you expect to find this information?**
> Since I am beginner with SeqAn, I started to read the first steps, and then a searched in SeqAn IO, and then I searched in the Alphabets, and after that I try Parsing command line arguments ... And of course I searched using google also.

Thank you!

Out-of interest, will you make your code public? It would be interesting to see how you use our API, s.t. we can optimize it for different use cases.

I guess we should add a section to our documentation how you would deal with standard types like std::string or char *, so please leave the issue open.

**Comment by chegrane** [comment]
Hi @marehr 

> Out-of interest, will you make your code public?

Yes, with pleasure. Given two standard strings (an std::string  and/or char* ) do some task with SeqAn3.  It could be from the standard input, or in loop (from CSV file for example)... so on. For me I compute the score of global pairwise alignment after receiving strings form command line. My code is below:

```
#include <utility>
  
 #include <seqan3/alignment/pairwise/align_pairwise.hpp>
 #include <seqan3/alignment/scoring/nucleotide_scoring_scheme.hpp>
 #include <seqan3/alphabet/nucleotide/dna4.hpp>
 #include <seqan3/core/debug_stream.hpp>

 #include <string_view>
 #include <seqan3/range/views/char_to.hpp> // for seqan3::views::char_to
 #include <seqan3/range/views/to.hpp> // for seqan3::views::to
  
 using seqan3::operator""_dna4;
  
 std::vector<seqan3::dna4> convert_str_to_dna4Sequence(char* inStr)
 {
	// the original sequence as string view (no-copy)
    std::string_view sequence_raw{inStr};
    
	seqan3::dna4_vector dna4_sequence =
        sequence_raw |
        // convert char-by-char from char to seqan3::dna4 (lazily per view, no-copy)
        seqan3::views::char_to<seqan3::dna4> |
        // copy the data from the view into a temporary seqan3::dna4_vector
        seqan3::views::to<seqan3::dna4_vector>;
		
	return dna4_sequence;
 }
  
 int main(int argc, char *argv[])
 {
     //seqan3::dna4_vector s1 = "ACGTGAACTGACT"_dna4;
     seqan3::dna4_vector s1 = convert_str_to_dna4Sequence(argv[1]);  
	  
     //seqan3::dna4_vector s2 = "ACGAAGACCGAT"_dna4;
     seqan3::dna4_vector s2 = convert_str_to_dna4Sequence(argv[2]);
  
     // Configure the alignment kernel.
     auto config = seqan3::align_cfg::method_global{} |
                   seqan3::align_cfg::scoring_scheme{seqan3::nucleotide_scoring_scheme{}}|
				   seqan3::align_cfg::output_score{};
  
     // Invoke the pairwise alignment which returns a lazy range over alignment results.
     auto results = seqan3::align_pairwise(std::tie(s1, s2), config);
     auto & res = *results.begin();
     seqan3::debug_stream << "Score: " << res.score() << '\n';
 }

```

> I guess we should add a section to our documentation how you would deal with standard types like std::string or char *, so please leave the issue open.

Yes absolutely, and this is just after the `seqan3::debug_stream << "Hello world\n";` tutorial. 

Thank you very much.

**Comment by h-2** [comment]
I would still like to underline what @marehr said originally:

The idiomatic way of using SeqAn3 is to not create a new container and just use the view:

```cpp
std::string s = "ACAGAGAATATAT";
auto v = s | seqan3::views::char_to<seqan3::dna4>; //<- just use this for the alignment, DO NOT COPY!
```

In case you input is `char const *`, it would look like this:

```cpp
char const * s = "ACAGAGAATATAT";
auto v = std::string_view{s} | seqan3::views::char_to<seqan3::dna4>; //<- just use this for the alignment, DO NOT COPY!
```

So for your example:

```cpp

#include <utility>
  
 #include <seqan3/alignment/pairwise/align_pairwise.hpp>
 #include <seqan3/alignment/scoring/nucleotide_scoring_scheme.hpp>
 #include <seqan3/alphabet/nucleotide/dna4.hpp>
 #include <seqan3/core/debug_stream.hpp>

 #include <string_view>
 #include <seqan3/range/views/char_to.hpp> // for seqan3::views::char_to
 #include <seqan3/range/views/to.hpp> // for seqan3::views::to
  
 using seqan3::operator""_dna4;
  
 int main(int argc, char *argv[])
 {
     //seqan3::dna4_vector s1 = "ACGTGAACTGACT"_dna4;
    auto v1 = std::string_view{argv[1]} | seqan3::views::char_to<seqan3::dna4>; 
	  
     //seqan3::dna4_vector s2 = "ACGAAGACCGAT"_dna4;
    auto v2 = std::string_view{argv[2]} | seqan3::views::char_to<seqan3::dna4>; 
  
     // Configure the alignment kernel.
     auto config = seqan3::align_cfg::method_global{} |
                   seqan3::align_cfg::scoring_scheme{seqan3::nucleotide_scoring_scheme{}}|
				   seqan3::align_cfg::output_score{};
  
     // Invoke the pairwise alignment which returns a lazy range over alignment results.
     auto results = seqan3::align_pairwise(std::tie(v1, v2), config);
     auto & res = *results.begin();
     seqan3::debug_stream << "Score: " << res.score() << '\n';
 }
```

**Comment by marehr** [comment]
Hi @chegrane, we close this issue, because we think that we resolved the question. If you have any further questions or remarks, please re-open the issue.

**Comment by chegrane** [comment]
Thank you very much @marehr and @h-2 💯
