### ISSUE TITLE
[MISC] Argument Parser - Help page improvement

### ISSUE THREAD

**Issue by Irallia** [seqan/seqan3#2396]
In https://github.com/seqan/iGenVar/pull/72 we have come across some bugs and improvements to the help page.

- double "to"
- version-check boolean: Instead of 1 a true would be more user-friendly.
- integer's -> integers

**Comment by eseiler** [comment]
https://github.com/seqan/seqan3/blob/5038e73ba9d7aee87272f3c4364c2e1714e86a79/include/seqan3/argument_parser/detail/format_base.hpp#L116-L119

I would get rid of the `'s`:
```cpp
return ("(\\fIList\\fP of \\fI" + get_type_name_as_string(container) + "\\fP)");
```

A `list of std::string`, `list of unsigned 8 bit integer` sounds fine.
 I think the original intention was to separate the type from the `s`, e.g. `std::strings` vs. `std::string's`.

**Comment by eseiler** [comment]
https://github.com/seqan/seqan3/blob/5038e73ba9d7aee87272f3c4364c2e1714e86a79/include/seqan3/argument_parser/argument_parser.hpp#L768-L784

version_check is currently only supporting `1` and `0`

https://github.com/seqan/seqan3/wiki/Update-Notifications would then need an update
