### ISSUE TITLE
[BUG] Extracting the alignment from a BAM file referenes ID index not in range.

### ISSUE THREAD

**Issue by joshuak94** [seqan/seqan3#2417]
## Platform

  - SeqAn version: 
  - Operating system: Linux
  - Compiler: g++ 7.5

## Description
When I extract the alignment field of records in an alignment file, at some point it throws the following message:
```terminate called after throwing an instance of 'seqan3::format_error'
  what():  Reference id index '287314191' is not in range of header.ref_ids(), which has size 34.
```

### How to repeat the problem

Code snippet:
```cpp
#include <seqan3/io/alignment_file/input.hpp>   // SAM/BAM support
#include <seqan3/core/debug_stream.hpp>
#include <filesystem>

int main()
{
    std::filesystem::path alignment_path = "test.bam";

    using my_fields = seqan3::fields<seqan3::field::id,
                                     seqan3::field::alignment>;

    seqan3::alignment_file_input alignment_file{alignment_path, my_fields{}};

    for (auto & [ id, alignment ] : alignment_file)
    {
        seqan3::debug_stream << ": " << id << ": " << std::get<1>(alignment) << '\n';
    }

}
```

Test file attached. It's a part of a larger BAM file, the error occurs at the last line of this part.

[test.bam.gz](https://github.com/seqan/seqan3/files/6049807/test.bam.gz)

I wonder if it has to do with the record trying to extract an alignment in an unmapped sequence?

**Comment by eseiler** [comment]
This is some bug with the binary parsing. I'm looking at it.

As a workaround you can also parse `seqan3::field::seq` and then the errors should not happen.

**Comment by eseiler** [comment]
I found the bug, maybe you already want to try it locally https://github.com/seqan/seqan3/pull/2418
