### ISSUE TITLE
Alphabets must support strict assignment from char

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#242]
Only the alphabet itself can know if the char, it is assigned from, is valid for the alphabet.
For example, if checking whether an input character is part of the DNA alphabet, then the alphabet must  be convertible to DNA but will lose the information of upper and lower case. To make sure, that specific alphabets, that for example only allow small letters, are checked correctly, the alphabet must make sure, that the assigned char fits the specified implementation.

Possible names could be `assign_char_strict`, that returns an optional to represent assignability.

**Comment by h-2** [comment]
It is valid.

**Comment by rrahn** [comment]
Fixed by #678
