### ISSUE TITLE
Consider changing the style of the head-lines

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#244]
Currently we use "Sentence case" for head-lines, i.e. We just capitalise the first letter and proper nouns. I am weakly in favour of this, as it goes well with using snake_case for code.

But @rrahn disagrees and we could also change it to another style. Here is an overview:
https://headlinecapitalization.com/

Have a look at e.g. http://docs.seqan.de/seqan/3.0.0-master-dev/structseqan3_1_1dna5.html
And think about the implications, all sections like "Read functions" would turn into "Read Functions" and "Generic serialisation functions for all seqan3::semi_alphabet_concept" would be "Generic Serialisation Functions for All seqan3::semi_alphabet_concept".

**Comment by smehringer** [comment]
We will stick to `Sentence case`
