### ISSUE TITLE
tokenisation – discussion

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#248]
We currently have:

* #238 by @rrahn that has a `transfer_data` function, as well as some `read_`* function and also wants to add `write_`* and `put`....
* #247 by me which reduces most cases to `copy` with certain conditions (no read VS write and a lot fewer interfaces)

BUT I think these designs are all sub-optimal, they all replicate existing range and view behaviour and we should just use views to achieve the behaviour. This is an example of how that would look for reading fasta files:

```cpp
auto inv = urange | view::single_pass_input;

// read id
std::copy(inv | view::take_while(!(is_char<'\n'>{} || is_char<'\r'>{})),
          make_output_iterator(id));

// read sequence
std::copy(inv | view::remove_if(is_space{} || is_num{})  // ignore whitespace and numbers
              | view::take_while(!is_char<'>'>{}) // until next header (or end)
              | view::transform([] (char const c)
                {
                    if (!is_in_alphabet<legal_alphabet>{}(c))
                        throw parse_error{is_in_alphabet<legal_alphabet>::msg.string()};
                    return c;
                }) // enforce legal alphabet
              | view::char_to<sequence_alphabet>, // convert to actual target alphabet
          make_output_iterator(sequence));
```

I would argue that this is far superior and more flexible. It re-uses existing data structures and we don't even need the output_conversion_iterators anymore, because conversion happens in the pipe. 
In case we want stricter behaviour where we e.g. read until a condition is met and we don't want to accept end-of-input, we can just make an extra view that has this behaviour.

**Comment by h-2** [comment]
I have created a PR following this design: #250

**Comment by marehr** [comment]
Can this be closed?

**Comment by rrahn** [comment]
Yes can be closed.
