### ISSUE TITLE
Change private inheritance of binning_bitvector

### ISSUE THREAD

**Issue by tloka** [seqan/seqan3#2489]
Hey all,

I am trying to use the interleaved bloom filter in a somewhat different way than what you had in mind with respect to the DREAM index.  
To make my computations most efficient, I would need to use original sdsl::int_vector operations on the resulting `binning_bitvector` of the `membership_agent` which I can't, as the inheritance of the `sdsl::bit_vector` is private.  
Is there any special reason that the access to the original `sdsl::bit_vector` is that limited (probably, to prevent corruption)? In my special case, I would need to perform bitwise operations on the underlying bit vector. With the private inheritance, this is not possible as I can't access `sdsl::int_vector::data()`. Is there any possibility, you allow access to more underlying `sdsl::bit_vector` member functions, or to even use public inheritance to grant full access?

**Comment by eseiler** [comment]
I'll have a look at it, but I don't see any reason to not at the very least at a `raw_data()` member that returns a reference to the underlying data structure.
