### ISSUE TITLE
Bloom Filter

### ISSUE THREAD

**Issue by tloka** [seqan/seqan3#2490]
Are there any plans to add a simple bloom filter in addition to the interleaved one? This would be very useful for many applications, and simply using the interleaved bloom filter with a single bin doesn't work (efficiently) as it would be extended to 64 technical bins.

**Comment by eseiler** [comment]
We don't have any plans because it's not useful for the IBF - so from our current POV it's more an app feature than a library feature.

What would be your use case?

**Comment by tloka** [comment]
> 
> 
> [...] from our current POV it's more an app feature than a library feature.

I disagree. A bloom filter is a very useful data structure for different use cases - though fully unrelated to the IBF. 
When writing different apps using a bloom filter, I don't want to handle all the hashing stuff again for each single app. For me, it's pretty much the same as providing a k-mer index, but a bloom filter would allow the efficient use of larger k-mer sizes.

>
>
> What would be your use case?

In my current application, I want to use a bloom filter for k-mer based filtering of human reads. A k-mer index would not be suitable due to the memory consumption for a sufficiently high k-mer size.  
The IBF is also not perfectly suitable, as it creates 64 technical bins (I am currently testing a workaround for which I need the feature requested in #2489 ). I could directly use the sdsl bitvector, but would need to handle all the hashing on my own (or copy all the things implemented for the IBF). Thus, I currently don't see a good way to implement this with the existing data structures you provide.  
  
However, I am open for alternative solutions!

**Comment by eseiler** [comment]
I see; the general idea would be to implement it in the app and then port it to the library if it proofs useful and general enough., which would be the workflow I'd propose (and I can help to implement a BF in your app).
Another advantage is that doing it in the app is usually less work to get a working version.

---

So in your application you get a read, compute k-mers and then just have a binary decision to make, hence one bin in the IBF abstraction. Sounds indeed like a BF application :)

**Comment by tloka** [comment]
I am currently implementing a small prototype for this. Just one quick question:  
Is it correct that I just need to drop the line `h *= technical_bins;` from the `hash_and_fit(...)` function to make the hashing work with a simple (unbinned) underlying bit vector?
```c++
inline constexpr size_t hash_and_fit(size_t h, size_t const seed) const
    {
        h *= seed;
        assert(hash_shift < 64);
        h ^= h >> hash_shift; // XOR and shift higher bits into lower bits
        h *= 11400714819323198485ULL; // = 2^64 / golden_ration, to expand h to 64 bit range
        // Use fastrange (integer modulo without division) if possible.
#ifdef __SIZEOF_INT128__
        h = static_cast<uint64_t>((static_cast<__uint128_t>(h) * static_cast<__uint128_t>(bin_size_)) >> 64);
#else
        h %= bin_size_;
#endif
        h *= technical_bins;   // <<< REMOVING THIS LINE IS THE ONLY ADAPTION I NEED TO MAKE?
        return h;
    }
```

**Comment by eseiler** [comment]
Yes, the idea is to map the hashed value `h` to the range we have available for an individual bin `bin_size_`. This gives us the position in an individual bin; but since we interleave them, we do `*= technical_bins`.

Alternatively you could probably allow the technical_bins to not be a multiple of the word_size...

**Comment by tloka** [comment]
Thanks, I wasn't 100% sure about whether the golden ratio is required.  
  
Looks like I have a prototype running, I'll let you know if I run into any problems or once I have everything finished, tested and cleaned up.

**Comment by tloka** [comment]
@eseiler 
I integrated my Bloom Filter implementation including unit tests and snippets in my SeqAn3 fork.
If you want you can have a look and discuss, whether you want to have this merged to SeqAn3 or not.  
https://github.com/tloka/seqan3/commit/5f10c5e6648f96c0a39dcba15516e6e47e385d75

If you want this, I am happy to contribute necessary changes to the code.  
  
PS: No performance tests included in the current state.

**Comment by eseiler** [comment]
Thank you, you can open a PR if you want to :)
