### ISSUE TITLE
Documentation online is out of date

### ISSUE THREAD

**Issue by rlorigro** [seqan/seqan3#2503]
The docs about indexing have headers that don't appear to exist in the latest seqan3

http://docs.seqan.de/seqan/3.0.1/tutorial_index_search.html

```
#include <seqan3/search/algorithm/search.hpp> // this already includes (bi)_fm_index
```

Where the existing header appears to be:
```
#include "seqan3/search/all.hpp"
```

EDITED: the compilation error for `search` was my own fault, so I removed it

**Comment by marehr** [comment]
Hi @rlorigro,

you seem to use an out-dated documentation (3.0.1), please use either [3.0.2](https://docs.seqan.de/seqan/3.0.2/) or [master](https://docs.seqan.de/seqan/3-master-user/) depending on which version you use. You should be able to select the version in the bottom-left corner.

![grafik](https://user-images.githubusercontent.com/103778/113474604-26e9bd80-9471-11eb-9281-93aadc14db52.png)

**Comment by rlorigro** [comment]
:) thanks, and sorry about the false alarm
