### ISSUE TITLE
Correctness / strictness of format reading

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#251]
I think we agree that we should be able to parse all legal (by specification) variations of the important formats, but we need to discuss whether we also want to fail on deviations from the spec.

I would argue against it, because it incurs a potentially huge penalty on parsing performance and is a lot harder to maintain. It does mean, however, that if you want to lint files, you need to write your own parser.

Here is an example fasta file:

```
> ID_STRING
12 ACGT ACGT ACGAT
24 ACGT ACGT ACGAT
33 ACGT ACGT A
```

As per #250 this will be parsed by stripping the numbers and spaces and line-endings which is the correct behaviour. But this means we also accept the following:

```
> ID_STRING
94 ACGTACGTACGATACGT
ACGT ACGAT
ACGT 7 ACGT A
```
deviations of the spec: 
  * wrong number in first line
  * no number in second line
  * all lines except the last should have same length, but don't
  * third line contains number somewhere in the middle

But I would argue, that these error non-semantic, they don't influence the sequence or the ID read.

And, as you can see, tokenising this bit-by-bit, enforcing same width of sequence columns, correct line width, correct character number would be a lot more expensive to do – and it would provide no benefit to 99% of our users who just want to read the file (and might even be happy about error tolerance)!

Note, that we do throw for semantic errors, like wrong characters.

**Comment by rrahn** [comment]
I think we keep as close as possible to the specification of the respective format. And agree, that if someone deviates from it the person can add it's own parser.
