### ISSUE TITLE
Linking libdivsufsort temporarily (for SDSL)

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan3#253]
Anyone familiar with the cmake in SeqAn3? @marehr :grin:

**Comment by cpockrandt** [comment]
@marehr I think you are one of the developers most familiar with the build system in SeqAn3. This issue would be a lot less work for everyone if you could add the linking of libdivsufsort and libdivsufsort64 instead of me figuring it out and you having to review it multiple times. :smile:

If you're not responsible for the build system (anymore), please let me know who is.

**Comment by marehr** [comment]
This to?

relates to #184
