### ISSUE TITLE
Alphabet TODOs

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#257]
* [x] think about assertions and exceptions
  * [x] expose legal alphabet
  * [x] have strict/safe assignment functions that always assert/throw?
  * [x] implement `<=>` via CRTP mixin, possibly make generic CRTP facade.
  * [x] require that assign_rank and regular assign_char are noexcept

**Comment by rrahn** [comment]
@h-2 what's the state?

**Comment by h-2** [comment]
First point still open.
