### ISSUE TITLE
seqan3::test::tmp_file_name naming inconsitency

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#263]
The actual class is called `seqan3::test::tmp_file_name`, but
* the include file is called `/test/include/seqan3/test/tmp_filename.hpp`
* the test file is called  `/test/unit/test/tmp_filename_test.cpp`
* in `tmp_filename_test.cpp` the test cases are named `tmp_filename`

This feature was introduced in #120 and test cases added in #140.

We should make this consistent.

@seqan/all  do you prefer `tmp_filename` or `tmp_file_name`?

Please vote for :tada: (= `tmp_filename`) or  :heart: (=`tmp_file_name`)

**Comment by joergi-w** [comment]
The [Dictionary](http://www.dictionary.com/browse/filename) clearly states that _filename_ for the identifying name of a computer file is written as one word. Thus, we should use `tmp_filename`, unless someone can provide good counter-arguments.

**Comment by holtgrewe** [comment]
FWIW

https://stackoverflow.com/q/742115/84349
