### ISSUE TITLE
revert `sequence_concept` workaround for travis-ci / ubuntu 14.04/16.04

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#264]
I introduced `sequence_concept_modified_by_const_iterator_bug` to workaround an issue that was only present in the [gcc-7.2.0 ppa](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=trusty).

The rational was that ubuntu/debain users that are still on trusty (14.04) or xenial (16.04) have no easy way of installing gcc-7 without this ppa.

On 2018/04/24 the gcc version was updated to 7.3 and [travis](https://travis-ci.org/seqan/seqan3/jobs/385692703) already uses this version, so we should revisit this issue and remove the workaround.

See commit 5ba75261f785259adf8b49e0cf41ce818f481e8a and pr #113.

----
split from  #255

**Comment by marehr** [comment]
As you can see in #265, the build is still failing for 7.3 (and 8.0, which I checked locally).

I figured out, that the version of `g++-7` on travis sets `--disable-libstdcxx-dual-abi` and `--with-default-libstdcxx-abi=gcc4-compatible`.

After some digging into [configure](https://gcc.gnu.org/onlinedocs/libstdc++/manual/configure.html)and [using_dual_abi](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html), I figured out that the ubuntu ports still uses the pre-c++11 `std::string` implementation. The reason is simple, the ABI of gcc4.8 (default on ubuntu 14.04) uses the old-implementation. To ensure no linking errors it makes sense to produce compatible binaries.

Unfortunately, `--disable-libstdcxx-dual-abi` disallows us to use the new ABI. Otherwise, we could set `-D_GLIBCXX_USE_CXX11_ABI=1`.

See also this [blog](https://davmac.wordpress.com/2015/07/19/tale-of-two-abis/).

**Comment by h-2** [comment]
What a mess.

> Otherwise, we could set -D_GLIBCXX_USE_CXX11_ABI=1.

Setting this on Travis fixes the problems? Then I am absolutely in favour of doing that.

**Comment by marehr** [comment]
Unfortunately not. The ppa stdlibc++ was not build with dual abi, hence we can't override this.

**Comment by marehr** [comment]
I wrote an email to the package maintainer, but I think he will (again) not answer.

**Comment by h-2** [comment]
🤦‍♂️

**Comment by h-2** [comment]
I don't think we should aim at supporting Ubuntu 14.04 in general. If we are stuck on travis with 14.04, maybe we just need to ship our own compilers to travis. It's not ideal, but the amount of time we already spent dealing with broken GCC on travis is even worse.

We had talked with the staff at FUB about providing regular compiler snapshots to us, I suppose we could just expose that directory to our travis instances.

**Comment by rrahn** [comment]
We upgraded on tavis didn't we? Is this still a problem?

**Comment by rrahn** [comment]
@marehr maybe we can try again?

**Comment by h-2** [comment]
yes please :pray:
