### ISSUE TITLE
Please add to README how to run tests

### ISSUE THREAD

**Issue by yurivict** [seqan/seqan3#2640]
Usually there's a cmake option like ```BUILD_TESTS``` that builds them and then the ```test``` target that runs them.

**Comment by eseiler** [comment]
Dear @yurivict,

we have documentation about building tests here: https://docs.seqan.de/seqan/3-master-user/setup_tests.html

But I agree that it is not the easiest to find :)
Regarding the main README, we link to the setup-tutorial in the [usage](https://github.com/seqan/seqan3#usage) section.

* Would it help to have another link pointing to the test suites documentation in the usage section?

* Would it help to have a "developer" section in the main README?
I often see this in other repositories, but there is the question whether we have enough to put there without repeating the documentation. Maybe it could be a small example like the one for compiling.

There could also be another README in the test folder, but it has the same problem as the previous point.

**Comment by yurivict** [comment]
First I create a temp directory ```build``` and run configure and build there.
When then I run cmake again with ```../../seqan3/test/unit``` - it fails:
```
===>  Testing for seqan3-3.0.2.1195_2
CMake Error: The source "/disk-samsung/freebsd-ports/biology/seqan3/work/seqan3-3.0.2-1195-gee0dbcad/test/unit/CMakeLists.txt" does not match the source "/disk-samsung/freebsd-ports/biology/seqan3/work/seqan3-3.0.2-1195-gee0dbcad/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
*** Error code 1

Stop.
```

cmake doesn't like multiple CMakeLists.txt files. They should be included from each other.

cmake has facilities to define tests: https://cmake.org/cmake/help/latest/command/enable_testing.html

**Comment by marehr** [comment]
If your build folder is empty (your build folder seems to have some left-over files in it)

The following should work:

```bash
cd build
rm -rf *

cmake <seqan3-repo>/test/unit

make
```

**Comment by marehr** [comment]
Maybe I should clarify the process again.

We don't bundle the tests in the top-level cmake, because we have quite different tests that can't be executed at the same time.

We think of our tests more like something that interfaces with our library and for that reason they are decoupled. This has a couple of advantages, as most of the time, someone who wants to USE our library doesn't need our test infrastructure and all the quirks to set it up.

If you want to verify that our library works on your platform you can use the following script:

```bash
git clone --recurse-submodules https://github.com/seqan/seqan3.git
mkdir -p seqan3/build
cd seqan3/build

cmake ../test/unit

make -j 8
ctest
```

**Comment by yurivict** [comment]
Ok, thanks.
