### ISSUE TITLE
remove -Werror in test cases

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#266]
I think it is really annoying to get hard errors on warnings. Especially, when you are developing a new test case and may comment out code or do some other things that result in a warning, which are not that important at the time of conception.

I suggest to pass `-Werror` in our CI via `-DCMAKE_CXX_FLAGS`. This ensures that builds on our CI will fail, but we are still flexible when developing. But, removing them from our default flags.

Personally, I miss the colour differentiation which gets lost by `-Werror`. Everything is red which is really discouraging.

@h-2 Any, thoughts?

**Comment by h-2** [comment]
I don't know, I think having `-Werror` makes it clearer to our developers, that indeed warnings will be treated as errors and must be fixed. You are always free to deactivate this locally, but it should be opt-out.

**Comment by marehr** [comment]
closing this; as it was voted against it
