### ISSUE TITLE
make namespace-scoped const(expr) variables also be inline

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#268]
... so that they are defined only once throughout translation units (and the address taken will be the same). This is especially true for our instances of views, but likely also for other things.

**Comment by marehr** [comment]
Sry, I don't understand what the problem is. Could you elaborate on this and give an example?

**Comment by rrahn** [comment]
I think he means this:
>An inline function or inline variable (since C++17) has the following properties:
>1) There may be more than one definition of an inline function or variable (since C++17) in the program as long as each definition appears in a different translation unit and (for non-static inline functions and variables (since C++17)) all definitions are identical. For example, an inline function or an inline variable (since C++17) may be defined in a header file that is #include'd in multiple source files.
>2) The definition of an inline function or variable (since C++17) must be present in the translation unit where it is accessed (not necessarily before the point of access).
>3) An inline function or variable (since C++17) with external linkage (e.g. not declared static) has the following additional properties:
>1) It must be declared inline in every translation unit.
>2) It has the same address in every translation unit.
In an inline function,

which is important for variables with static storage duration. (Like global variables at namespace scope).
Apparently, namespace scope variables declared `constexpr` are not automatically inlined

**Comment by h-2** [comment]
Yes, for namespace scope variables `constexpr` does not imply `inline` and it does imply internal linkage. `inline constexpr` OTOH implies external linkage. Both are multi-TU-safe, but have different effects. External linkage is preferable, because than there is only one instance with same address.

**Comment by marehr** [comment]
I would prefer code examples where this applies. And then why this change improves the code.

I looked into our `views` and we do not declare a single one `constexpr`:

https://github.com/seqan/seqan3/blob/3ec70140d53880409762ef71f46485d73a235aa0/include/seqan3/range/view/to_rank.hpp#L100

https://github.com/seqan/seqan3/blob/3ec70140d53880409762ef71f46485d73a235aa0/include/seqan3/range/view/to_char.hpp#L98

https://github.com/seqan/seqan3/blob/3ec70140d53880409762ef71f46485d73a235aa0/include/seqan3/range/view/translation.hpp#L334

**Comment by h-2** [comment]
Applies to `const` as well.

Views that are composites of other views will be `constexpr` once the ones in ranges/std are. Our own ones should be `constexpr`.

> And then why this change improves the code.

With `inline` the functors will be guaranteed to have the same address throughout translation units. All namespace scope variables in std and ranges are now explicitly inline.

See for example the shortcut for is_integral_v:
https://en.cppreference.com/w/cpp/types/is_integral

**Comment by marehr** [comment]
Thank you for clarifying 👍
