### ISSUE TITLE
Alternative to chunk view - processing multiple entries in alignment file

### ISSUE THREAD

**Issue by riasc** [seqan/seqan3#2680]
## Platform

  - SeqAn version: 3.03
  - Operating system: macOS 11.2.2
  - Compiler: g++-9

## Question

Hello, I have a quick question about reading an alignment file. What is the best way to read a file in chunks? Since the `chunk view` is not part of the SeqAn API and range-v3s `chunk` is not recommended. In principle, I just want to iterate through the alignment file using 2 entries (or more) at the same time. 

I mean I could create an additional range and go from there. Is there any other way? Thanks

**Comment by marehr** [comment]
Hi riasc,

maybe we should clarify this more. It is not the case that we do not recommend to use other views. Maybe you can point to the documentation that gave you that impression, we should correct that.

We are fans of the complete range concept, and we strongly believe in the power of the "compossibility".
It is just that we - as a Sequence Analysis Library - want to focus more on sequence analysis things and compact our scope as a library. One step is to reduce the number of dependencies of our library, that means that in the near future we will make the ranges-v3 library an optional dependency (just making it a requirement for pre-C++20 compiler; gcc 7-9). One necessary step is to re-implement external views, such as `seqan3::views::chunk()`, or to "deprecate" them (of course you still can use them from the original library!). As those views are outside our scope as a "Sequence Analysis Library".

I don't know if our intent came through, but we put everything into the `utility/` folder that could be made external libraries.

If `ranges::chunk()` does solve your Problem, please use it! We strongly recommend using other libraries. Just be aware that in a future releases you might need to provide the ranges-v3 library yourself, if you want to depend on it :)

I hope I could help you!
Marcel

**Comment by riasc** [comment]
Hello Marcel,
thank you for your swift answer and for pointing that out. So seqan3::views::chunk() is literally the implementation from range-v3. Got it. I guess I was a bit confused because I was still on 3.0.2 (despite writing otherwise) in which chunk was still in range/views. Should have read the CHANGELOG more thoroughly. Good to know that this will still persist for a while. Thanks.

Greetings 
Richard

Closing the issue.
