### ISSUE TITLE
add [[likely]] and [[unlikely]] attributes

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#275]
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0479r5.html

This was merged into C++20 in March. It will transparently start to work as soon as the compiler(s) support it.

**Comment by h-2** [comment]
- [ ] `[[likely]]` before `throw` produces a hard error on GCC >= 7: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86243
  - [ ] `[[likely]]` produces a warning on GCC >= 7 even when neither `-Wall -Wextra` is specified

**Comment by marehr** [comment]
Nice finding; But as I said https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86368 is what I told you ;)

**Comment by h-2** [comment]
> is what I told you ;)

Yes, but it doesn't always produce warnings, unit tests for #285 pass (now warning, no error), header testss for #285 fail  :confused:

**Comment by smehringer** [comment]
@h-2 Do you know if there are updates on this? Can we reevaluate this?

The first bug you reported (86243) is fixed by now.
