### ISSUE TITLE
Change the sampling rate of the suffix array for the fm_index

### ISSUE THREAD

**Issue by Sawwave** [seqan/seqan3#2755]
## Platform

  - SeqAn version: 3.0.2
  - Operating system: Linux 3.10.0-693.5.2.el7.x86_64 \# 1  SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 GNU/Linux
  - Compiler: gcc (GCC) 9.2.0

## Question

I'm looking to create fm_indices with sampling rates for the suffix array other than the default, constant value 16. I have previously been altering the sdsl_wt_index_type found inside fm_index.hpp to change the sampling rate, but I would like to be able to change this value programmatically, and hopefully without having to modify the underlying library. I can't seem to find any documented procedures for creating a different index type, nor can I find any documented procedures for implementing an index with said type. Any help you can offer on the subject would be greatly appreciated.

**Comment by eseiler** [comment]
Hey @Sawwave,

thanks for reaching out, this is indeed not intuitive and not documented.

It could look like this:
```cpp
#include <seqan3/alphabet/nucleotide/dna4.hpp>
#include <seqan3/search/fm_index/all.hpp>

int main()
{
    using sdsl_wt_index_type =
        sdsl::csa_wt<sdsl::wt_blcd<sdsl::bit_vector, // Wavelet tree type
                                sdsl::rank_support_v<>,
                                sdsl::select_support_scan<>,
                                sdsl::select_support_scan<0>>,
                    8, // Sampling rate of the suffix array
                    10'000'000, // Sampling rate of the inverse suffix array
                    sdsl::sa_order_sa_sampling<>, // How to sample positions in the suffix array (text VS SA sampling)
                    sdsl::isa_sampling<>, // How to sample positons in the inverse suffix array
                    sdsl::plain_byte_alphabet>; // How to represent the alphabet

    seqan3::fm_index<seqan3::dna4, seqan3::text_layout::collection, sdsl_wt_index_type> index{/*some text*/};
}
```

The `fm_index` takes 3 template parameters: alphabet, text_layout (a single string / a collection of strings), and the used underlying SDSL index type. The first two are usually deduced when constructing an index with a text, and the SDSL defaults.

Do you have a snippet of how you currently use the FM-Index? 
We will add some documentation for this use case, but we might want to consider this case regarding the API.

**Comment by Sawwave** [comment]
Thank you for the example, this clears up a few questions I had about the fm_index construction. In an ideal world, I would like to be able to able to treat the SA sampling rate as a variable in fm_index construction, but I realize that might not be feasible, since you're using the sdsl::csa_wt template (requiring the sampling rate to be compile-time constant).

My current code allows the user to load a .fasta file, and create an index using either the dna5 or aa27 alphabet types. That, combined with the fact that we know our benchmarks will only have a single sequence in the .fasta leads to some rather ugly code.


```
if(isAmino){
  //the amino sequence file needs the <sequence_file_input_default_traits_aa> trait in oder to read as protein data.
  seqan3::sequence_file_input<seqan3::sequence_file_input_default_traits_aa> fastaContents{databaseSequenceInputFileSrc};
  //seqan3 only has examples of using a for-each loop to get sequences out of the file, so I guess that's what we gotta do.

  for(auto & record: fastaContents){
    //we know for a fact that the .fasta file will only have one sequence inside, so read the first one and break.
    seqan3::fm_index<seqan3::aa27, seqan3::text_layout::single> index(seqan3::get<seqan3::field::seq>(record));
    std::ofstream stream {indexFileSrc, std::ios::binary};
    cereal::BinaryOutputArchive oarchive{stream};
    oarchive(index);
    break;
  }
}
else{
  seqan3::sequence_file_input fastaContents{databaseSequenceInputFileSrc};
   //seqan3 only has examples of using a for-each loop to get sequences out of the file, so I guess that's what we gotta do.
  for(auto & record: fastaContents){
     //we're only going to grab the first entry, so we'll quit out after this.
    seqan3::fm_index<seqan3::dna5, seqan3::text_layout::single> index(seqan3::get<seqan3::field::seq>(record));
    //seqan3::fm_index<seqan3::dna5, seqan3::text_layout::single> index(record.id());
    std::ofstream stream {indexFileSrc, std::ios::binary};
    cereal::BinaryOutputArchive oarchive{stream};
    oarchive(index);
    break;
  }
}
```

Note that nowhere in here am I setting the SA ratio, the only way I could figure out how to modify this was running a script that replaced the hard-coded 16 inside the internal sdsl_wt_index_type definition, and recompile.




To load and run a locate() benchmark, I loaded one of two query sets and index objects, and then query each one.

```
seqan3::fm_index<seqan3::dna5, seqan3::text_layout::single> nucIndex;
std::vector<std::vector<seqan3::dna5>> nucQueries;
seqan3::fm_index<seqan3::aa27, seqan3::text_layout::single> aminoIndex;
std::vector<std::vector<seqan3::aa27>> aminoQueries;


if(isAmino){
  std::ifstream is{indexFileSrc, std::ios::binary};
  cereal::BinaryInputArchive iarchive{is};
  iarchive(aminoIndex);

  aminoQueries = generateAminoQueries()
  }
else{
  std::ifstream is{indexFileSrc, std::ios::binary};
  cereal::BinaryInputArchive iarchive{is};
  iarchive(nucIndex);
}


//perform locate on the index, keeping a count of # of hits, and add the hit position to a dummy so I can be guaranteed that
// the compiler doesn't try to optimize-away the actual search.
if(isAmino){
  auto searchResult = seqan3::search(aminoQueries, aminoIndex);

  for(auto result: searchResult){
    countTotal++;
    dummyReferenceValue += result.reference_begin_position();
  }
}
else{
  auto searchResult = seqan3::search(nucQueries, nucIndex);

  for(auto result: searchResult){
    countTotal++;
    dummyReferenceValue += result.reference_begin_position();
  }
}
```


As previously mentioned, I would love to be able to set the SA sampling rate and alphabet using run-time variables, but that doesn't seem possible using the templating from sdsl. With this in mind, I think the solution I will modify the code snippit given above by @eseiler , replacing the hard-coded SA sampling rate with a macro definition:

```
#include <seqan3/alphabet/nucleotide/dna4.hpp>
#include <seqan3/search/fm_index/all.hpp>


#define DEFAULT_SA_SAMPLING_RATE 16 //this is the default sampling rate if none is specified at compile time
#ifndef SA_SAMPLING_RATE
#define SA_SAMPLING_RATE DEFAULT_SA_SAMPLING_RATE
#endif
int main()
{
    using sdsl_wt_index_type =
        sdsl::csa_wt<sdsl::wt_blcd<sdsl::bit_vector, // Wavelet tree type
                                sdsl::rank_support_v<>,
                                sdsl::select_support_scan<>,
                                sdsl::select_support_scan<0>>,
                    SA_SAMPLING_RATE, // Sampling rate of the suffix array
                    10'000'000, // Sampling rate of the inverse suffix array
                    sdsl::sa_order_sa_sampling<>, // How to sample positions in the suffix array (text VS SA sampling)
                    sdsl::isa_sampling<>, // How to sample positons in the inverse suffix array
                    sdsl::plain_byte_alphabet>; // How to represent the alphabet

    seqan3::fm_index<seqan3::dna4, seqan3::text_layout::collection, sdsl_wt_index_type> index{/*some text*/};
}
```

Then, when I wish to run a benchmark with a specific SA sampling rate, compile with the option -DSA_SAMPLING_RATE=4, or whatever specific sampling rate is required for the test.


As long as the sampling rate lives as a template parameter, I don't think I'll be able to get away without recompiling, unless I instantiate templates for all feasible sampling rates. This seems like a quagmire I would rather not get lost in, TBH.

**Comment by smehringer** [comment]
Hi @Sawwave,

thanks for you detailed response which shows how to solve the problem (although not in a nice way because a nice way is not possible).

Bad news, we will not change the sdsl.
Good news, we might be switching the FM index implementation with this one https://github.com/SGSSGene/fmindex-collection. Here, the sampling rate is a runtime parameter! But the project is currently under construction with only little to no documentation or fixed API. @SGSSGene would be the person to talk to, if this is still an issue for you and you would like to try out his implementation.

We will close the issue as there is nothing we can do (IMHO).
Feel free to reopen the issue if you still have questions or don't feel like this is resolved for you.
