### ISSUE TITLE
Argument Parser TODOs

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#277]
- [ ] Write more tests
- [ ] Check if the validators for containers and non-containers can be modeled by two functions/operators rather than two separate classes. (This was done in a former commit but reversed..)
- [ ] A lot of string parameters are passed by reference and are then copied, instead of copied in the fnction call and then moved (copy elision)
- [ ] Check that the lambda functions do not copy everything but pass the arguments by reference.

**Comment by h-2** [comment]
>  Check that the lambda functions do not copy everything but pass the arguments by reference.

IIRC the lambdas where required to copy, because they are stored/called in a scope that outlives the calling context (and thus references would be invalidated).

**Comment by rrahn** [comment]
Well, this would be a reason to copy them. 👍

**Comment by marehr** [comment]
What is meant by "after merging" in the title? Is this right now? :grin:

**Comment by smehringer** [comment]
transferred to cards in Project Argument Parser
