### ISSUE TITLE
CMake generator "Ninja" does not work

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#281]
On Unix cmake can generate gnu-make files or ninja files, this *should* be transparent, but something in our setup breaks it. It would be good to get this fixed, because the cmake-support of many IDEs only works with Ninja, but not gnu-make.

**Comment by marehr** [comment]
> cmake -GNinja ../../seqan3/test/unit -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_CXX_FLAGS=-fdiagnostics-color -DCMAKE_BUILD_TYPE=Debug
> ninja     
ninja: error: 'lib/libgtest_maind.a', needed by 'alignment/aligned_sequence_test', missing and no known rule to make it
