### ISSUE TITLE
Constexpr for the CIGAR char literal

### ISSUE THREAD

**Issue by joergi-w** [seqan/seqan3#2819]
In some contexts, the cigar character needs to be used in constexpr context, e.g.
```cpp
    seqan3::cigar::operation op = 'M'_cigar_operation;
    switch (op.to_rank())
    {
        case 'M'_cigar_operation.to_rank():
            ;
    }
```

I think that it is useful to implement this and I'll provide a PR for it.

**Comment by marehr** [comment]
This is a bug. We forgot to put constexpr at the literal operator.

Can you double-check all char literal operators if they are declared constexpr?

**Comment by joergi-w** [comment]
> Can you double-check all char literal operators if they are declared constexpr?

I checked, and this is the only one 👍🏽

**Comment by eseiler** [comment]
The only thing I want to add is that we should also add `constexpr` to
```cpp
inline aa10li_vector operator""_aa10li(char const * const s, size_t const n)
```
if the compiler supports `constexpr std::vector`. 

But this should be another PR in any case.

**Comment by marehr** [comment]
@eseiler Good point!

**Comment by eseiler** [comment]
> @eseiler Good point!

We could probably do something like this

```cpp
#if defined(__cpp_lib_constexpr_vector) && __cpp_lib_constexpr_vector >= 201907L
#    define SEQAN3_CHAR_LITERAL_VECTOR constexpr
#else
#    define SEQAN3_CHAR_LITERAL_VECTOR inline
#endif
```

However, only MSVC implements `constexpr` for `std::vector`.

https://godbolt.org/z/EKGxYnEas

**Comment by eseiler** [comment]
Resolved via https://github.com/seqan/seqan3/pull/2820
