### ISSUE TITLE
`seqan3::views::translate` does not compile without specifying `frame`

### ISSUE THREAD

**Issue by madagiurgiu25** [seqan/seqan3#2909]
Hi together,

The issue refers to `views`, chapter _Views in the standard library and in SeqAn_.

I tried running this code from the tutorial and I receive and error.
It seems that I cannot run `seqan3::views::translate` without specifying the `frame`.

```
# original (this generates an error to specify which frame)
seqan3::debug_stream << "Frames:   " << (s_as_dna | seqan3::views::translate) << '\n';
```

What it worked for me:

```
seqan3::debug_stream << "Frames:   " << (s_as_dna | seqan3::views::translate(seqan3::translation_frames::six_frames)) << '\n';
```

Same applies for `seqan3::views::translate_join`, I cannot create a view pipe and not specify the translation frame.

**Comment by eseiler** [comment]
Hey there,

our tutorial snippets are part of the continuous integration tests and therefore *should* always work.

Can you provide more information, please?

- seqan version/commit
- compiler
- code you are trying to compile
- error message

**Comment by madagiurgiu25** [comment]
The error still persists even after updating to latest seqan3 commit (https://github.com/seqan/seqan3/commit/8a4f31cb7)

```
(base) madag@Madas-MacBook-Pro seqan3 % pwd
/.../seqan3_test/lib/seqan3
(base) madag@Madas-MacBook-Pro seqan3 % git describe HEAD
3.1.0-268-g8a4f31cb7
(base) madag@Madas-MacBook-Pro seqan3 % git status       
On branch master
Your branch is up to date with 'origin/master'.
```

Error:

```
[ 50%] Building CXX object src/CMakeFiles/seqan3_test_lib.dir/ranges.cpp.o
/usr/src/seqan3_test/src/ranges.cpp: In function 'int complementSequence(int, char**)':
/usr/src/seqan3_test/src/ranges.cpp:90:77: error: expected primary-expression before ')' token
   90 |     auto v2 = vec | seqan3::views::translate_join(seqan3::translation_frames);
      |                                                                             ^
make[2]: *** [src/CMakeFiles/seqan3_test_lib.dir/build.make:134: src/CMakeFiles/seqan3_test_lib.dir/ranges.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:288: src/CMakeFiles/seqan3_test_lib.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

**Comment by eseiler** [comment]
> Error:
> 
> ```
> [ 50%] Building CXX object src/CMakeFiles/seqan3_test_lib.dir/ranges.cpp.o
> /usr/src/seqan3_test/src/ranges.cpp: In function 'int complementSequence(int, char**)':
> /usr/src/seqan3_test/src/ranges.cpp:90:77: error: expected primary-expression before ')' token
>    90 |     auto v2 = vec | seqan3::views::translate_join(seqan3::translation_frames);
>       |                                                                             ^
> make[2]: *** [src/CMakeFiles/seqan3_test_lib.dir/build.make:134: src/CMakeFiles/seqan3_test_lib.dir/ranges.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:288: src/CMakeFiles/seqan3_test_lib.dir/all] Error 2
> make: *** [Makefile:160: all] Error 2
> ```

It should be either 
```cpp
auto v2 = vec | seqan3::views::translate_join(seqan3::translation_frames::six_frames);
// or any other translation frame: https://docs.seqan.de/seqan/3-master-user/namespaceseqan3.html#add11e2b24db6ff71d7c3d3ca3ea9268d
``` 

or 

```cpp
auto v2 = vec | seqan3::views::translate_join;
// Just uses default
```

Can you try the latter one?

**Comment by madagiurgiu25** [comment]
> It should be either
> 
> ```c++
> auto v2 = vec | seqan3::views::translate_join(seqan3::translation_frames::six_frames);
> // or any other translation frame: https://docs.seqan.de/seqan/3-master-user/namespaceseqan3.html#add11e2b24db6ff71d7c3d3ca3ea9268d
> ```
> 
> or
> 
> ```c++
> auto v2 = vec | seqan3::views::translate_join;
> // Just uses default
> ```
> 
> Can you try the latter one?

Ohh, I see. Both version work. Thank you!
