### ISSUE TITLE
`alphabet/views/all.hpp`: `complement` and `translate_join` missing

### ISSUE THREAD

**Issue by madagiurgiu25** [seqan/seqan3#2910]
Dear team,

I was working through the SeqAn3 Tutorial. This issue refers to `views`, chapter _Views in the standard library and in SeqAn_:
The `#include <seqan3/alphabet/views/all.hpp>` does not include `complement.hpp` (I updated seqan3 to the latest version).
The `translate_join.hpp` is also missing.

**Comment by eseiler** [comment]
Hey there,

can you tell us the exact version you are using (commit / seqan version)?

The includes were missing in seqan 3.0.3, but are there in 3.1.0 (latest release):

https://github.com/seqan/seqan3/blob/3.1.0/include/seqan3/alphabet/views/all.hpp#L21-L28

**Comment by madagiurgiu25** [comment]
Hi @eseiler,

- seqan commit:  https://github.com/seqan/seqan3/commit/52f201a5e
- C++ compiler version is: 11.2

I managed now to update to latest version using (`--force` seems important):

```
git submodule update --recursive --remote --merge --force

git describe HEAD  
3.1.0-268-g8a4f31cb7
```
And know I also see the updates.
Thank you!
