### ISSUE TITLE
Missing includes with `gcc11 -std=c++17`

### ISSUE THREAD

**Issue by tloka** [seqan/seqan3#2913]
`include/seqan3/io/sam_file/output_format_concept.hpp` is missing 

```c++
#include <optional>
```

that is explicitly used in lines 87 and 88:

```c++
std::optional<int32_t>                                               & ref_id,
std::optional<int32_t>                                               & ref_offset,
``` 

and 93:

```c++
std::tuple<std::optional<int32_t>, std::optional<int32_t>, int32_t>  & mate,
```

Just writing this, `std::tuple` is also not included.

**Comment by eseiler** [comment]
We don't include headers that are already included by other (seqan3-)headers.
In general, we keep the includes in the library to the absolute minimum - which we can automate once we have clang support.

We only enforce that including a single header includes everything the header needs. This is done by the header test.

**Comment by tloka** [comment]
Maybe I do something wrong here, but:
```c++
/builds/seqstant/livetools/submodules/seqan3/include/seqan3/io/sam_file/output_format_concept.hpp:85:15: 
error: 'std::optional' has not been declared
```

**Comment by smehringer** [comment]
Yes try and update. But either way an error like this is usually caught in our header tests :thinking: If the error persists after the update, can you supply us with compiler and platform information?

**Comment by eseiler** [comment]
I did some digging; it's a very ugly include path, but in the end, `#include <seqan3/std/ranges>` provides `optional`.
`#include <ranges>` is also enough if your compiler supports it.

**Comment by tloka** [comment]
I will run some testing, but it will also not be 100% trivial for me as this error only shows up in my CI setup. Locally, everything compiles fine.. Still possible that it's an error on my side, I will have a more detailed look ..

**Comment by eseiler** [comment]
Is the CI something we can access?

Might be something STL related, because I did not look into where `<ranges>` includes `optional`...

**Comment by tloka** [comment]
> Is the CI something we can access? Anyway, compiler versions and such would help to narrow it down.

Naa, it's a private repo, I can't give access to that. However, main difference is that the CI currently only uses GCC 11 (I have still GCC 9 locally installed). So, probably it switches to `std:.ranges` in the CI where I am using `seqan3::std::ranges` in my local setup.  

I will let you know once I find out more; I need to get it running first for now and will check the newest SeqAn3 version and different compiler versions locally afterwards.

**Comment by eseiler** [comment]
We always use `std::ranges`; when on gcc-11; or generally when the `ranges` header is available, we internally use `#include <ranges>` and otherwise we use range-v3 and pull the stuff into the `std` namespace.

`range-v3` includes `functional`, which somewhere pulls `optional`

STL has an explicit include:
https://github.com/gcc-mirror/gcc/blob/7ca388565af176bd4efd4f8db1e5e9e11e98ef45/libstdc%2B%2B-v3/include/std/ranges#L44

So if 

```cpp
#include <ranges>

int main()
{
    std::optional<int> x;
}
```

doesn't compile on your gcc 11, something's wrong.

**Comment by tloka** [comment]
True, I guess that's exactly what I am running. I didn't activate cpp20 yet, it's always running with cpp17 (independent of the compiler version used). Thus, both compilers end up in `<functional>`, which does not include `<optional>` with gcc11.

**Comment by eseiler** [comment]
I guess we could add header tests for `gcc11 -std=c++17` to the nightlies and then fix the missing includes.
I wouldn't run the whole test suite, but at least making sure all includes are there seems sensible.

@smehringer @SGSSGene do you agree?

**Comment by smehringer** [comment]
> I guess we could add header tests for `gcc11 -std=c++17` to the nightlies and then fix the missing includes. I wouldn't run the whole test suite, but at least making sure all includes are there seems sensible.
> 
> @smehringer @SGSSGene do you agree?

Yes can't hurt to have them :)

**Comment by eseiler** [comment]
I opened https://github.com/seqan/seqan3/pull/2914
There are two `#include <optional>` missing.
