### ISSUE TITLE
Implement with_gaps functor and linear_gaps config for pairwise alignment

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#300]
Implement a static config based on `seqan3::detail::config_base` for linear gap costs.
The config should take one parameter that represents the penalty for adding an indel.

Here is a possible checklist:
- [x] rebase PR #295 on your master
- [x] familliarize yourself with the documentation and the tests for configurator and config_base
- [x] implement a aggregate class called linear_gaps with one member for the penealty
- [x] implement a with_gaps configurator functor
- [x] the functor should be in the namespace `seqan3::align::`
- [x] implement a static config as base of `config_base` that can be used to access the data.
- [x] add detail documentation for the config
- [x] add user documentation for using the `with_gaps` functor.

How it should look like:
```cpp
auto cfg = alignment::global_alignment | alignment::with_gaps(align::linear_gaps, 1);
align(rng, cfg)
```

Fixed by #349

**Comment by marehr** [comment]
Is this done?
