### ISSUE TITLE
mask-alphabet and masked-alphabet composition

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#306]
- [x] Read through http://docs.seqan.de/seqan/3.0.0-master-user/group__composition.html and the individual documentation pages; you can also look at the code of the the composition templates, but it is probably more difficult to understand
  - [ ] Instead or additionally look at the example alphabets that are based on them, like seqan3::gapped (a union_composition) and seqan3::quality_composition (a cartesian_composition) and try figure out what's going on
  - [ ] implement `seqan3::mask`, a "semi_alphabet" (only rank notation, no char notation) that has bool as rank type or an enum and the static members `::UNMASKED` and `::MASKED`
  - [ ] implement `seqan3::masked<>` template that is derived of seqan3::cartesian_composition and combines the seqan3::mask alphabet with another alphabet, in such a way that the character representation is that of the other alpahbet, except that if the seqan3::mask half of the combined alphabet is true, the character will be converted to lower-case ( you can use https://en.cppreference.com/w/cpp/locale/tolower for this)

In the end one should be able to do:
```cpp
masked<dna5> l;
l = dna5::G;
l = mask::UNMASKED;
std::cout << to_char(l); // prints 'G'
l = mask::MASKED;
std::cout << to_char(l); // prints 'g'
```

PS: you will need to relax the constraints on types that are accepted by cartesian_composition, currently they are required to alphabet, but they should only be required to be semi_alphabet.

**Comment by marehr** [comment]
Can you give a rational for the naming `UNMASKED` and `MASKED`? It sounds odd to me.

**Comment by h-2** [comment]
> Can you give a rational for the naming UNMASKED and MASKED? It sounds odd to me.

https://bioinformatics.stackexchange.com/questions/225/uppercase-vs-lowercase-letters-in-reference-genome

**Comment by h-2** [comment]
@joshuak94 You can ask @marehr all the technical questions, but @joergi-w should also be able to help you out while I am on vacation and in the next days!

**Comment by marehr** [comment]
Is this done?

**Comment by joshuak94** [comment]
@marehr I think so... #308 introduces the mask and masked classes, both of which have been merged into the master.
