### ISSUE TITLE
How to update an already built FM-Index

### ISSUE THREAD

**Issue by Wang-kaifei** [seqan/seqan3#3114]
Dear developers, 

I am currently learning to use SeqAn3 and I am curious if there is support for updating an FM-Index that has already been constructed? For example, I first constructed the FM-Index from a collection of strings, and then a new string appeared that needed to be added. Is there a way to update the FM-index on the original one? 

Sincerely,
Flora

**Comment by SGSSGene** [comment]
Hi Flora

Currently, there is no support to update an FM-Index in the SeqAn3 library.
The only way to achieve an updated FM-Index is to completely reindex it.

In theory (not in our code), there exists ways to merge multiple BWT together, which would allow to skip the most expensive part of the reindexing, which is the construction of the BWT, but these haven't been explored by us, yet.

**Comment by Wang-kaifei** [comment]
I see, thanks a lot for your reply.  : )

> Hi Flora
> 
> Currently, there is no support to update an FM-Index in the SeqAn3 library. The only way to achieve an updated FM-Index is to completely reindex it.
> 
> In theory (not in our code), there exists ways to merge multiple BWT together, which would allow to skip the most expensive part of the reindexing, which is the construction of the BWT, but these haven't been explored by us, yet.
