### ISSUE TITLE
Meta-Issue for Index Module

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#315]
This is a meta-issue for the index module:
Collect all ideas, items that need to be done in this issue and make small new issues from this list.

**Comment by rrahn** [comment]
@cpockrandt Please can you fill this, also add items for the things that you already have and reference them. And please look into the Milestone: Index Module and add a list of items that need to be done for this milestone. You can have a look into #314 to see what I mean. I hope I'll be next week in the office, so we can discuss this.

**Comment by smehringer** [comment]
Issue #465 summarizes issues for the search module but was also closed in fviour of cards in the Search Project.
