### ISSUE TITLE
[Meta-Issue] Streams

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#317]
# Compressor Streams
* zlib_stream
* zlib_stream_buffer
* bzib_stream
* bzib_stream_buffer
* bgzf_stream
* bgzf_stream_buffer

# Decompressor Streams
* unzlib_stream
* unzlib_stream_buffer
* unbzib_stream
* unbzib_stream_buffer
* unbgzf_stream
* unbgzf_stream_buffer

# Virtual Stream
* transparent stream handler for compressor/decompressor streams
* chunk_view, expose direct read/write functionality to buffer avoiding virtual function calls of regular streams

**Comment by smehringer** [comment]
Transferred to Project IO Stream
