### ISSUE TITLE
IBF and HIBF 

### ISSUE THREAD

**Issue by lutfia95** [seqan/seqan3#3192]
Hi Seqan-Team,

I have tested the ability of IBF to store many small protein sequences. I use the alphabet `seqan3::aa27`, the inserted sequences are not very long (maximum `13556` amino acids), but the number of bins is relatively large (`683337` and the RVDB with `34731189` sequences). Since I am classifying peptide sequences, I need to insert the sequences into `683337` (or `34731189` for RVDB) bins. The computed bin size is about (**55.31KiB**) corresponding to the longest sequence, since each bin has the same size. This process results in very high memory footprint since I am dealing with a lot of bins. Do you recommend using HIBF in this case? Actually, I am not interested in where I have the k-mers  (e.g. in FM index), the only thing I would like to classify is each peptide into a specific bin. I thought about using minimizers, but I don't think it will solve the problem.

Best,
Ahmad

**Comment by smehringer** [comment]
Hi @lutfia95,

Thanks for reaching out!

Indeed the HIBF might be better suited when dealing with many bins. But:
Whether the HIBF can reduce the memory footprint depends on the size distribution of your input. If it is skewed (max and min size differ largely) chances are good. Worst case ( all sequences equal in size), it could double the space requirements. It will speed up your queries either way.

You can try out the HIBF here: https://github.com/seqan/hibf

The HIBF library is not released yet but we think it should be already ready to use. Please get back to us with any questions, remarks or bugs.

The HIBF will need to compute a layout. For the amount of bins you have, we recommend setting the config option `seqan::hibf::config:: disable_rearrangement` to true. Rearrangement can improve the layout as similar input sequences might be merged in the same bins leading to smaller total sizes. But currently it doesn't scale well to many user bins. 

Best,
Svenja

**Comment by lutfia95** [comment]
Hi Svenja, 

thank you very much for your reply, I will check the HIBF implementation and look out how can I use it. Is it also possible to use the same bin insertion concept with HIBF? In IBF, we insert the sequences into specific bin e.g. `ibf.emplace(value, seqan3::bin_index{4u});`. I would like to avoid reading the sequences from file, basically the sequences are read first from file, then many sequences are processed, and I want to skip the part of writing them to file then reading them again for HIBF insertion by just inserting them into the HIBF, which will reduce the run time and the usage of memory. 

Best,
Ahmad

**Comment by smehringer** [comment]
Hi Ahmed,

@eseiler will hopefully have time to add some example snippets tomorrow to ease the transition.

The bad news: The construction is different from the IBF in Seqan3. And it's a little more complex.

The good news: You should have similar flexibility and you are definitely not required to provide files.

Best,
Svenja

**Comment by lutfia95** [comment]
Hi Svenja, 

the bad news sound not that bad, I will go with the good news ;) 

P.S: I will close the issue as answered! 

Best,
Ahmad

**Comment by smehringer** [comment]
Something along these lines you can try:

```cpp
#include <iostream>   // for operator<<, basic_ostream, char_traits, cout
#include <ranges>     // for _Iota, iota, views
#include <vector>     // for vector

#include <hibf/config.hpp>                                // for config, insert_iterator
#include <hibf/hierarchical_interleaved_bloom_filter.hpp> // for hierarchical_interleaved_bloom_filter

int main()
{
    
    std::vector<std::vector<seqan3::aa27>> protein_sequences{...};

    auto get_user_bin_data = [&](size_t const user_bin_id, seqan::hibf::insert_iterator it)
    {
        for (auto protein_seq : protein_sequences[user_bin_id])
        {
            for (uint64_t hash : protein_seq | hash_me)
                it = hash;
        }
    };

    seqan::hibf::config config{.input_fn = get_user_bin_data, // required
                               .number_of_user_bins = 3u,     // required
                               .number_of_hash_functions = 2u,// recommended
                               .maximum_false_positive_rate = 0.05, // what suits your data?
                               .threads = 1u};

    seqan::hibf::hierarchical_interleaved_bloom_filter hibf{config};

    // Now we can search for some query, suppose we already have the hash values:
    std::vector<uint64_t> query1{3u, 9u, 12u, 14u};

    auto agent = hibf.membership_agent();
    auto & result1 = agent.membership_for(query1, 2u); // Note that we bind the result with a `&` to avoid copies!

    for (int64_t hit_user_bin : result1)
        std::cout << hit_user_bin << ' ';
    std::cout << '\n';
}
```

**Comment by lutfia95** [comment]
Hey Svenja, 

thank you very much for providing the example! I have two questions in between: 

- Regarding the hashing adapter, can I use the usual one (e.g. `auto hash_me = seqan3::views::kmer_hash(seqan3::ungapped{kmer_size});`). ´? 
- Should the sequences be inserted into the `std::vector`? or can I insert them during other loop in the user bin? Storing them all inside the `std::vector` might be RAM costly in case of many sequences.
- If not, can I actually use the HIBF in a case such as having vector of vectors? e.g. `std::vector<std::vector<std::vector<seqan3::aa27>>> protein_sequences{{"AAH"_aa27, "AHY"_aa27}, {"LNA"_aa27, "NAL"_aa27, "ALN"_aa27}};` . Where `{"AAH"_aa27, "AHY"_aa27}` is the first user bin and `{"LNA"_aa27, "NAL"_aa27, "ALN"_aa27}}` is the second one. They are the k-mers already proceeded and ready to be inserted inside the filter. 

Best,
Ahmad

**Comment by smehringer** [comment]
> Hey Svenja,
> 
> thank you very much for providing the example! I have two questions in between:
> 
>     * Regarding the hashing adapter, can I use the usual one (e.g. `auto hash_me = seqan3::views::kmer_hash(seqan3::ungapped{kmer_size});`). ´?
> 

Yes. Whatever worked for you before with the IBF. The only hard requirement we have, is that the hash values are convertible to `uint64_t` (which is the case for `kmer_hash`).

>     * Should the sequences be inserted into the `std::vector`? or can I insert them during other loop in the user bin? Storing them all inside the `std::vector` might be RAM costly in case of many sequences.

No! You do not need to store them in a vector. Good question though, I'll keep that in mind for documenting. Basically, you can do whatever you want inside the lambda. You just need to know which user bin / protein-sequence refers to `user_bin_id` and then assign whatever values you deem correct (convertible to `uint64_t`) into the HIBF via `it = value`/`it = hash`. You could even read a file within the body of the lambda. If you need help, you can explain your use case to me.

>     * If not, can I actually use the HIBF in a case such as having an vector of vectors? e.g. `std::vector<std::vector<std::vector<seqan3::aa27>>> protein_sequences{{"AAH"_aa27, "AHY"_aa27}, {"LNA"_aa27, "NAL"_aa27, "ALN"_aa27}};` . Where `{"AAH"_aa27, "AHY"_aa27}` is the first user bin and `{"LNA"_aa27, "NAL"_aa27, "ALN"_aa27}}` is the second one. They are the k-mers already proceeded and ready to be inserted inside the filter.
> 

See above. It just needs some thinking about the lambda design.

> Best, Ahmad

Best,
Svenja
