### ISSUE TITLE
small documentation error

### ISSUE THREAD

**Issue by notestaff** [seqan/seqan3#3237]
At
https://github.com/seqan/seqan3/blob/ffabe95327e99f954db0cf116ce189b36284c49d/include/seqan3/contrib/stream/bgzf.hpp#L17
the variable is no longer static.

Also, maybe doc/cookbook/compression_threads.cpp should include this file, rather than seqan3/io/all.hpp?   Or this file is not part of the public API?

**Comment by SGSSGene** [comment]
Thank you! This is a mistake in the documentation. PR #3238 will fix this.

**Comment by eseiler** [comment]
The contrib include is completely non-API.

But you don't need `io/all.hpp` either.
If you only use a specific io, it is enough to include that.

Any IO that supports compression will implicitly include this bgzf header.
