### ISSUE TITLE
travis builds broken for debug benchmark builds

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#347]
Has someone seen these errors before?

From [travis](https://travis-ci.org/seqan/seqan3/jobs/411385067):

>[ 75%] Building CXX object alphabet/CMakeFiles/alphabet_benchmark.dir/alphabet_benchmark.cpp.o
[ 83%] Linking CXX executable alphabet_benchmark
../lib/libbenchmark.a(benchmark.cc.o): In function `RunBenchmark':
/home/travis/build/seqan/seqan3-build/vendor/benchmark/src/benchmark.cc:308: undefined reference to `benchmark::ComputeStats(std::vector<benchmark::BenchmarkReporter::Run, std::allocator<benchmark::BenchmarkReporter::Run> > const&)'
../lib/libbenchmark.a(benchmark_register.cc.o): In function `benchmark::internal::Benchmark::Benchmark(char const*)':
/home/travis/build/seqan/seqan3-build/vendor/benchmark/src/benchmark_register.cc:249: undefined reference to `benchmark::StatisticsMean(std::vector<double, std::allocator<double> > const&)'
/home/travis/build/seqan/seqan3-build/vendor/benchmark/src/benchmark_register.cc:250: undefined reference to `benchmark::StatisticsMedian(std::vector<double, std::allocator<double> > const&)'
/home/travis/build/seqan/seqan3-build/vendor/benchmark/src/benchmark_register.cc:251: undefined reference to `benchmark::StatisticsStdDev(std::vector<double, std::allocator<double> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [alphabet/alphabet_benchmark] Error 1
make[2]: Target `alphabet/CMakeFiles/alphabet_benchmark.dir/build' not remade because of errors.
make[1]: *** [alphabet/CMakeFiles/alphabet_benchmark.dir/all] Error 2
Scanning dependencies of target example_benchmark
[ 91%] Building CXX object example/CMakeFiles/example_benchmark.dir/example_benchmark.cpp.o
[100%] Linking CXX executable example_benchmark
../lib/libbenchmark.a(benchmark.cc.o): In function `RunBenchmark':
/home/travis/build/seqan/seqan3-build/vendor/benchmark/src/benchmark.cc:308: undefined reference to `benchmark::ComputeStats(std::vector<benchmark::BenchmarkReporter::Run, std::allocator<benchmark::BenchmarkReporter::Run> > const&)'
../lib/libbenchmark.a(benchmark_register.cc.o): In function `benchmark::internal::Benchmark::Benchmark(char const*)':
/home/travis/build/seqan/seqan3-build/vendor/benchmark/src/benchmark_register.cc:249: undefined reference to `benchmark::StatisticsMean(std::vector<double, std::allocator<double> > const&)'
/home/travis/build/seqan/seqan3-build/vendor/benchmark/src/benchmark_register.cc:250: undefined reference to `benchmark::StatisticsMedian(std::vector<double, std::allocator<double> > const&)'
/home/travis/build/seqan/seqan3-build/vendor/benchmark/src/benchmark_register.cc:251: undefined reference to `benchmark::StatisticsStdDev(std::vector<double, std::allocator<double> > const&)'
collect2: error: ld returned 1 exit status

I could not reproduce them locally on my mac.

**Comment by marehr** [comment]
something broke benchmark. Maybe is the upstream version broken.

**Comment by rrahn** [comment]
Ok, I rebuild the job and see if the error might be fixed already upstream. I couldn't spot it in the other PRs.

**Comment by marehr** [comment]
This was just a guess. There seems to be some symbols missing in debug build. The release build is working without any problems.

**Comment by rrahn** [comment]
I know, but as I said, it does not occur on other PRs either and I did not touch anything in the modules being built. So fingers crossed, because locally I couldn't reproduce it.

**Comment by marehr** [comment]
This should be fixed by #413
