### ISSUE TITLE
redesign cartesian_composition to not be tuple

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#355]
All our alphabets are implemented as just being the rank type with some voodoo around it, **except** the cartesian_composition which is currently always implemented as a tuple. It would be nice to actually compress immediately so that `quality_composition<dna5, illumin18>` only consumes 1 byte and not two.

**Comment by h-2** [comment]
Would also resolve current issues with `masked<>`

**Comment by marehr** [comment]
Like the union_composition we would select `uint8_t`, `uint16_t`, `uint32_t`, `uint64_t` depending how large the product is.

**Comment by h-2** [comment]
changed via #535
