### ISSUE TITLE
Collection of Minor issues and typos.

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#358]
- [ ] File https://github.com/seqan/seqan3/blob/master/include/seqan3/alphabet/gap/all.hpp has no `#pragma once`

- [ ] The documentation group opened here has no closing bracket : https://github.com/seqan/seqan3/blob/master/include/seqan3/std/concept/core_language.hpp#L153

- [ ] The record code example is wrong (order of types and get according function) : http://docs.seqan.de/seqan/3.0.0-master-user/structseqan3_1_1record.html

- [ ] The `write_eol` function in IO has a wierd documentation as "\n" is displayed as an actual new line instead of the character: http://docs.seqan.de/seqan/3.0.0-master-dev/group__io.html#gaf387d6832c3e03849af06740694ada9c

- [ ] In many files the date is still `2016-2017` and needs to be updated.

**Comment by marehr** [comment]
duplicate of #213
