### ISSUE TITLE
How does structured_rna::pseudoknot_id work?

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#378]
Hi Jörg,

maybe you can help me to understand this part of the code (especially line [194](#L194)):

https://github.com/seqan/seqan3/blob/7fbbefe94b542499ad58bd9293092fe9b84b2a9e/include/seqan3/alphabet/structure/structured_rna.hpp#L190-L198

I think it is strange that you can make a `constexpr` decision on the current state of a runtime value. I think this needs to be fixed, but I don't know what the expected outcome is.

Do you have test cases for `structure_alphabet_type::pseudoknot_support <= 1`?

Is `return 0;` a special id for opening and closing pairs?

Under which circumstances can  `structure_alphabet_type::pseudoknot_support <= 1` be true?

**Comment by joergi-w** [comment]
Thank you for asking this – I'm happy to make this more clear. Let me divide your question into two topics, **(1)** `pseudoknot_support` and **(2)** `pseudoknot_id`. 

**(1)** The `pseudoknot_support` variable is the maximum allowed depth of pseudoknots for the structure alphabet, i.e. the nestedness of brackets (in biology: loops). Value 1 means that the format supports just one bracket type `(`/`)`, so no pseudoknots. Any value > 1 says that there is support for pseudoknots. As it is a static class variable (e.g. 1 for dot_bracket, 22 for wuss51), the constexpr decision is valid. 

**(2)** The `pseudoknot_id` gives an identifier for each bracket type, which is 0 for `()`, 1 for `[]`, and so on... It is defined for types that support pseudoknots and should return id = 0, if there is just one bracket type. The value is std::nullopt (undefined), iff the structure letter does not represent a bracket, but an unpaired site.

With the explanations above at hand, I hope you understand the code snippet and agree that it is correct. The doxygen documentation for these are directly in the formats, e.g. check `wuss.hpp` lines 247-257. I was thinking that a User, who uses a certain alphabet, would firstly look here. As you couldn't find or understand it, would you suggest that I put it to a different location or should I write even more detailed text?

**Comment by marehr** [comment]
As discussed the line does not work:

```cpp
else if constexpr (is_pair_open() || is_pair_close()) 
```

**Comment by joergi-w** [comment]
fixed with PR #402
