### ISSUE TITLE
Gap Decorator Variants Benchmarked

### ISSUE THREAD

**Issue by mariehoffmann** [seqan/seqan3#382]
<body>
<header>
<h1 class="title">Benchmark Results for Gap Decorator Variants</h1>
</header>

Standalone code, results, plots, and more complete documentation are found in this git repo: [gap_decorators](https://github.com/mariehoffmann/seqan3_benchmarks/tree/master/gap_decorators)

<h1 id="the-approaches">The Approaches</h1>
<p>Three gap decorator variations were benchmarked against each other and against a sequence allowing regular <code>seqan3::dna15</code> letters and the <code>gap::GAP</code> symbol. Let’s denote with <span class="math inline"><em>n</em></span> the ungapped sequence length, <span class="math inline"><em>k</em></span> the number of gaps (not number of gap symbols!) and <span class="math inline"><em>m</em></span> the number of gap symbols.</p>
<ol>
<li><p><span><strong>Gapped Sequence</strong></span> An <code>std::vector</code> of type <code>gapped&lt;dna15&gt;</code> which grows and shrinks on direct insertion/deletion of gaps.</p>
<ul>
<li><p>Direct addressing</p></li>
<li><p>Overhead because of explicit gap character storage</p></li>
<li><p><code>dna</code> cast to wider data type <code>gapped&lt;dna&gt;</code></p></li>
</ul></li>
<li><p><span><strong>Gap vector</strong></span> Using a compressed bit vector of length <span class="math inline">|</span>sequence<span class="math inline">|</span> + # gaps</p>
<ul>
<li><p>Bit vector is <code>sdsl::sd_vector</code> with rank and select support structures with access time depending on the number of bits set.</p></li>
<li><p>Set bit indicates gap, else underlying sequence minus the rank</p></li>
<li><p>Bit vectors are not modifyable (except the <code>sdsl::int_vector</code>), hence any insertion or deletion operation results in a rebuilt with costs of <span class="math inline"><em>Θ</em>(<em>n</em>)</span></p></li>
</ul></li>
<li><p><span><strong>Anchor List</strong></span> Gaps are stored as anchors, i.e. a list of tuples with <span><strong>container-relative</strong></span> positions and lengths of gaps</p>
<ul>
<li><p>Insertion, deletion, and random access positions are virtual (=gapped sequence space), the anchor gaps have to be therefore accumulated to compute the virtual position</p></li>
</ul></li>
<li><p><span><strong>Anchor set</strong></span> A red-black tree stores the <span><strong>virtual</strong></span> anchor positions, an additional dictionary resolves the gap length for a given position.</p>
<ul>
<li><p>An <code>std::set</code><a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> is used for key management. The <code>std::set</code> does not allow handing over a lambda function for user-defined sorting. Therefore, key-value tuples which have to be sorted only by key cannot be used when one needs the guarantee of <span class="math inline">log<sub>2</sub>(<em>k</em>)</span> access time.</p></li>
<li><p>Associated gap lengths are stored in an <code>std::unordered_map</code> with constant access, but larger storage consumption.</p></li>
<li><p>To improve random access runtimes from <span class="math inline"><em>Θ</em>(<em>k</em>)</span> to <span class="math inline"><em>Θ</em>(log<sub>2</sub><em>k</em>)</span>, the gap lengths are stored in an accumulated fashion. To retrieve the actual gap length one substracts the accumulator of the preceeding gap.</p></li>
</ul></li>
</ol>

<table>
<caption>Theoretical runtimes and space consumptions with <span class="math inline"><em>k</em></span> = number of gaps, <span class="math inline"><em>m</em></span> = accumulated gap length, <span class="math inline"><em>n</em></span> = underlying (gap-free) sequence length.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Operation</strong></th>
<th style="text-align: left;"><strong>Gapped Sequence</strong></th>
<th style="text-align: left;"><strong>Gap Vector</strong></th>
<th style="text-align: left;"><strong>Anchor List</strong></th>
<th style="text-align: left;"><strong>Anchor Set</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>operator[]</code></td>
<td style="text-align: left;"><span class="math inline"><em>Θ</em>(1)</span></td>
<td style="text-align: left;"><span class="math inline">$\mathcal{O}(\log(\frac{n+m}{m}))$</span></td>
<td style="text-align: left;"><span class="math inline"><em>Θ</em>(<em>k</em>)</span></td>
<td style="text-align: left;"><span class="math inline"><em>Θ</em>(log<sub>2</sub><em>k</em>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>erase_gap</code></td>
<td style="text-align: left;"><span class="math inline"><em>Θ</em>(<em>n</em> + <em>m</em>)</span></td>
<td style="text-align: left;"><span class="math inline"><em>Θ</em>(<em>n</em> + <em>m</em>)</span></td>
<td style="text-align: left;"><span class="math inline"><em>Θ</em>(<em>k</em>)</span></td>
<td style="text-align: left;"><span class="math inline"><em>Θ</em>(log<sub>2</sub><em>k</em>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>insert_gap</code></td>
<td style="text-align: left;"><span class="math inline"><em>Θ</em>(<em>n</em> + <em>m</em>)</span></td>
<td style="text-align: left;"><span class="math inline"><em>Θ</em>(<em>n</em> + <em>m</em>)</span></td>
<td style="text-align: left;"><span class="math inline"><em>Θ</em>(<em>k</em>)</span></td>
<td style="text-align: left;"><span class="math inline"><em>Θ</em>(log<sub>2</sub><em>k</em>)</span></td>
</tr>
</tbody>
</table>

<h1 id="benchmark-results">Benchmark Results</h1>
<p>To create realistic gapped sequences or gaps for insertion, gap lengths are sampled from a histogram distribution published by Goonesekere et al. <a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> for each position, which results in a rather dense distribution of short gaps (40%-45% gap proportion). After sampling the ‘‘gapped’’ sequences were resized to have total sequence size of <span class="math inline">2<sup><em>i</em></sup></span>. All four data structures are then initialized with the same gap vector within the same experiment. Each experiment is repeated 32 times for sequences with lengths in range <span class="math inline">[2, 2<sup>2</sup>, ..., 2<sup>15</sup>]</span>, and 8 times for lengths in range <span class="math inline">[2<sup>16</sup>, ..., 2<sup>18</sup>]</span>. The benchmarks cover three user scenarios:</p>
<dl>
<dt>Benchmark 1</dt>
<dd>
<p>
Read-only on ungapped or gapped sequence. Left plot: Read-only on ungapped sequence, i.e. gap structures are empty. Right: Read-only on gapped sequence.
</p>
</dd>
<dt>Benchmark 2</dt>
<dd><p>
Insert/Delete at <span><strong>random positions</strong></span> into ungapped or gapped sequence.  Left plot: Insert and delete at random positions into ungapped sequence. Right: Insert and delete at random positions into gapped sequence." /><figcaption>Left: Insert and delete at random positions into ungapped sequence. Right: Insert and delete at random positions into gapped sequence.
</p>
</dd>
<dt>Benchmark 3</dt>
<dd><p>Insert/Delete from <span><strong>left to right</strong></span> into ungapped or gapped sequence. Left plot: Insert and delete from left to right into an ungapped sequence. Right: Insert and delete from left to right into a gapped sequence." /><figcaption>Left: Insert and delete from left to right into an ungapped sequence. Right: Insert and delete from left to right into a gapped sequence.</p>
</dd>
</dl>

![benchmark1_plot](https://user-images.githubusercontent.com/4982274/44401064-a5f28780-a54d-11e8-9f0f-e7322036f6e7.png) 
![benchmark2_plot](https://user-images.githubusercontent.com/4982274/44401065-a5f28780-a54d-11e8-8554-9b3706fc9c19.png)
![benchmark3_plot](https://user-images.githubusercontent.com/4982274/44401066-a5f28780-a54d-11e8-910f-68503594f47e.png)

<h1 id="summary">Summary</h1>
<h2 id="results">Results</h2>
<ul>
<li><p>The gapped sequence (<code>gapped&lt;dna15&gt;</code>) always outperforms the other approaches, except when gaps are inserted from left to right into an empty sequence (see Benchmark 3). In this case the Anchor List approach is always faster, and the Anchor Set approach when sequence lengths exceeds <span class="math inline">2<sup>12</sup></span>.</p></li>
<li><p>The Gap Vector (<code>sdsl::sd_vector</code>) never outperforms the three other approaches, but should be considered to be provided in SeqAn3 when only read operations are performed and a transformation to a <code>gapped</code> sequence is undesirable.</p></li>
<li><p>When comparing anchor list versus anchor set for Benchmark 1 the anchor set outperforms the anchor list for sequence lengths exceeding <span class="math inline">2<sup>12</sup></span>. However, both approaches are outperformed by the gap vector. For Benchmark 2 (insert/delete at random position) and Benchmark 3 (insert/delete from left to right) the anchor list always outperforms the anchor set.</p></li>
</ul>
<h2 id="recommendations">Recommendations</h2>

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Usecase</strong></th>
<th style="text-align: left;"><strong>Data Structure</strong></th>
<th style="text-align: left;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Read-Only</td>
<td style="text-align: left;">Gap Vector or Gapped Sequence</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Ins/Del at Random Position into <span><strong>Ungapped</strong></span> Sequence</td>
<td style="text-align: left;">Anchor List</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ins/Del at Random Position into <span><strong>Gapped</strong></span> Sequence</td>
<td style="text-align: left;">Anchor List or Gapped Sequence</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Ins/Del Left to Right into <span><strong>Ungapped</strong></span> Sequence</td>
<td style="text-align: left;">Anchor List</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ins/Del Left to Right into <span><strong>Gapped</strong></span> Sequence</td>
<td style="text-align: left;">Anchor List or Gapped Sequence</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<section class="footnotes">
<hr />
<ol>
<li id="fn1"><p>which is implemented via a red-black tree<a href="#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>see Table 1 in <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC419611/" class="uri">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC419611/</a>, columns were summed up and normalized<a href="#fnref2" class="footnote-back">↩</a></p></li>
</ol>
</section>
</body>
</html>

**Comment by mariehoffmann** [comment]
@rrahn and @h-2: despite the theoretical runtimes for lookup, insert, delete for the anchor set are Theta(log(k)) compared to Theta(k) of the anchor list, in practice, the anchor set is only for reading in large sequences faster than the more simple anchor list approach. Do you have an idea why? The code can be found in my repo (see link at the top of this page).

**Comment by marehr** [comment]
Thank you for your really detailed analysis.

```cpp
                t1 = std::chrono::high_resolution_clock::now();
                [[maybe_unused]] auto val_as = as[pos];
                t2 = std::chrono::high_resolution_clock::now();
                durations[AS][round*R + j] = std::chrono::duration_cast<std::chrono::nanoseconds>(t2 - t1).count();
```

Looking at the benchmark, I would think that the invocation `[[maybe_unused]] auto val_as = as[pos];` gets optimized away, since the result is not stored anywhere. In google benchmark there is a function called [benchmark::DoNotOptimize](https://github.com/google/benchmark#preventing-optimisation) that tries to mitigate this.

**Comment by h-2** [comment]
Wow, thanks for this exenstive analysis!

Concerning benchmark 3: Am I correct that he underlying sequence is already there and it is just the gaps that are being inserted left to right?

have you tried using an sdsl `bit_vector` instead of the `sd_vector`? It should have similar run-time to the `std::vector<gapped<>>` but still be smaller.

Concerning the table: Could you add logarithmic space complexity, too? I am assuming

| vector   | sd_vector    | set    | set+map    |
| -- | ---- | -- | -- |
| `O(m+n)`   | `O(m * log((n+m)/m))` | `O(k)` | `O(k)` |

is that correct roughly? Can you benchmark the actual size overhead?

**Comment by h-2** [comment]
@marehr DoNotOptimize is not ideal either, because then it doesnt optimise at all, I think. A safer way is to add the return value onto a counter and read the counter at the end. Adding of course costs something, too, but you can assume the same overhead for all your runs.

**Comment by mariehoffmann** [comment]
The space complexity is in the pdf linked at the top of the page (somehow it could not be rendered from LaTeX to html/md). More precisely it would be: 
![screen shot 2018-08-21 at 17 08 40](https://user-images.githubusercontent.com/4982274/44410531-e6a9cb00-a564-11e8-9c9f-ae88e09ee57c.png)
The cast from a, e.g. compressed `dna4` to `gapped<dna4>` could be expensive, that's why I took it into account.
In all three benchmarks there are actually 2 cases tested: operation on an ungapped sequence (left), operation on a gapped sequence (right). The underlying sequence is always there and resized before measurements start.
@h-2 I would then re-run the benchmarks and use the return value as you proposed to avoid optimization. Initially, I used the `bit_vector`, but due to the smaller space consumption of the `sd_vector` it was decided to take this one instead. But I can benchmark a 2nd bit vector version.

**Comment by h-2** [comment]
> More precisely it would be:

Where does the `n` factor come from in the three right cells? Is that the original sequence? Can you give it without the original? I think including it gives an unfair advantage to the gapped_sequence as usually you have you sequence data extra and independent of the alignment.

> The cast from a, e.g. compressed dna4 to gapped<dna4> could be expensive, that's why I took it into account.

Yep, that's good.

> In all three benchmarks there are actually 2 cases tested: operation on an ungapped sequence (left), operation on a gapped sequence (right). The underlying sequence is always there and resized before measurements start.

:+1: 

> @h-2 I would then re-run the benchmarks and use the return value as you proposed to avoid optimization. Initially, I used the bit_vector, but due to the smaller space consumption of the sd_vector it was decided to take this one instead. But I can benchmark a 2nd bit vector version.

Yeah, originally I didn't think the gapped_sequence would be so much better than the sd_vector so I wouldn't have started with it either. But now I think it would be great to test, because it might just be comparable in speed, but smaller. If it is easy to add more types to your test, could you also give `bitcompressed_vector<gapped<dna4>>` a try?

And like I said, actual measurements for the size might be useful, too. [Now that you have done such a good job on the benchmarks, we might as well do all the stuff ;-) ]

**Comment by mariehoffmann** [comment]
@h-2 Could you give an advice of how to benchmark actual space consumtions?

**Comment by h-2** [comment]
> @h-2 Could you give an advice of how to benchmark actual space consumtions?

You can prefix the command on the command line with `/usr/bin/time -f '%M RAM %E time'` (linux) or `/usr/bin/time -l` (FreeBSD and macOS) this will give you the maximum amount of ram used during the time the program ran.  But that will only work if your benchmarks are isolated into individual runs.

More fine-grained analysis can be made via [massif](http://valgrind.org/docs/manual/ms-manual.html)

**Comment by mariehoffmann** [comment]
I am currently utilizing `valgrind --tool=massif`. I assume the heap profiling should be also keyed by sequence length. There is now a Python script generating the actual source files for avoiding cpy-paste errors and making adding of new test cases easy. For each of the 3 benchmarks 5*3*2*|sequence lengths| (5 gap decorators, 3 alphabet types, 2 sequence states, i.e. ungapped or already gapped) `cpp` files will be generated, run, and evaluated.

**Comment by h-2** [comment]
Cool!

just in case you hadn't noticed: massif affects the run-time strongly so you need to do run-time and memory tests separately. If you already generate separate tests anyway, `/usr/bin/time` might be easier. In any case the important memory value is the "maximum resident set size".

**Comment by rrahn** [comment]
Sorry for adding so late to this conversation. In general the evaluation is very thorough already, but we will have certain use cases in particular that we need to adress:

 #. Gaps are mostly inserted in one direction after computing the alignment. In this case we would always use the most effcient approach, which is inserting them from left to right (This gives a strong benefit for anchor lists over anchor sets). 
 #. When we deal with gaps we are mostly interested in the positions of the gaps. So we need efficient conversions from a source position to the corresponding gap positions and vice versa. I believe that the vector approach is the fastest due to rank/select support, but for smaller sequences it will compete with anchor sets. The gapped sequence would be linear. 

We have a SeqAn book and there are some benchmarks. It also includes the anchor set approach. Maybe we can also include these benchmarks.

**Comment by mariehoffmann** [comment]
The anchor list version that I implemented addresses this issue in the following way: 

- the classical anchor list data structure stores relative gap positions (relative to the underlying, ungapped sequence) and their lengths
- `insert_gap` consistently throughout all implementations is expected to receive a virtual position (i.e. position relative to the gapped sequence)
- using the classical approach, insertion is done in theta (k) where k is the number of gaps (not gap symbols). Note: binary search doesn't work, since gap lengths need to be accumulated to determine the relative anchor position.
- therefore, I use **virtual anchor positions** which has to be paid with higher costs for insertion/deletion at random position (tailing gap positions need to be updated)
- this is optimal when inserting from left to right: binary search is applicable and no tailing gaps to update

The plot below (left) shows the runtimes of **insertion from left to right** into an a) empty sequence (top) and b) into a gapped sequence (bottom). For case a) AL (anchor list) and GS (baseline, i.e. vector of type gapped<alphabet> storing gaps and letters in same sequence) are the best and in case b) anchor list is still the best out of all approach that do not modify the underlying sequence. Same is true for random insertion (plot not shown).
**But** when combined with many read operations, the performance suffers: for larger sequence lengths the reading runtimes for AL are the worst (2nd plot, bottom left).
This is what I did meanwhile and what I'm working on: 

1. Improvement of the anchor set approach by using one data structure with constant random access and log(k) lower_bound for storing gaps (instead of key set and gap lengths dictionary) making it more competitive to the anchor list approach (not yet in plot below).
2. Implementing a new anchor list variant with block-wise gap statistics as proposed by Hannes
   * classical anchor list with relative gap positions
   * block-wise accumulated gap lengths, which reduces gap updates to theta(#blocks) compared to the anchor set approach, but will also make it necessary to accumulate gap lengths block-wise for read operations.
   * it's a trade-off between the classical anchor list (non-aggregative, relative positions) and the anchor set (aggregated gaps, virtual positions).

![b3](https://user-images.githubusercontent.com/4982274/48776922-7a5c7600-ecd1-11e8-80aa-7ae2500a66ed.png)
![b1](https://user-images.githubusercontent.com/4982274/48776933-7fb9c080-ecd1-11e8-8772-de2413b3b63a.png)

legend: AL = anchor list, AS = anchor set, GS = std::vector<gapped<dna>>, GVbit = sdsl::bit_vector of length (#gap_symbols + |sequence|), GVsd = sdsl::vector_sd

**Comment by rrahn** [comment]
Ok in the following consence and with the pressure to get the alignment module ready, I am proposing to stick with the anchor set for the moment. 
It seems the easises way to implement and it would give us for the majority of situations good performance. We can then still revisit a more efficient implementation, when we realize that they become the bottleneck in the code, which I consider highly doubful.

**Comment by mariehoffmann** [comment]
Just a remark, all approaches implement all operators and are tested to exhaustion through randomized gap insertion and erasure :) Hence, there is not much to do to adjust the code to match the concepts and style guide.

**Comment by mariehoffmann** [comment]
# Update of Benchmark Runtimes
Can't get enough, here are more benchmark plots with sequence lengths in [2^i] for i in range [3:18]! 
What's new/different: 

- Anchor Set is using a single data structure now for gap storage which improves the practical runtime a lot
- Added a new approach: block-wise gaps are accumulated, but within a block anchor gaps are stored
  - for random access, one first forwards by accumulating the block sums, when arriving at the designated block, one iterates over the gaps stored by the designated block. Average access time with b denoting the number of blocks and k the total number of contiguous gaps: O(b + k/b))
  - it's open how much the optimal block width corresponds to the sequence length; for a length of 2^10, the optimal block width is 32
- Very large sequence lengths are now also included

To sum it up: Anchor List and Anchor Set are the best general-purpose data structures for storing/computing an alignment. The Anchor Block approach beats the others when gap density is high and lots of insert/erase operations are done and the sequence length exceeds 2^10. Also there is some margin for optimizing block width towards sequence length, so runtimes might be even better. 
For the special case that only read operations on an aligned sequence are performed: Gap Vector with an sdsl::bit_vector is the best choice.

## Benchmark 1 - Read-Only
left: read on gap-free sequence, right: read on gapped sequence (about 40% gap symbols)
![b1_legend](https://user-images.githubusercontent.com/4982274/50226463-8b1d0c00-03a3-11e9-8a0e-a327ed85d72f.png)

## Benchmark 2 - Insert/Erase on Random Position
left: insert + erase on initially empty sequence, right: insert + erase on already filled sequence. Note that after gap insert, gap erasure on the same gap is performed, but with a smaller size value, s.t. the gap is not completely erased.
![b2_legend](https://user-images.githubusercontent.com/4982274/50226714-35952f00-03a4-11e9-9dbb-21814eb8e794.png)

## Benchmark 3 - Insert/Erase from Left to Right
left: insert + erase on initially empty sequence, right: insert + erase on already filled sequence. Same erasure behavior as described for benchmark 2.
![b3_legend](https://user-images.githubusercontent.com/4982274/50226764-58274800-03a4-11e9-85ce-33d002a6e027.png)

## Recommendations

|   Use Case |  Initially Empty |  Initially Filled  |
|:-:|---|---|
|  Read-Only |  Anchor Set, Anchor List |  Gap Vector bit  | 
| Insert/Erase at Random Index  |  Anchor List |   Anchor List (n <= 2^10), Anchor Block (n > 2^10)| 
|  Insert/Erase from Left to Right  |  Anchor List  | Anchor List (n <= 2^9), Anchor Block (n > 2^9)   |

**Comment by h-2** [comment]
@mariehoffmann  Now that the first decorator is merged, can you prioritise getting benchmarks into our benchmark suite? They may not produce as pretty graphs, but it is essential that we have this integrated with the rest of the benchmarks.

**Comment by mariehoffmann** [comment]
Yes, I will add a benchmark to the suite in seqan3. Based on the newer benchmark results containing the *anchor block* approach, i.e. fix a block_width within gaps are physically anchored and use an accumulated sum over the gap lengths stored at each block, we definitely should include this approach, too. See Figure below. **AB** refers to non accumulated block statistics and **AB2** to the accumulated version which allows binary search to identify the block to which a random index is pointing to.

**Comment by mariehoffmann** [comment]
- AB: anchor blocks, like anchor list approach but, gaps grouped together block-wise. Blocks have a fixed with w.r.t. to the positions in the unaligned sequence. Gaps are stored as anchors. A list of lengths sequence_length/block_width + 1 stores the gap lengths accumulated per block. Random access is performed in two steps: first locate block (linearly), the locate lower bounding gap within that block if present.
- AB2: same as AB, but block sums are accumulated. Hence, first location step is in log_2 (num_blocks).
- AS: anchor set, use a set of gap structures storing virtual anchor positions and accumulated gap length. Internally, gcc uses a red-black tree allowing binary search and efficient iteration. Gap length of  leave node is computed by substracting the accumulated gap sum from its predecessor. 
- GS: baseline, i.e. use std::vector of type `gapped<dnaX>`. Direct insertion, sequence grows.
- AL: traditional approach with a single list storing anchors as relative (to sequence) addresses and gap length.
- GVbit: use a bit vector to indicate gap and non-gap position in virtual sequence. Make use of rank and select functionalities to convert between virtual and physical addresses.
- GVsd: use bit vector sd with different helper functions (see sdsl).

### Benchmark 1
**Left**: Read on empty ungapped sequence. **Right**: read in gapped sequence (about 40% of the aligned sequence are gap symbols). Note that for **GS** using a `sdsl::bit_vector` the benchmark was abortet for sequence lengths above 2^18, that's why there are no results for benchmark 1.
![out_1_32_3_20](https://user-images.githubusercontent.com/4982274/52914464-cb780800-32c8-11e9-9f8a-1d7b81f9c89f.png)

### Benchmark 2
**Left**: Insert/delete at random positions into *ungapped* sequence. **Right**: Insert/delete gaps at random positions into *gapped* sequence.
![out_2_32_3_18](https://user-images.githubusercontent.com/4982274/52914344-6e2f8700-32c7-11e9-907f-a991378f6dc3.png)

### Benchmark 3
**Left**: Insert/delete from left to right into *ungapped* sequence. **Right**: Insert/delete gaps from left to right into *gapped* sequence.

![out_2_32_3_18](https://user-images.githubusercontent.com/4982274/52914463-c2873680-32c8-11e9-9898-70160a15665e.png)

**Comment by h-2** [comment]
turned into car https://github.com/seqan/seqan3/projects/10#card-27119202
