### ISSUE TITLE
argument_parser requires const char ** argv

### ISSUE THREAD

**Issue by joshuak94** [seqan/seqan3#388]
The argument_parser initialization requires a const char ** argv option, instead of just a char ** argv.

https://github.com/seqan/seqan3/blob/9b81a6c8403c5b79d4a6163dc6256c22f293ca48/include/seqan3/argument_parser/argument_parser.hpp#L212-L216

**Comment by eseiler** [comment]
Independent of whether it should be `const char **` or `char **`, the [snippet](http://docs.seqan.de/seqan/3.0.0-master-user/classseqan3_1_1argument__parser.html) doesn't work the way it is.
Instead of
```cpp
int main(int argc, char ** argv)
```
You need to use
```cpp
int main(int argc, const char ** argv) // or
int main(int argc, char const *argv[])
```
