### ISSUE TITLE
Quality alphabet TODOs

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#39]
I thought about the name `illumina18` again, and I think it is confusing, because for the other alphabets the number in the end denotes the size. Also the current `illumina18` can also represent the original Sanger qualities.

I would therefore propose:

  * `phred42`:
    * rename of the current `illumina18`
    * phred_type should be changed to uint8_t since it is only positive
    * documentation should indicate that it can represent illumina >= 1.8 and original sanger
    * phred range is `[0, 41]` (hence "phred42")
    * values larger than 41 should be mapped to 41, also assert values not larger than 62
    * offset_phred can be removed

  * `phred63`:
    * same as `phred42`
    * except that phred range is `[0, 62]` (hence "phred63")
    * only assert values not larger than 62

  * `phred68legacy`:
    * same as `phred63`
    * except that phred range is `[-5, 62]` (hence "phred68")
    * phred_type is int8_t
    * offset_phred is -5
    * assert that assigned values not larger than 62 and not smaller than -5
    * document that this is for solexa and illumina < 1.8

Also, maybe we can add a small documentation overview to `alphabet/quality.hpp` that explains the differences...

**Comment by h-2** [comment]
@mariehoffmann What do you think about these points? Would you be willing to do this? I think it's mostly copy'n'paste of existing code and updating some minor things to the current documentation standard...

**Comment by mariehoffmann** [comment]
ok.

**Comment by marehr** [comment]
Is this done?

**Comment by h-2** [comment]
@marehr no, it's still open.

**Comment by h-2** [comment]
* [ ] rename `quality_composition<>` to `qualified<>` to be consistend with `gapped<>` and `masked<>`
* [ ] mark `qualified<>` as implementing `quality_concept`
