### ISSUE TITLE
[Sequence IO] Does fastq check if sequence and qual have the same length?

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#407]
This should at least give a debug assertion if not.

**Comment by MitraDarja** [comment]
I am not sure but I think different lengths in reading will throw an error here:

https://github.com/seqan/seqan3/blob/87affac82c095ab5e15410900723d0a9205dd5fa/include/seqan3/io/sequence/sequence_file_format_fastq.hpp#L213

**Comment by smehringer** [comment]
> I am not sure but I think different lengths in reading will throw an error here:
https://github.com/seqan/seqan3/blob/87affac82c095ab5e15410900723d0a9205dd5fa/include/seqan3/io/sequence/sequence_file_format_fastq.hpp#L213

I think you are right but maybe only at the end of the file if there are no more characters to read. If there is the next id it will just read that and then fail as @eseiler mentioned 

> Therefore it _should_ fail with, e.g.
https://github.com/seqan/seqan3/blob/87affac82c095ab5e15410900723d0a9205dd5fa/include/seqan3/io/sequence/sequence_file_format_fastq.hpp#L155

@h-2 is this intendent behaviour ? Or should we change line 213
from 
```cpp
auto qview = stream_view | ranges::view::remove_if(is_space)                  // this consumes trailing newline
                         | view::take_exactly_or_throw(sequence_size_after - sequence_size_before);
```
to
```cpp
auto qview = stream_view | ranges::view::remove_if(is_space)                  // this consumes trailing newline
                         | view::take_until_or_throw(is_char<'@'>)
                         | view::take_exactly_or_throw(sequence_size_after - sequence_size_before);
```
?

**Comment by rrahn** [comment]
Well, but in you last example a too long quality string would be silently ignored, which would be an error as it is against the specification of the format. 
So in the current version it could accidentally happen that a complete sequence might be consumed (very very unlikely, but not impossible) and the parser would never notice. Like if the difference between the size of the quality string is exactly the number of bytes until the after next sequence is read. 
So the correct version would be:

```cpp
auto qview = stream_view | ranges::view::remove_if(is_space)                  // this consumes trailing newline
                         | view::take_until_or_throw(is_char<'@'>);
// copy qview into qualities 
if (sequence.size() != qualities.size()) 
    throw ...
```

**Comment by smehringer** [comment]
I think this is deliberately done like this (allowing for longer quality sequences) as to not enforce correct input as strict as correct output. @h-2 ?

**Comment by rrahn** [comment]
I think it shouldn't. I mean what would be the assumption? Are there artificial trailing characters, or rather leading once? Or maybe something was inserted inbetween? Maybe the sequence was altered and not the qualities. So in any case, the file format is corrupted and should be signaled as such.

**Comment by h-2** [comment]
> Reading will consume as many characters as the sequence is long, including the next lines.

The only thing that needs to be done here is check for validity of the read characters. That will throw on newlines if the sequence is to short.

**Comment by rrahn** [comment]
What is the state for this? Is there a test for this? And is the current outcome a problem or wrong?

**Comment by rrahn** [comment]
I am closing this since no one is responding so I assume this is fixed.
