### ISSUE TITLE
Retrieving data from a configuration object

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan3#411]
1. It seems that I cannot retrieve a value when only one configuration object is set:

```
auto const cfg = search_cfg::max_error(1) | search_cfg::strata(1);
seqan3::get<search_cfg::id::max_error>(cfg); // works

auto const cfg2 = search_cfg::max_error(1);
seqan3::get<search_cfg::id::max_error>(cfg2); // fails
```

error message:
```
candidate: template<seqan3::search_cfg::id e, class ... cfg_elements_t> constexpr const auto& seqan3::get(const seqan3::detail::configuration<configs_t ...>&)
 constexpr auto const & get(detail::configuration<cfg_elements_t...> const & cfg) noexcept

note:   template argument deduction/substitution failed:
note:   ‘const seqan3::detail::configuration_fn_proxy<seqan3::detail::search_config_max_error_adaptor, int>’ is not derived from ‘const seqan3::detail::configuration<configs_t ...>’
```

Might I be doing something wrong or is it possible that a single configuration object that is not combined with any other has not been considered? The code for `seqan3::get()` was copied from the alignment module.

2. How can we check whether a configuration value has been set in the object or not?

Before retrieving it with `seqan3::get<id::foo>(cfg)` I need to check its existance before running in a static_assert. I implemented my own `seqan3::contains<id::foo>(cfg)` but was wondering whether it already exists and I overlooked it.

**Comment by rrahn** [comment]
Well, as my last post suggests, within the interface you would trigger the conversion implicitly. The only agreeable point is, that users might change the state of the config after they set it. But this would not work. Likewise a view adaptor or a view adaptor proxy Is not iterable. I know that this has a certain design flaw. My initial thought was to have configuration object as the start of any configuration expression, but it was voted down. For the moment we have to leave it like this and document it properly. We might find a solution in the future

**Comment by cpockrandt** [comment]
> For the intended use within the algorithm, you probably assume some default configurations? For this I will have a preconfigured config that replaces the defaults with the user configuration passed to the algorithm before I enter the algorithm that assumes that certain configs are given.

I understand your approach, but I don't think it works for me. Some of the configuration objects are flags (i.e. configuration objects that do not take any parameters, not even a boolean value to explicitly unset it, which you do I guess). This way I make sure that I know at compile-time whether they are set or not without having to create multiple code paths. And to be honest I'm not a fan of `foo(as_c<true>)`

Furthermore some of these flags are mutually exlusive, i.e. I cannot have a default configuration that sets these flags to false and override them with the user values.

No biggi, I just wanted to check whether we already have a way to check for this. :bowtie:

**Comment by rrahn** [comment]
And btw, it is not in the current code base, but of course we will have has_config function that is constexpr.
