### ISSUE TITLE
Doxygen warnings on std::ranges::OutputRange

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan3#418]
Running doxygen currently outputs these two warnings on the master branch:

    Generating docs for file seq/.../seqan3/include/seqan3/range/all.hpp:62: warning: unable to resolve link to `std::ranges::OutputRange' for \link command
    .../seqan3/include/seqan3/range/all.hpp:103: warning: unable to resolve link to `std::ranges::OutputRange' for \link command

**Comment by eseiler** [comment]
Can you pull the current master branch of [seqan3-infrastructure](https://github.com/seqan/seqan3-infrastructure) and try again?

The `include/seqan3/std/ranges` file which defines std::ranges::OutputRange has no extension and therefore is not parsed by doxygen unless you tell it explicitly to do so.
The current master of seqan3-infrastructure does this and I do not get this warning.
