### ISSUE TITLE
Alignment/Search Configuration Docs

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan3#423]
I built the user documentation and realised that the documentation is very sparse for the configuration objects since everything is in the detail namespace. Basically the user only gets a list of configuration objects **without** details such as parameters.

Is the documentation still work in progress or shall we write information such as parameters into the documentation ourselves (without doxygen checking consistency)?

Minor sidemark: It seems you can't do

```
/*!\defgroup configuration Configuration
 * \brief ...
 * \ingroup alignment
```

If I do the same and add it to the group `search` both configurations (alignment and search) will be merged into both groups. Maybe name them alignment_configuration?

**Comment by rrahn** [comment]
The configuration is now part of the public API, so it can be documented properly.
