### ISSUE TITLE
[DOC] snippets should be copy and pastable.

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#425]
a lot of our snippets in the documentation do not include the `#include ..` and `using namespace seqan3::literal` etc. so the inexperienced user will have problems to use them easily.

**Comment by marehr** [comment]
Interesting that there is nothing in our wiki https://github.com/seqan/seqan3/wiki/Writing-Documentation

For structs / classes:
* I agree that the main snippet at the top of a class/struct should be completely copy & pastable.
* But, each function of a class should be as minimal as possible

I'm not so sure for (free) functions. 

```c++
/*! ... Good landing page
 * complete snippet with include / using namespace / and main
 */
struct foo
{
   // short snippet what bar does
   // sort({4,3,2,1}) // returns {1,2,3,4}
   void sort();
};

```

**Comment by marehr** [comment]
Apparently, #83 had the task:

> add a section to https://github.com/seqan/seqan3/wiki/Writing-Documentation titled **Including example code snippets** that explains how to use snippets and that people should prefer to use snippets from existing test-cases and if that is not feasible add the code to separate files under `test/snippet`.

I think we should discuss here, what we want to write as guide.

**Comment by marehr** [comment]
History always repeats itself and there is a newer issue #837 with a more active discussion. We can reopen this if it is not superseded by #837.
