### ISSUE TITLE
loosen alphabet_concept requirements?

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#444]
Although it makes sense to design alphabets as trivial types and standard-layout-types, I am no longer sure that we should require this. Especially when dealing with external datatypes it is really difficult to ensure triviality.

In fact I am deactivating the trivial requirement now, because of dealing with SDSL-types. 

We need to re-evaluate this after the workshops.

**Comment by marehr** [comment]
> In fact I am deactivating the trivial requirement now, because of dealing with SDSL-types.

Can you give an example where we use sdsl-types as alphabets?

**Comment by h-2** [comment]
we use sdsl::int_vector_reference inside the proxy type returned by bitcompressed_vector and I assume we will have more of this when mergen the gap_adaptors.

**Comment by h-2** [comment]
(having a non-trivial type inside your alphabet also makes it non-trivial)

**Comment by h-2** [comment]
Sure it is convertible, but that doesnt help when you have constrained type deduction and you can't infer which concrete alphabet it would be convertible to.

**Comment by h-2** [comment]
changed via #535
