### ISSUE TITLE
Warn in cmake if performance tests are build in debug mode

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan3#450]
Running cmake without any arguments and building a performance test gives a warning that the library was built in DEBUG mode. Shouldn't we alter the CMakeLists.txt for performance tests to build in release mode by default? I don't see any reason why we ever want to build it in debug mode. This would make it a tiny bit easier for users. :smiley: 

    cmake ../../seqan3/test/performance
    make example_benchmark
    ./example/example_benchmark

***WARNING*** Library was built as DEBUG. Timings may be affected.

**Comment by marehr** [comment]
I think this is a documentation issue, I would prefer not to do wonkey default cmake settings.

Everyone who uses cmake knows that he has to build with `-DCMAKE_BUILD_TYPE=Release`.

We could add a warning to `CMakeLists.txt` which says 

> please use `cmake -DCMAKE_BUILD_TYPE=Release <path> ` if you want to have the best performance

**Comment by h-2** [comment]
I agree with Marcel that this is up to cmake. But I think we can add a diagnostic to platform.hpp that prints something like "Attention: you are building with debugging/without optimisations." When NDEBUG is not defined.

**Comment by cpockrandt** [comment]
I agree. Then let's introduce a warning in cmake :+1:

**Comment by smehringer** [comment]
When I compile in debug mode there already is a warning :eyes:

**Comment by marehr** [comment]
Can you paste the output?

**Comment by cpockrandt** [comment]
But we're talking about the cmake output not about the compiler/runtime output, aren't we?

**Comment by smehringer** [comment]
> But we're talking about the cmake output not about the compiler/runtime output, aren't we?

ah sorry. I meant the runtime output. But if we have a runtime warning why do we want an extra cmake warning ?

**Comment by rrahn** [comment]
If somone is willing to do this please, but this has absolutely no priority right now.
