### ISSUE TITLE
alignment_file issues

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#457]
Some of these will make the tutorial harder so it would be nice if you could look at them asap:

  * `alignment_file_output` and `alignment_file_output_options` are not part of the `alignment_file` module in the documentation
  * compare_aligned_values and get_cigar_string are not in detail as planned; constraints for get_cigar_string are not guarded
  * write_range constraints are not guarded
  * sam_format and alignment_file_output protected sections are not marked as private although it is detail

**Comment by marehr** [comment]
on recent doxygen version:

```
include/seqan3/io/alignment_file/output.hpp:617: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
```

**Comment by smehringer** [comment]
> * compare_aligned_values and get_cigar_string are not in detail as planned; constraints for get_cigar_string are not guarded

[Yes they are?](https://github.com/seqan/seqan3/blob/master/include/seqan3/io/alignment_file/detail.hpp#L51)

**Comment by h-2** [comment]
> Yes they are?

That's up for you to discuss with doxygen:
http://docs.seqan.de/seqan/3.0.0-master-user/group__alignment__file.html

**Comment by smehringer** [comment]
:scream: But why? its in the seqan::detail namespace
