### ISSUE TITLE
Search module issues

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan3#465]
**SeqAn**

* [x] (DOC) Move configuration group into algorithm submodule
* [ ] (DOC) Finish documentation for Index and write documentation for search module (#638)
* [ ] (API) Make `mode()` a runtime decision
* [x] (API) arbitrary order and subset of `max_error` and `max_error_rate` parameters
* [ ] (API) delegate
* [ ] (FEATURE) Strata mode
* [x] (FEATURE) Optimum Search Schemes
* [x] (BUG) see #473 
* [x] (BUG) see #482
* [x] Wiki page: Introduction to the search module and diff of important search scheme algorithm changes to SeqAn2 (because commits have been squashed)

**SDSL**

* [ ] (API) Let SDSL take any range on numeric elements for index construction, not only int_vector or C arrays
* [ ] (FEATURE) Reduce memory peak for index construction
* [ ] (FEATURE) Support string collections (range of ranges)
        - flatten the string collection using a view (without introducing sentinels)
        - in locate() and lazy_locate() recompute the positions by either using a vector of accumulated begin positions of the sequences or a sparse bitvector with select support (this can be further optimized by sorting the occurrences in locate() and improving the binary search in the begin positions while streaming over the sorted occurrences)
        - there are no adaptions necessary for the SDSL and the space consumption is optimal compared to storing tuples in the suffix array itself (seq nbr., seq pos.)
* [ ] (FEATURE) EPR dictionaries

**Comment by joshuak94** [comment]
There's also a failed test in GCC8, mentioned in #494. I'm not sure if it's the same issue as was mentioned in previous posts.

**Comment by smehringer** [comment]
Points moved to issues and cards in project kanban.
