### ISSUE TITLE
[Doxygen] Improve API search

### ISSUE THREAD

**Issue by tloka** [seqan/seqan3#468]
Currently, the API only preforms prefix search.
It should find all occurrences, also when a match occurs in the middle.

----------

Current behavior:
```
Search: validator
>> validator_concept
>> validator.hpp
```

Expected behavior:
```
Search: validator
>> file_ext_validator  // expected match that is currently not found
>> validator_concept
>> validator.hpp
[...]
```

**Comment by h-2** [comment]
But doesn't it so prefix search on each suffix, effectively searching every position?

**Comment by eseiler** [comment]
Nah, just the prefix. If it would search every suffix for the prefix, it would be fine :D
By [default](https://www.stack.nl/~dimitri/doxygen/manual/searching.html) doxygen uses client side searching which does not provide "full text search" (and that probably also means not searching for a prefix match with any suffix). 
Server side search allows for full text search.
