### ISSUE TITLE
Explicit vector<dna5> and auto query strings produce different search() results

### ISSUE THREAD

**Issue by wtwhite** [seqan/seqan3#473]
Attention: @marehr (I hope this is the Marcel I investigated this with yesterday afternoon!)

Put query.fastq and reference.fasta from https://github.com/eseiler/SeqAn3_read_mapper/blob/master/ in the current directory, compile the following gist https://gist.github.com/wtwhite/66ce494a25d88155afb05ce5ba5ecc4e, and run the following command:

    ./mapper reference.fasta query.fastq output.txt > stdout 2> stderr

The main output, which is written to the file stderr, will be different if line 51 (marked `// (1)`) is commented out and line 52 (marked `// (2)`) is uncommented, though it seems clear that it should be the same.  (Note: nothing is actually written to output.txt, and very little is written to stdout.)  From looking at a page or so of diffed output, it seems that the original version reports a superset of the hits reported by the second.  The first hit found by the first version but not by the second is for read 2; manual inspection shows that this read does in fact align with a single mismatch at this position in the reference (well under the default error threshold of 42), so the error is with the second version.

**Comment by marehr** [comment]
@cpockrandt Can you look into this problem?

**Comment by eseiler** [comment]
This should be fixed now and the example produces the same output for me with the current master.
