### ISSUE TITLE
reading numbers in I/O

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#493]
For many input formats we need to read numbers from the character stream. There are couple of ways to do this, but I would recommend just streaming from the stream directly into the target variable, i.e. not using the stream view, but directly accessing the stream. 

E.g. assume you have "[1, 2, 3, 4]" in the file and you want to read this...
```cpp
std::vector<uint32_t> vec;
vec.resize(4);
detail::consume(stream_view | view::take_until_or_throw(is_digit));
stream >> vec[0];
detail::consume(stream_view | view::take_until_or_throw(is_digit));
stream >> vec[1];
detail::consume(stream_view | view::take_until_or_throw(is_digit));
stream >> vec[2];
detail::consume(stream_view | view::take_until_or_throw(is_digit));
stream >> vec[3];
detail::consume(stream_view | view::take_until_or_throw(is_char<']'>));
```
(if you know for sure that there is always one character inbetween the numbers, it would of course be better to just `++ranges::begin(stream_view)`).

It is possible that using the stream directly invalidates the streams iterators (and thereby the stream_view), but since it just an input range anyway it *should* be ok.

IF THIS DOESN'T WORK:

I would propose implementing `std::from_chars` in our std module (with the exact same interface as in the standard library). We could use easy solutions inside the function before implementing efficient ones (e.g. copying into a buffer and calling `strtol` or so).

**Comment by smehringer** [comment]
Side question: Does every arithmetic type has an operator>> overload, even different representations of floats (e.g. `10e-2`) and negative numbers (`-2`)?

Considering proposal 1: We would still need the following checks (supplied by std::from_char).
* Check the stream for `stream.fail()` in case casting went wrong
* Check the stream to have consumed everything. E.g. `"3a" >> x ` will be happily parsed to `x = 3` but should not.
* Check if the given number as string does not cause an over/underflow error.  (What happens with `uint16_t x; "-3" >> x`?)

Considering the checks and throwing exceptions on error, this should be still wrapped in a function and maybe is thereby not much less work then implementing std::from_char.

Unrelated to this issue: Any specific reason our view is called `char_to` instead of `from_char`? Might be more consistent with the STL.

**Comment by h-2** [comment]
> Side question: Does every arithmetic type has an operator>> overload, even different representations of floats (e.g. 10e-2) and negative numbers (-2)?

Yes!

> Considering proposal 1: We would still need the following checks

Not really, you can check on the next read whether you are on the right character after extraction or you can have the `view::take_until_or_throw( )` cause an exception.
E.G. if you know exactly that each number is separated by exactly once `,`, you can do
```cpp

std::vector<uint32_t> vec;
vec.resize(4);
assert(*ranges::begin(stream_view) == '[');
stream >> vec[0];
assert(*ranges::begin(stream_view) == ',');
++ranges::begin(stream_view);
stream >> vec[1];
assert(*ranges::begin(stream_view) == ',');
++ranges::begin(stream_view);
stream >> vec[2];
assert(*ranges::begin(stream_view) == ',');
++ranges::begin(stream_view);
stream >> vec[3];
assert(*ranges::begin(stream_view) == ']');
```
I would assume this is also a lot less expensive then doing the checks you mentioned.

> Unrelated to this issue: Any specific reason our view is called char_to instead of from_char? Might be more consistent with the STL

But they do completely different things, one does conversion (by calling `assign_char`) and the other does lexical interpretation of strings... Also `view::char_to<dna4>` is very well readable as something that converts chars to dna4, or not? :grinning:

**Comment by rrahn** [comment]
In general I would only go for the second option regarding performance, which is our major concern here.
My general understanding is that streams provide a generalised formatted input/output version and that this is not very efficient. We had special lexical_cast functionality in SeqAn before, similar to boost, which is much more performant to do these conversions. 
It seems, that the from_chars/to_chars family is the c++17 counterpart of this.
Though I remember a proposal for adding boost::lexical_cast to the STL, but I am not sure if this is the outcome of this or some other proposal.
Here a discussion on a reddit thread regarding efficiency of string to arithmetic conversion:

https://www.reddit.com/r/cpp/comments/92bkxp/how_to_efficiently_convert_a_string_to_an_int_in_c/

And the following quote indicates that these functions are going to be heavily optimised.

>Floating-point from_chars() is available in VS 2017 15.8 Preview (currently Preview 5). I worked on its performance for months, and I benchmarked it as being ~40% faster than strtod()/strtof() on my machine.
Note that while I implemented integer from_chars() and to_chars() with some attention to performance, they aren't hyper-optimized yet (in particular, I am aware of techniques to make to_chars() faster). I focused on getting a correct implementation with extensive testing first, so we could optimize it behind-the-scenes later.
I'm working on floating-point to_chars() right now - the performance of the shortest-representation (non-precision) overloads will be amazing. (Over 10x to 40x faster than sprintf() - times not percent.)

However, there seems to be a lot of comments suggesting some safety issues, as `+` signs or `0x12` numbers are not recognised correctly. But, I am not sure, that these issues are of big concern for us as most of the formats we typically have to parse have  a specified format so we can handle this.

**Comment by h-2** [comment]
> In general I would only go for the second option regarding performance, which is our major concern here.

Yes and no. In general the implementation of `std::from_chars` should be more efficient, but it requires that you pass it `char const *` which we don't have in our situation. This means we need to dynamically allocate a buffer in the function, copy the number string out of the stream and into the buffer (this already involves parsing-logic if you want to do it in a generic way) and then call `std::from_chars`.

I suggest we do a benchmark that compares the two alternatives, but maybe at a later point in time? Maybe we can a TODO somewhere...?

**Comment by rrahn** [comment]
>Yes and no. In general the implementation of std::from_chars should be more efficient, but it requires that you pass it char const * which we don't have in our situation. This means we need to dynamically allocate a buffer in the function, copy the number string out of the stream and into the buffer (this already involves parsing-logic if you want to do it in a generic way) and then call std::from_chars.

Well, I would rather have a std::array allocated on the stack, write the stream into the buffer, (which we will be really fast once we have a `stream_chunk_view` that reads directly from the stream buffer) and then use `array.data()` to get the char*.

**Comment by rrahn** [comment]
But in general, these are optimisations we can do after getting the parsing done correctly. So for convenience it is ok to just parse it at the moment with the formatted in/out functions. Though, the topic of this issue was about design decisions. And this is what I prefer

**Comment by h-2** [comment]
> Well, I would rather have a std::array allocated on the stack

Sure, you could use a stack storage, but how much would you copy from the stream? Remember that it's single-pass so copying too much breaks successive parsing. Copying exactly only the number while supporting all different number formats is expensive and likely half the cost of parsing the number at all.

> But in general, these are optimisations we can do after getting the parsing done correctly. So for convenience it is ok to just parse it at the moment with the formatted in/out functions. Though, the topic of this issue was about design decisions. And this is what I prefer

Yes, I agree, it's something we need to keep an eye on! In the end we need to measure it anyway.

**Comment by rrahn** [comment]
Well fortunate for us, we know what to parse. Typically formats don't say `it could be int, but it could also be float` So we can simply parse the bytes for the number, without testing for different numbers formats (e.g. parse until next delimiter). And this merely involves copying chars from one buffer into another (at the end) which can be done very efficiently. Or am I missing something? It is also clear, that the size of the buffer is known by the format specification and that we can use a single buffer for all records to be parsed, because of the single-pass restriction.

**Comment by smehringer** [comment]
> Not really, you can check on the next read whether you are on the right character after extraction or you can have the view::take_until_or_throw( ) cause an exception.
> `assert(*ranges::begin(stream_view) == '[');`

This check is totally unrelated to the checks I mentioned? Maybe I did not understand you correctly, but after calling `stream >> vec[i]` in either of your examples there could be an error that should trigger an exception analogously to reading an illegal character in the sequence, e.g. on `[1,2,a,4]`.

**Comment by h-2** [comment]
ok, say you expect three tab-separated numbers, it's even easier, because the following tab is consumed:
```cpp
stream >> d1;
my_assert(is_digit(*stream_it));
stream >> d2;
my_assert(is_digit(*stream_it));
stream >> d3;
//assert whatever comes after
```

if you have `123\t456\t789`, it will exactly extract the numbers. If you instead have `123\t4A6\t789` you **won't** get an error when extracting the second number, but you **will** get assert when checking if the current character is a digit, immediately after (because the current character will be a 'A').


That's what I meant above: if the number is incorrect, you will not necessarily get an exception when extracting the number itself, but you will definitely get an exception when you assert on the delimiter (or the beginning of the next number).

**Comment by h-2** [comment]
Combining stream iterators/views and directly streaming doesn't work well, so we need to go back to buffering and parsing the buffer. This involves multiple things:

* add a container class with static storage, but dynamic size behaviour; this can inherit from constexpr_string; it could share a base-class with the `small_string` we discussed in #414 ;
* Add `THAT_TYPE number_buffer`  as a member variable to the format.
* add implementations for `std::from_chars`
* then:
```cpp
number_buffer = stream_view | view::take(buffer_size) | view::take_until_or_throw(is_char<'\t'>);
std::from_chars(buffer.begin(), buffer.end(), your_integer);
```

This first `view:take()` ensure that we never exceed the buffer size and the second one asserts the condition and throws.

**Comment by h-2** [comment]
> add a container class with static storage, but dynamic size behaviour;

As a workaround, you can for now use a `std::vector<char>` as a member variable and reserve that to say 100 on construction of the format. But, don't forget to clear the buffer before each use :wink:

**Comment by h-2** [comment]
@smehringer This can be closed, because we have from_chars, right?

**Comment by smehringer** [comment]
Yes. See #500.
