### ISSUE TITLE
GCC8 testing issues

### ISSUE THREAD

**Issue by joshuak94** [seqan/seqan3#494]
When using cmake with GCC8, the debug builds are all executed fine. However, the Release mode builds have a few errors:

`sequence_file_integration_test` fails with error: `C++ exception with description "The ID field may not be empty when writing FASTA files." thrown in the test body.`

`search_test` fails with errors:
In `search_strategy_best`:
 ```cpp
Expected equality of these values:
  search(this->index, "AAAA"_dna4, cfg)
    Which is: { 0 }
  (hits_result_t{})
    Which is: {}
```
Further, SEGFAULTS from the following tests:
```
	 56 - unit/io/alignment_file/alignment_file_output_test (SEGFAULT)
	 62 - unit/io/sequence_file/sequence_file_output_test (SEGFAULT)
	 69 - unit/io/structure_file/structure_file_output_test (SEGFAULT)
```

**Comment by h-2** [comment]
@cpockrandt please have a look at the issue in the search module!

@marehr @smehringer If the two of you have time to look at the i/o issues next week, that would be great! I hope we are not running into regressions.

**Comment by marehr** [comment]
Yeah sure we can investigate this.
