### ISSUE TITLE
deprecate matrix formatter for a direct debug_stream overload

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#510]
As discussed in #495 we want to throw away the `matrix_formatter` and put the code directly into a `debug_stream` overload.

-----

### Preliminaries

We currently have 3 major ways to print matrices:
* ASCII
  ```c++
     | |A|A|C|C|G|G|T|T|
     /-/-/-/-/-/-/-/-/-/
     |0|1|2|3|4|5|6|7|8|
     /-/-/-/-/-/-/-/-/-/
    A|1|0|1|2|3|4|5|6|7|
     /-/-/-/-/-/-/-/-/-/
    C|2|1|1|1|2|3|4|5|6|
     /-/-/-/-/-/-/-/-/-/
    G|3|2|2|2|2|2|3|4|5|
     /-/-/-/-/-/-/-/-/-/
  ```
* CSV
  ```c++
     ; ;A;A;C;C;G;G;T;T;
     ;0;1;2;3;4;5;6;7;8;
    A;1;0;1;2;3;4;5;6;7;
    C;2;1;1;1;2;3;4;5;6;
    G;3;2;2;2;2;2;3;4;5;
    T;4;3;3;3;3;3;3;3;4;
  ```
* UNICODE
  ```c++
     ║ε║A║A║C║C║G║G║T║T║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
    ε║0║1║2║3║4║5║6║7║8║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
    A║1║0║1║2║3║4║5║6║7║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
    C║2║1║1║1║2║3║4║5║6║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
    G║3║2║2║2║2║2║3║4║5║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
    T║4║3║3║3║3║3║3║3║4║
  ```

We will remove ASCII in favour of CSV, because CSV is generally more useful (e.g. put that into excel) and only support one UNICODE. We use `seqan3::fmtflags2` and `utf8` to distinguish whether to output CSV or UNICODE. 

### Introduce debug_matrix

We currently have alignment matrices, such as `alignment_score_matrix<>` and `alignment_trace_matrix<>`.
* CON: They don't store the sequences and thus can't print them, so output is only like
  ```c++
     ║ε║ ║ ║ ║ ║ ║ ║ ║ ║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
    ε║0║1║2║3║4║5║6║7║8║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
     ║1║0║1║2║3║4║5║6║7║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
     ║2║1║1║1║2║3║4║5║6║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
     ║3║2║2║2║2║2║3║4║5║
     ╬═╬═╬═╬═╬═╬═╬═╬═╬═╬
     ║4║3║3║3║3║3║3║3║4║
  ```

We will add a new matrix that will be called debug_matrix and which can store sequences and will take over the functionality of alignment_formatter in the debug_stream overload.

**Comment by h-2** [comment]
Can you clean this up in time for the release?
