### ISSUE TITLE
[FEATURES/BUGS] Argument_parser

### ISSUE THREAD

**Issue by joshuak94** [seqan/seqan3#532]
List of possible features/bugs worth discussing regarding the argument_parser.

Bugs:
- [x]  --export-help html is not properly exporting the Synopsis section.

~- When printing help for something with a `value_list_validator`, there is no space between the listed options. (Value must be one of [call,merge]).~ This is fine

Features:
- [x]  Allow file_ext_validator to work on a vector of strings? Example:
```cpp
const char * argv = {"./test.", "file1.bam", "file2.bam"};
seqan3::argument_parser myparser("test", 3, argv);
std::vector<std::string> option1;

add_positional_option(option1, "INPUT", file_ext_validator({std::string("bam")}));
myparser.parse()
```
^ Doesn't currently work because option1 and std::string aren't the same type.

- [ ]  Add a min and max validator (think about removeing the range validator since it can be modelled by min and max) (see https://github.com/seqan/seqan3/projects/7#card-26482709)

When displaying the --help/-h page, it would be nice if the flags showed either 
- [ ] "REQUIRED", (see https://github.com/seqan/seqan3/projects/7#card-26482743) or 
- [x] "Default = 10". 
Example would be:
```
-r, --referenceGenome STRING [Required]
    Genome sequence file(.fa). File name extension must be one of [fa].
-q, --minMapQual INT (32 bit) [Default = 20]
    Mapping quaility cutoff. Value must be in range [0,2147483647].
--report-filtered [Default = False]
    Report filtered result.
```

More to come...

**Comment by joshuak94** [comment]
@smehringer Some initial things!

**Comment by joshuak94** [comment]
Small example regarding the first error:
```cpp
#include <seqan3/argument_parser/all.hpp>

int main(int argc, const char ** argv)
{
    seqan3::argument_parser testparser("test", argc, argv);
    testparser.info.app_name = "NAME";
    testparser.info.synopsis.push_back("THIS DOES NOT DISPLAY");
    testparser.info.short_description = "short description";
    testparser.info.description.push_back("BLAHBLAHBLAH");

    try
    {
        testparser.parse();
    }
    catch(seqan3::parser_interruption)
    {
        return 1;
    }
    return 0;
}
```

**Comment by smehringer** [comment]
> For the second feature, sometimes I just want the option to take an int >= 0 (or >= -1), but no need to make an upper limit. Or I want a negative number but no positive numbers (min INT32_MIN, max 0). I just think it'd be nice to have a better display in the help than a range of -10373948294820 to 0.

Ah I see. Then we should have a maximum and minimum validator that just says `.. must be greater than 0.` I think this was already an idea but I never worked on this.

**Comment by joshuak94** [comment]
Yeah, if it was something like `arithmetic_max_validator(10)`, and your variable was a `int32_t`, then your variable can take any value from `INT32_MIN` to 10, and an `arithmetic_min_validator(-1)`, then your variable can be anything from -1 to `INT32_MAX`.

Or even just one function where you call it `arithmetic_limit_validator(max=TRUE, 10)` or `arithmetic_limit_validator(max=FALSE, -1)`?

Then there could be a better formatted error message such as "Value must be at most 10", or "Value must be at least -1", instead of "Value must be within range [-1, 2147483647]".

**Comment by tloka** [comment]
Related to this, so I didn't open a new issue:
I think it would be nice to have a case insensitive option for file_ext_validator (e.g., having optional constructor argument `bool case_sensitive = true` that can be changed to false if required). Usually, a `.BAM` is similar to `.bam`.
Probably it would even be sufficient to have always case insensitivity, then an `std::transform` could be used with `std::tolower` for vector storage and comparison. However, maybe there are situations that require case sensitivity!?

**Comment by smehringer** [comment]
I added cards for the remaining to open feature points about the min/max validator and required options so this can be closed
