### ISSUE TITLE
GCC8 ICE when trying to print a seqan3::filesystem::path with the debug_stream

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#540]

**Comment by marehr** [comment]
Can you give a code sippet?

**Comment by smehringer** [comment]
```
#include <seqan3/io/filesystem.hpp>
#include <seqan3/io/stream/debug_stream.hpp>

int main()
{
    seqan3::filesystem::path my_path{"/usr/file.txt"};
    debug_stream << my_path;
}
```

**Comment by eseiler** [comment]
From what I've seen, the ICE occurs in GCC 7 and 8.
It hails from this concept:
https://github.com/seqan/seqan3/blob/c14ce2f2f50c4413cad693edfbca4885e4baa782/include/seqan3/io/stream/debug_stream.hpp#L315

What will work is:
* streaming directly to std::cerr
* ```cpp
   seqan3::debug_stream_type d{};
   d.operator<<(my_path); // delegating directly to underlying stream
   ```

The [filesystem::path](https://en.cppreference.com/w/cpp/filesystem/path) object has several member functions for returning, e.g., a [string](https://en.cppreference.com/w/cpp/filesystem/path/string).

So actually:

```cpp
#include <seqan3/io/filesystem.hpp>
#include <seqan3/io/stream/debug_stream.hpp>

int main()
{
    seqan3::filesystem::path my_path{"/usr/file.txt"};
    seqan3::debug_stream << my_path.string();
}
```
will work.

The `<<` [operator](https://en.cppreference.com/w/cpp/filesystem/path/operator_ltltgtgt) of path also uses the member functions to convert to a string.

**Comment by smehringer** [comment]
Result of discussion:

The iterator on a file path is a directory iterator, that's why it is again a range.
The metafunctions show expected behaviour but the requires statement runs into an endless loop causing the ICE.
To circumvent this we need a separate debug_stream overload for path, which should go into gebud_stream.hpp with a forward declaration of filesystem::path.
