### ISSUE TITLE
Short license headers

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#553]
In https://github.com/seqan/seqan3/pull/523#issuecomment-436177165 we shortly discussed that we might want to introduce shorter license headers.

For example, transforming

https://github.com/seqan/seqan3/blob/ffca425fecf8e2a490e1493399b866fe1c3ee689/test/unit/core/bit_manipulation_test.cpp#L1-L33

into

```c++
// This software may be modified and distributed under the terms of the BSD license.  See the LICENSE file for details.
```
This would reduce 33 lines down to 1 line.

I propose to do those changes only to files that we don't ship. Which means all files except for `include/` and `build_system/` should be changed.

----

Thoughts, suggestion, remarks?

**Comment by joergi-w** [comment]
> I propose to do those changes only to files that we don't ship. Which means all files except for `include/` and `build_system/` should be changed.

Thank you for discussing this idea @marehr! All files except for the mentioned result in `test/` only. I do not see the point in introducing a different rule for the test directory headers. Do we really care about the length of test files more than others? In my opinion, let us use your supposed short header either everywhere or nowhere.

**Comment by h-2** [comment]
I also lean slightly towards changing this everywhere. But I do think the shorter version needs to be a little longer:
```cpp
// Copyright (c) 2006-2018, Knut Reinert & Freie Universitaet Berlin 
// Copyright (c) 2016-2018, Knut Reinert & MPI Molekulare Genetik 
// May be modified and/or redistributed under the terms of the 3-clause BSD-License shipped with this source-code or under:
// https://github.com/seqan/seqan3/blob/master/LICENSE
```

The Copyright lines should never be omitted, I think.

**Comment by eseiler** [comment]
Maybe like this?

```cpp
// Copyright (c) 2006-2018, Knut Reinert & Freie Universitaet Berlin 
// Copyright (c) 2016-2018, Knut Reinert & MPI Molekulare Genetik 
// You may use, distribute and modify this code under the terms of the 3-clause BSD-License shipped 
// with this file and also available at: https://github.com/seqan/seqan3/blob/master/LICENSE
```

I would also include the copyright, though some people also omit it.

**Comment by h-2** [comment]
Compromise:
```cpp
// Copyright (c) 2006-2018, Knut Reinert & Freie Universitaet Berlin 
// Copyright (c) 2016-2018, Knut Reinert & MPI Molekulare Genetik 
// This file may be modified and/or redistributed under the terms of the 3-clause BSD-License shipped
// with this file and also available at: https://github.com/seqan/seqan3/blob/master/LICENSE
```

**Comment by smehringer** [comment]
If this is the final version,
I would limit line width to 80 (if this is not the case already) and would still have seperation lines that makes them look more like a header than just some comments (shipped files should also look nice :crown: ).

```
// -----------------------------------------------------------------------------
// Copyright (c) 2006-2018, Knut Reinert & Freie Universitaet Berlin 
// Copyright (c) 2016-2018, Knut Reinert & MPI Molekulare Genetik 
// This file may be used, modified and/or redistributed under the terms of the
// 3-clause BSD-License shipped with this file and also available at: 
// https://github.com/seqan/seqan3/blob/master/LICENSE
// -----------------------------------------------------------------------------
```

In general I would keep the header in the include file as it is or change it to the "not so short either header" above and just use @marehr's one liner in the test files.

> Do we really care about the length of test files more than others? (@joergi-w )

I do because in the test files I think it unneccessary and I would rather see more of the test instantly than scrolling down a header nobody cares about.

**Comment by smehringer** [comment]
Ok

**Comment by h-2** [comment]
3/4 of the core team just agreed on:
```cpp
// -----------------------------------------------------------------------------------------------------
// Copyright (c) 2006-2018, Knut Reinert & Freie Universitaet Berlin 
// Copyright (c) 2016-2018, Knut Reinert & MPI Molekulare Genetik 
// This file may be used, modified and/or redistributed under the terms of the 3-clause BSD-License
// shipped with this file and also available at: https://github.com/seqan/seqan3/blob/master/LICENSE
// -----------------------------------------------------------------------------------------------------
```

**Comment by joergi-w** [comment]
Shouldn't it be 
MPI _für_ Molekulare Genetik? 
Since we change all headers anyway, we could correct this.

**Comment by rrahn** [comment]
What is your coporate specifications say? Is there something specified. Then we should stick to this.

**Comment by joergi-w** [comment]
I had a look: The corporate name is _Max-Planck-Institut für molekulare Genetik_. And _MPI_ is an official abbreviation for _Max-Planck-Institut_.

**Comment by eseiler** [comment]
Do we then put `MPI fuer molekulare Genetik` or `MPI für molekulare Genetik`? But if we allow an umlaut for the MPI, we might as well write `Universität` instead of `Universitaet`.

**Comment by eseiler** [comment]
Ok.

I'll do an PR for:

```cpp
// -----------------------------------------------------------------------------------------------------
// Copyright (c) 2006-2018, Knut Reinert & Freie Universität Berlin 
// Copyright (c) 2016-2018, Knut Reinert & MPI für molekulare Genetik 
// This file may be used, modified and/or redistributed under the terms of the 3-clause BSD-License
// shipped with this file and also available at: https://github.com/seqan/seqan3/blob/master/LICENSE
// -----------------------------------------------------------------------------------------------------
```

**Comment by h-2** [comment]
There are currently at least two huge PRs open so we should wait at least until they are merged.

**Comment by eseiler** [comment]
Some major changes were merged recently, so what PRs are left that are blocking this?

**Comment by rrahn** [comment]
@eseiler nothing, but we should wait to the end of the sprint. At least the number of open PRs that would be affected should be then to a minimal.
