### ISSUE TITLE
Header checks should verify tht every header includes platform.hpp

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#564]
... either directly or via another header include.

**Comment by smehringer** [comment]
note from earlier conversations: we could test this by checking if `SEQAN3_WITH_CEREAL` is defined

**Comment by marehr** [comment]
Okay, I translate it into something that someone can work on:

Change 

https://github.com/seqan/seqan3/blob/f51501cfac3d6cadda9858fc9014fdaeb5bf4e6f/test/header/CMakeLists.txt#L93-L97

into

```cmake
            file (WRITE "${source_file}" "
#include <${header}>
#include <${header}>
#include <gtest/gtest.h>
TEST(Header, ${header_source_test_name}) {}")

            # test that seqan3 headers include platform.hpp
            if (component MATCHES "seqan3")
                file (APPEND "${source_file}" "
#ifndef SEQAN3_DOXYGEN_ONLY
#error \"Your header file is missing #include<seqan3/core/platform.hpp>\"
#endif")
            endif ()
```

After that fix the header test.
