### ISSUE TITLE
cmake: test whether each all.hpp includes all non-detail header files in the current dir.

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#568]
Oh and we wanted to test whether each all.hpp includes all non-detail header files in the current dir.

_Originally posted by @smehringer in https://github.com/seqan/seqan3/issues/564#issuecomment-439843918_

-----

That means:

1. go through each subdirectory which contains a `all.hpp` file.
2. check whether it includes all header files within this subdirectory and its subdirectories [except for the all.hpp itself]

### Examples: 

`seqan3/include/seqan3/range/container/` contains a `all.hpp`
* aligned_allocator.hpp [should be included in all.hpp]
* all.hpp [should be excluded from all.hpp; because it is the same file]
* bitcompressed_vector.hpp [should be included in all.hpp]
* concatenated_sequences.hpp [should be included in all.hpp]
* concept.hpp [should be included in all.hpp]
* constexpr_string.hpp [should be included in all.hpp]

### A possible Approach:

As I see it, we would need to do this:

* Copy whole /seqan3/include/ into a new directory (somewhere in the build folder)
* Add a unique macro in each file
  * for example `seqan3/include/seqan3/range/container/concatenated_sequences.hpp` could be `HEADER_SEQAN3__range__container__concatenated_sequences` 
  * note we could use TARGET_UNIQUE_NAME from:
    https://github.com/seqan/seqan3/blob/9897a678dd0e92c306c20ae4b09e1d197188409e/test/seqan3-test.cmake#L95-L102
* Create for each `all.hpp` a cpp file which includes the `all.hpp` and checks whether each unique macro is defined.
  For example:
  ```c++
  #include <seqan3/range/container/all.hpp>
  #ifndef HEADER_SEQAN3__range__container__aligned_allocator
  #error "#include <seqan3/range/container/aligned_allocator.hpp> is missing in seqan3/range/container/all.hpp"
  #endif
  #ifndef HEADER_SEQAN3__range__container__concatenated_sequences
  #error "#include <seqan3/range/container/concatenated_sequences.hpp> is missing in seqan3/range/container/all.hpp"
  #endif
  ```

### Open questions:
* should `all.hpp` be within each subdirectory?

**Comment by rrahn** [comment]
@marehr is this done?

**Comment by marehr** [comment]
No! This needs a new infrastructure. I updated the description to make clear what has to be done.

**Comment by smehringer** [comment]
What's the status of this?
