### ISSUE TITLE
Bring aminoacid submodule up to state

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#57]
* [x] add `alphabet/aminoacid.hpp` meta-header and introduce sub-module for aminoacid
  * [x] remove `alphabet/aminoacid/aa27_container.hpp`
  * [x] clean-up `alphabet/aminoacid/aa27.hpp`
    * style-guide, documentation,  make statics private, replace table with constexpr lambda...
  * [x] add aa27 to the generic alphabet tests, reduce the aa27 test to the specific parts
    
Most of this can be easily adapted from the nucleotide submodule.

@sarahet, since you are working on this anyway, could you update it?

**Comment by sarahet** [comment]
What should be included into the alphabet/aminoacid.hpp? As we have only the aa27 alphabet at the moment?
Will there be a concept in any way concerning the aminoacid submodule? As we don't have different types as for nucleotide submodule.

**Comment by sarahet** [comment]
Just to make sure there is no explicit cast char_type() anymore?

**Comment by marehr** [comment]
> Just to make sure there is no explicit cast char_type() anymore?
yes

**Comment by h-2** [comment]
> What should be included into the alphabet/aminoacid.hpp? As we have only the aa27 alphabet at the moment?

Yep, that's correct. There will later maybe be your translate.hpp and also reduced amino acid alphabets.

> Will there be a concept in any way concerning the aminoacid submodule? As we don't have different types as for nucleotide submodule.

No, it's not required, at least not, yet.

> I guess we want an aminoacid_test.cpp file instead of the old test files?!

Yes! There now is a general alphabet_test.cpp and aa27 should be added there (it's already added, but commented out). And then there should be an aminoacid_test.cpp for aminoacid specific stuff.

**Comment by sarahet** [comment]
Thanks to both of you
