### ISSUE TITLE
Compressed FASTA indexing

### ISSUE THREAD

**Issue by fungs** [seqan/seqan3#591]
Hi,

looking at the documentation at https://seqan.readthedocs.io/en/master/Tutorial/InputOutput/IndexedFastaIO.html I find no mention of compressed FASTA file indexing as done in htslib or BioPython/pyfaidx. When a FASTA file is compressed as valid gzip using the program bgzip, it should be possible to index the file using the corresponding auxiliary .gzi index file. I'm using indexed FASTA with Seqan for a while but the FASTA files grow kind of large, so it would be very helpful if Seqan would support compressed FASTA indexing.

Thanks!

Best,
Johannes

**Comment by fungs** [comment]
That would be great, I think it shouldn't be too difficult, compression is similar to how BAM files work.

**Comment by rrahn** [comment]
Well, yes, but we are currently on a feature stop for SeqAn 2 and trying to get SeqAn3 done. So there will be some time until we can get it. I hope you can bear this delay until then.

**Comment by marehr** [comment]
Hi @fungs,

we are adding this to our long term todo list. As soon as someone is working on it, we will reopen the issue.

See https://github.com/seqan/seqan3/projects/17#card-27119766
