### ISSUE TITLE
Refactor algorithm configuration

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#601]
### Alignment module

 - [x] scoring config
 - [x] gap scheme config
 - [x] aligned ends config
 - [x] global config
 - [x] edit config
 - [x] output config
 - [x] max error config
 - [x] band config
 - [x] remove utility
 - [x] add detail with compatibility table
 - [x] adapt current pairwise selector
 - [x] adapt current pairwise alignment
 - [x] adapt bitvector alignment

### Search  module
 - [x] max_error_common
 - [x] max_error_rate
 - [x] max_error
 - [x] mode
 - [x] output
 - [x] remove utility

### General
 - [x] add concept checks to the individual test 
cases
 - [x] check all.hpp in configuration
WIP: see #567

**Comment by smehringer** [comment]
This looks like it should be a project card with single issues, no ?

**Comment by rrahn** [comment]
resolved by #567
