### ISSUE TITLE
alignment

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#608]
Currently the alignment result object is implemented as a tuple with enum based access. To reduce the complexity of the interface and to allow type-erasure on the return type of alignment algorithms the result object should be refactored.

The file is here: `include/seqan3/alignment/pairwise/align_result.hpp`

Tasks:
 - [x] Remove tuple interface of the alignment result type
 - [x] the class can be queried to return the score*, the end position, the begin position, the traceback.
 - [x] the score must always be set
 - [x] The other values (except the score) are optionals
 - [x] On access of an non-set optional throw an invalid access error.
 - [x] Only return unmutables or copies of the respective value.
 - [x] The necessary types should be passed as a traits type  
 - [x] implement a concept for the traits class to check for valid configuration
 - [x] write tests
 - [x] write docu

###### estimate: 13

**Comment by smehringer** [comment]
I thought we decided not to make meta issues but meta cards with single task issues?

**Comment by joergi-w** [comment]
Implemented with PR #625.
