### ISSUE TITLE
Doxygen \file should be empty if it is in the same file

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#61]
Currently we use mostly the `\file <filepath>` syntax.

For example in file `/include/seqan3/alphabet/nucleotide/rna4.hpp`
```c++
/*!\file alphabet/nucleotide/rna4.hpp
 * [...]
 */
```
which is basically the absolute path without the `/include/seqan3/` part.

In `/include/seqan3/alphabet/range.hpp` and `/include/seqan3/core/platform.hpp` we only use the filename itself.

```c++
/*!\file platform.hpp
 * [...]
 */
```

------
I propose to use the `\file` syntax (without `<filepath>`), because according to https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdfile:

> If the file name is omitted (i.e. the line after \file is left blank) then the documentation block that contains the \file command will belong to the file it is located in.

Manual testing showed that it will produce the same doc as by providing a `<filepath>`.

------

A pro argument is:
 * You can't forget to rename the `<filepath>` part, after renaming the actual file

A contra argument:
 *  If you see `\file alphabet/nucleotide/rna4.hpp` - even if you don't know what `\file` means - you can kind of guess that the following documentation is only for the file `\file alphabet/nucleotide/rna4.hpp`, whereas `\file` may not be descriptive enough

**Comment by h-2** [comment]
If it works as expected (no ambiguities) it is much better than having to write the name of course :+1: 

Do you want to make a PR for the whole library?

**Comment by marehr** [comment]
Yes I would do a pull request for the whole repository

**Comment by h-2** [comment]
Great! Please don't forget to update the wiki, as well!

**Comment by marehr** [comment]
What do you mean with updating the wiki? There is no section about `\file`.

**Comment by h-2** [comment]
> What do you mean with updating the wiki? There is no section about \file.

https://github.com/seqan/seqan3/wiki/Headers-and-Namespaces#contents :)

**Comment by marehr** [comment]
Okay, was hard to find, since it is not within the dox section.

Wiki has been updated

**Comment by h-2** [comment]
Yes, the dox section needs a lot more love.
