### ISSUE TITLE
Indentation for alignment output

### ISSUE THREAD

**Issue by joergi-w** [seqan/seqan3#614]
Currently the alignment output is indented by a constant number of spaces (8), as in SeqAn2. 

@marehr suggested in PR #593 that we adapt the indentation according to the number of digits of the largest position number, so dependent on the alignment length. This leads to a minimal possible indentation.

**Comment by joergi-w** [comment]
My concern is that two alignments with different indentations will be hard to compare with `diff`.

**Comment by joergi-w** [comment]
I agree that diff might not be very useful. It was just a thought. However, I don't see any benefit in changing from a static indentation to a dynamic one, as the sequence length per line is anyway fixed to 50.

**Comment by smehringer** [comment]
Hm it might introduce unnecessary complexity but what if the size grows too large and 50 is not enough?

**Comment by joergi-w** [comment]
If the size of the alignment is larger than 50, the output becomes multi-line:

```
      0     .    :    .    :    .    :    .    :    .    : 
        GGUGGCGGCCAUAGCGGCGGGGCAAUUCCUGUACCCAUCCCGAACACAGA
          |||||||||| ||||||||| || ||||||||||||||||||||||| 
        -UUGGCGGCCAUGGCGGCGGGGUAACUCCUGUACCCAUCCCGAACACAGC

     50     .    :    .    :    .    :    .    :    .    : 
        AGAUAAGCCCGCCUGCGUUCUAUACUGUACUAAAGUAUGAGAGUCUUUGG
        |||||| |||||| ||||||  ||| ||||||||||  | ||| ||||||
        AGAUAAACCCGCCCGCGUUCCGUACGGUACUAAAGUGCGCGAGCCUUUGG

    100     .    :    .    :   
        GAAAUAUGGAACGCUGCCACCA
        ||| |  |||  ||||||| | 
        GAACUGCGGAUAGCUGCCAGCU


```

**Comment by smehringer** [comment]
nah I mean if the size is so large that the position number is larger than 50 bytes
```
....
100000001     .    :    .    :    .    :    .    :    .    : 
        GGUGGCGGCCAUAGCGGCGGGGCAAUUCCUGUACCCAUCCCGAACACAGA
          |||||||||| ||||||||| || ||||||||||||||||||||||| 
        -UUGGCGGCCAUGGCGGCGGGGUAACUCCUGUACCCAUCCCGAACACAGC
```

**Comment by rrahn** [comment]
I don't see any benefit for this. No one is ever gonna look at a ten's of thousands long alignment output. So this really just a nice debuggin output. On application level, we rather have CIGAR strings etc. So for me this has absolutely no priority.

**Comment by joergi-w** [comment]
I think we can close this for now, because most developers agree with the current implementation.
