### ISSUE TITLE
type_list / meta design discussion

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#649]
I played around with different more modern meta-programming approaches the last days, including doing all things via function template declarations (no function body) and variable templates. Both approaches have some very nice properties and a much shorter syntax than declaring class types, adding specialisations and shortcuts....

Here's an example of metafunctions as variable templates:
```cpp
template <size_t idx, typename head_t, typename ...pack>
    requires idx <= sizeof...(pack)
inline head_t at;

template <size_t idx, typename head_t, typename ...pack>
    requires idx > 0 && idx <= sizeof...(pack)
inline auto at<idx, head_t, pack...> = at<idx - 1, pack...>;
```

But both have severe drawbacks, some of the problems I encountered:
* functions can't return const types, therefore `at<0>(type_list<int const, float>{})` will have type `int`, not `int const`.
* variable templates have the opposite problem, either you make them `constexpr` (although you are usually not interested in the value, just type which is always resolved at compile time), this makes metafunctions always add `const` to the type; if you choose not to make things constexpr than it works, but it will lead to actual variables being instantiated and assembly code generated for them which something we don't want for metaprogramming I think (it does guarantee caching of the results, though).

@seqan/core If you don't have major vetos, I will start implementing a more traditional design with class templates for all traits and `_t` shortcuts for transformation traits and `_v` for type traits. I will also offer identical interfaces for type_lists and parameter packs, each in different sub namespaces.

It will look like this:

namespace seqan3
* type_list

namespace seqan3::tpack / namespace seqan3::tlist
* transformation traits (return single type): front, back, at
* type traits (return single value): size, empty, index_of, contains
* transformation traits (return type_list):
  * concat (takes two lists, returns one),
  * prefix (takes list + length) ,
  * suffix (takes list + length)
  * reverse
  * filter (takes list and predicate in form of variable template, returns those elements for which predicate returns true)
  * unique (filer that removes duplicates)
  * transform (takes a transformation trait and applies it to every item in the list)
  * split_at (takes list/pack + number, returns pair of lists)
  * split_on (takes list/pack + pivot, returns pair of lists)

Did I forget anything?

**Comment by h-2** [comment]
> I'm not sure if we should not only add stuff that we need.

I have thought about this, too, let's re-discuss this at the the next strategy meeting. I had hoped we could go with a better general design than before, but I think now that this may not be possible so we might also just import eric niebliers meta into `contrib`.

**Comment by h-2** [comment]
ps: 

> I think those could be postponed:

The way I designed my prototype codes was by implementing some through others but offering them convenience.

**Comment by h-2** [comment]
I have given up on this. I think we need to evaluate whether we need meta at all, and if yes, copy it to contrib.

**Comment by rrahn** [comment]
At least we need to go over all references to the meta library, see if we really need it or if we can provide it on our own. For the release we should not depend on the ranges/meta library anymore.

**Comment by h-2** [comment]
Reviving this after discussions with @rrahn. The plan is to use variable templates and `constexpr`, but wrap single return types in std::type_identity which is then stripped by the `_t` shortcut:

```cpp
#include <type_traits>
#include <cstdint>
#include <cstddef>

template <size_t idx, typename head_t, typename ...pack>
    requires idx <= sizeof...(pack)
inline constexpr std::type_identity<head_t> at{};

template <size_t idx, typename head_t, typename ...pack>
    requires idx > 0 && idx <= sizeof...(pack)
inline constexpr auto at<idx, head_t, pack...> = at<idx - 1, pack...>;

template <size_t i, typename ...args_t>
using at_t = decltype(at<i, args_t...>)::type;

static_assert(std::is_same_v<int, at_t<3, bool, bool, double, int, double>>);
```

I will prepare a small PR with my current state and @rrahn can take over from there! We will only add what we need when we need it.

**Comment by smehringer** [comment]
what's the status of this?

**Comment by h-2** [comment]
Done
