### ISSUE TITLE
union_composition clean-up: noexcept

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#70]
This is a detail/discussion ticket of the meta ticket #60

* [x] add `noexcept` where adequate

**Comment by marehr** [comment]
I looked into `dna4.hpp` and found that basically every function, except for `assign_rank` has `noexcept`

I assume that is due to `assert`. But, I thought `assert` does not throw but `SIGABORT`? And when compiling with `-DNDEBUG` this code will NEVER throw/exit. Is there a macro for `noexcept` if `-DNDEBUG`?

**Comment by h-2** [comment]
That's all true. We need a different assert macro that throws, than we can make the noexcept property of `assign_rank` forward to the noexcept property of the assertion which will be true in release mode and false in debug mode.
