### ISSUE TITLE
Write 60min Alphabet tutorial

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#701]
I would do it roughly like this:

* Tell people to read the alphabet landing page from the API docs
* Make small examples that illustrate working with nucleotides. All related functions should be handled at least once with an examples that explain their use.
* Their should be some example functions that practically explain that NucleotideAlphabet is more constrainted than Alphabet since using concepts will likely be new to a lot of people.
* In the end tell readers to implement `enum class dna3 { A, C, G}` with respective free functions and make sure that it models the respective concepts.

**Comment by smehringer** [comment]
@h-2 Can you add some points that should be included in this tutorial so @joergi-w  can start working on it?

**Comment by h-2** [comment]
done

**Comment by smehringer** [comment]
thanks :)

**Comment by rrahn** [comment]
Done by #765
