### ISSUE TITLE
[follow-up] investigate two ICEs in alphabets

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#713]
1. alphabet_proxy that inherits
2. alphabet_proxy that models nucleotide

**Comment by rrahn** [comment]
@h-2 something you are going to work on before the release?

**Comment by h-2** [comment]
Not a blocker but I will try to find time for it.

**Comment by rrahn** [comment]
@h-2 what is the state?

**Comment by h-2** [comment]
resolved by #1285
