### ISSUE TITLE
Make view::make_random_access

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#720]
Some ranges can not provide random access in constant time so their iterators should not expose the corresponding interface (subscript, +=, ... etc). In order to explicitly use a range as a random access range, ignoring the performance loss, one can wrap the range in `view::make_random_access` which will expose a random access iterator.

**requirement**: bidirectional range

**implementation**: Mimic random access operators by using operator++/--, std::advance und std::distance. 

**customization point**: Our custom ranges that can handle random access more efficiently than in linear time, can overload std::advance and std::distance to boost their performance.

**Comment by h-2** [comment]
I will work on this as soon as the gap_decorator provides the discussed interface (`.begin_ra` and `.end_ra`).

**Comment by smehringer** [comment]
is this planned for the release?

**Comment by rrahn** [comment]
It is not planned since it is not a crucial feature that needs to be there for the release.
