### ISSUE TITLE
GCC9 support

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#730]
Open reports:

- [ ] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90003 (duplicate of https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89953)
- [ ] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89953

Fixed GCC9 bugs:
- #708 
- #719 
- #730
- #902 
- #986 
- #989 
- #990

**Comment by rrahn** [comment]
@h-2 is there more to do?

**Comment by h-2** [comment]
In C++17 mode we only have one error left, I am not 100% sure this is a side-affect of other (reported) issues. I'll investigate that.

In C++20 mode there are 11 tests failing, AFAICT all due to a reported and fixed issue. These will disappear with the next package upgrade likely in a week or two.

**Comment by rrahn** [comment]
Let us keep this alive until we know for sure then.

**Comment by h-2** [comment]
We still have some open issues, many related to alignment code. @rrahn Can you have a look? I think GCC9 is scheduled for late april so we should really get these reported ASAP.

**Comment by h-2** [comment]
An alignment snippet is also ICEing on GCC8-nightlies:
http://cdash.seqan.de/viewBuildError.php?buildid=303901

**Comment by rrahn** [comment]
Yes, I'll check this.

**Comment by h-2** [comment]
Can you link to all open GCC bug reports here?

**Comment by rrahn** [comment]
- [ ] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90003
- [ ] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89953

**Comment by h-2** [comment]
We now have workarounds for everything.
