### ISSUE TITLE
O(log(n)) RandomAccessIterators 

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#736]
We cannot overload std::advance or std::ranges::advance for our log-time random access iterators:
ericniebler/range-v3#1058

Since any solutions we bake won't be generic anyway, I would propose the following
  * affected classes should provide two iterators, a biderectional and a random-access-iterator (can be implemented as the same class template with a bool template parameter switch for example)
  * `begin()`, `end()`, `cbegin()`, `cend()` on the range return the bidirectional iterator
  * `begin_ra()`, `end_ra()`, `cbegin_ra()`, `cend_ra()` on the range return the random access iterator
  * `view::make_random_access` just wraps the range and delegates from its own `begin()` to the underlying `begin_ra()`. This also means the view would have no overhead, because there is no additional iteration layer

Do you agree @smehringer and @rrahn or do you want to discuss this at the next strategy meeting? 
Sorry for the back-and-forth, @smehringer .

**Comment by rrahn** [comment]
Well, the only thing that I don't like at the first glance is that the range itself exposes the random access iterator and without thinking about it to long I am afraid their might be inconsistencies between the two interfaces. Like accidentally comparing begin with end_ra iterators or being able to call random access iterator algorithms on the range iterators but not on the range itself. So in general I am feeling that for a safe interface it would be better to only expose the ra feature via the respective view.

**Comment by smehringer** [comment]
ok let's discuss this next tuesday

**Comment by h-2** [comment]
We agreed on my proposal and have #720
