### ISSUE TITLE
Support concept for doxygen.

### ISSUE THREAD

**Issue by xenigmax** [seqan/seqan3#76]
Hello.

There are 4 things regarding Concept according to the issue #72.

1. Use **cond** syntax to let Doxygen skip parsing Concept part. (since it's not able to parse them)
https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdcond

2. Use **interface** command to manualy link Concepts to the document (it will be shown as C++ interface)
http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdinterface

3. Use  **implement** and **extend** commands to manually show inheritance information of Concepts.
https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdimplements
https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdextends

4. More explanation regarding functions defined in the concept block. (They will not be shown by 1 )

You can check datailed explaination in #72. 

I **tried** to do that by myself as requested but found that it's not only a  burden for me but also very risky.
Unfortunately, I was not involving in many design discussions and not easy to figure out all the inheritance relationships between concepts. 

Instead, I listed up all the source codes contain 'concept' by grep, and made a list with author names. Please understand that I'm not able to look at all these codes and figure out how to link them correctly.
Perhaps, it's not a big deal for original authors (but not me..). _**It does not require any hacks and infrastructure-related issues. Please just change some comments that you wrote and claimed as authors when you have a time.**_ 

Since the list is made by the grep, there can be some files that does not require any modification. If it's the case, please just check the checkbox. And please let me know regarding incorrect author assignments.

Sara @sarahet 
- [ ] alphabet/nucleotide/nucl16.hpp
- [ ] alphabet/aminoacid/aa27.hpp

David & Hannes @eldariont  

Marcel & David @marehr 
- [x] alphabet/gap/gap.hpp
- [x] alphabet/gap/gapped_alphabet.hpp
- [x] alphabet/composition/union_composition.hpp
- [ ] alphabet/composition/cartesian_composition.hpp

Rene @rrahn 
- [ ] core/concept/core_detail.hpp
- [ ] core/concept/iterator_detail.hpp
- [ ] core/concept/iterator.hpp
- [ ] core/concept/core.hpp
- [ ] core/platform.hpp
- [ ] core.hpp

Joerg @joergi-w 
- [x] io/sequence/sequence_file_format.hpp

Hannes @h-2 
- [x] alphabet/nucleotide/dna5.hpp
- [x] alphabet/nucleotide/concept.hpp
- [x] alphabet/nucleotide/dna4.hpp
- [x] alphabet/nucleotide/rna5.hpp
- [x] alphabet/nucleotide/rna4.hpp
- [x] alphabet/detail/convert.hpp
- [x] alphabet/concept.hpp
- [x] alphabet/nucleotide.hpp
- [x] alphabet.hpp
- [x] container.hpp
- [ ] core/pod_tuple.hpp
- [x] range/view.hpp
- [x] range/container.hpp
- [x] range/view/to_rank.hpp
- [x] range/view/char_to.hpp
- [x] range/view/concept.hpp
- [x] range/view/to_char.hpp
- [x] range/view/convert.hpp
- [x] range/view/rank_to.hpp
- [x] range/concept.hpp
- [x] range/container/concept.hpp
- [x] range.hpp

@mariehoffmann 
- [ ] alphabet/quality/composition.hpp
- [ ] alphabet/quality/concept.hpp
- [ ] alphabet/quality/aliases.hpp
- [ ] alphabet/quality/illumina18.hpp
- [ ] alphabet/quality.hpp

No author (probably not completed yet)
- [ ] io/alignment/align_file_in.hpp
- [ ] io/alignment/align_file.hpp
- [ ] io/alignment/align_file_out.hpp
- [ ] io/alignment/align_file_detail.hpp
- [ ] io/sequence/sequence_file_in.hpp
- [ ] io/sequence/sequence_file_format_fasta.hpp

**Comment by smehringer** [comment]
Thank you for the clarification and the detailed issue. 
I'm sure it's best to let the authors do the changing (i know, easy to say being not part of them 😏)

I think @joergi-w worked a little on the align file, no?
Temesgen and me were working on the sequence_file* during the retreat, but it is not completed yet (René is working on the tokenization I think). I will take a look at those two.

**Comment by h-2** [comment]
> I  know, easy to say being not part of them

Oh, you can have some of mine, no problem 😜

**Comment by marehr** [comment]
I think this is addressed now; if someone feels it should be reopened, please do so!
