### ISSUE TITLE
bitcompressed_vector<qualified<dna4, phred42>>::iterator does not model std::InputIterator

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#764]
One of the issues to get #672 working

Note that `bitcompressed_vector<dna4>::iterator` does model std::InputIterator and `std::vector<qualified<dna4, phred42>>::iterator` does too.

Boils down to this issue:

```cpp
using bit_type = bitcompressed_vector<qualified<dna4, phred42>>;
    std::cout << detail::get_display_name_v<decltype(*std::declval<decltype((std::declval<bit_type>()).begin()) &>())>.string() << std::endl;

```

prints `unsigned char&` which is clearly wrong

**Comment by rrahn** [comment]
@smehringer what is the state here?

**Comment by smehringer** [comment]
I just filed the bug. I"m not trying to fix it. 
@eseiler didn't you take a look at this?

**Comment by eseiler** [comment]
@smehringer I think it was the #679 thing?

**Comment by smehringer** [comment]
I"m not sure but did you fix either of them?

**Comment by eseiler** [comment]
@smehringer No

**Comment by rrahn** [comment]
@smehringer can you verify if this is still an issue?
