### ISSUE TITLE
Introduce internal namespace short-cut for std::ranges

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#770]
As discussed in the last strategy meeting we will introduce an alias within seqan3 for `std::ranges` called `sr`. @h-2 checked that introducing the alias will not clash with external namespaces.

This also resolves that we aliased some "frequently used ranges stuff" in our namespace which should be removed again (e.g. begin).

**Comment by rrahn** [comment]
I think we finally voted against it. I close it but if you think this was not resolved then please reopen.
