### ISSUE TITLE
Replace common iterator type traits in favour of the iter_..._t version

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#776]
Currently we use value_t and reference_t type traits for iterators and ranges
However, the new C++ standard introduces special type traits for iterator classes, namely:
* iter_difference_t
* iter_value_t
* iter_reference_t
* iter_rvalue_reference_t
* iter_common_reference_t

The ranges library also deprecats the old type traits and forwards to the new type traits.

### Suggested changes
- [ ] Add these new names in the seqan3/std/iterator header in the std namespce and forward them to the ranges:: versions if c++20 is not available yet.
- [ ] Remove the seqan3/core/metafunction/iterator.hpp and replace all broken code with the std:: versions.

Open question: We also expose the size_type type trait as an unsigned alternative for the difference type of  the iterator, but I don't see the advantage/use case for this.
As a matter of fact, there is no single use of this type trait for iterators in our code. 
But maybe there was a particular reason for this?

**Comment by h-2** [comment]
let's discuss at the next strategy meeting

**Comment by h-2** [comment]
We should wait for after the Cologne ISO meeting and then change this for the 3.0.1 release.

**Comment by smehringer** [comment]
Did we assign someone to do this within the week?

**Comment by marehr** [comment]
Closed because #1549 supersedes this issue now.
