### ISSUE TITLE
Add "How to add another cpp to your cmake file" to the setup tutorial

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#786]
We do not document how to proceed with the following tutorials after hello_world.cpp compiles and runs.
(http://docs.seqan.de/seqan/3.0.0-master-user/setup.html)
EDIT: maybe we should just alter the CMake script so it copmiles every cpp file in `source`

**Comment by smehringer** [comment]
@marehr is this possible in a few lines of cmake code to compile every cpp file in the source directory?

**Comment by marehr** [comment]
Not, really. I can add all of them when initializing with cmake, but then you would have to manually refresh (with `cmake .`) every time you add a .cpp file.

I think this is as confusing as to copy the section of a target  in the CmakeLists.txt every time you add a new cpp file.
