### ISSUE TITLE
parse_error when loading empty FASTA file

### ISSUE THREAD

**Issue by tloka** [seqan/seqan3#823]
Problem
---
Loading empty FASTA file using sequence_file_input causes:
```
terminate called after throwing an instance of 'seqan3::parse_error'
  what():  Expected to be on beginning of ID, but (is_char<'>'> || is_char<';'>) evaluated to false on '�'
```

For me this is unexpected behavior, since e.g. pipelines could be negatively affected by throwing an exception (imagine a pipeline giving FASTA as intermediate analysis result, this file being empty (no matches => expected behavior) leading to a crash of the complete pipeline).

Proposed Solution
---
I would rather consider to return an empty field. The app developer can still decide to throw an error on empty field or to handle internally.

**Comment by smehringer** [comment]
Good point! We did not think of workflows yet.

We will probably not even return empty fields. If you are trying to iterate over an empty file, `begin == end` so there is nothing to iterate over.
