### ISSUE TITLE
Export code snippets into files that can be tested

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#83]
As done in seqan2, maybe we should not hardcode cpp example code in the documentation but instead include separate files. Those demo files might then be tested by the testing framework and this ensures that the cpp examples always work.

@xenigmax Does Doxygen support something like `\include  mycode.cpp"`

@seqan/all

**Comment by xenigmax** [comment]
It seems \snippet is the one you are looking for.
http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdsnippet

**Comment by h-2** [comment]
Initially implemented via seqan/seqan3-infrastructure#1 and used here (where it references code from test-cases):
https://github.com/seqan/seqan3/blob/master/include/seqan3/range/detail/inherited_iterator_base.hpp#L65

But we still need an example directory with a module and submodule structure that mirrors that of include where we can place examples.

I would leave for this issue as TODOs:

  - [ ] decide whether to call it `example` or `snippet`
  - [ ] add the directory `test/example` or  `text/snippet` and corresponding cmake stuff
  - [ ] add a section to https://github.com/seqan/seqan3/wiki/Writing-Documentation titled **Including example code snippets** that explains how to use snippets and that people should prefer to use snippets from existing test-cases and if that is not feasible add the code to separate files under `test/example`.

@marehr Can you do this?

After that we can create separate "good first issues" for transforming current documentation into this style.

**Comment by rrahn** [comment]
please don't do it now. We have other things to do, that are more important. I will soon compile a list of things that need to be done before we have our workshops in September

**Comment by marehr** [comment]
This will be closed and the open wiki point will be addressed in #425
