### ISSUE TITLE
noexcept version/macro for function that use assert, i.e. only throw in debug mode

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#85]
> I looked into `dna4.hpp` and found that basically every function, except for `assign_rank` has `noexcept`
>
> I assume that is due to `assert`. But, I thought `assert` does not throw but `SIGABORT`? And when compiling with `-DNDEBUG` this code will NEVER throw/exit. Is there a macro for `noexcept` if `-DNDEBUG`?
> -- marehr

> That's all true. We need a different assert macro that throws, than we can make the noexcept property of `assign_rank` forward to the noexcept property of the assertion which will be true in release mode and false in debug mode.
> -- h-2

See original discussion:
* https://github.com/seqan/seqan3/issues/70#issuecomment-302068259
* https://github.com/seqan/seqan3/issues/70#issuecomment-302085232

**Comment by h-2** [comment]
@cpockrandt Could you maybe look into this? The most basic version would be

You could look at https://github.com/foonathan/debug_assert for inspiration, although it seems a little over-engineered. OTOH we had stack-unwinding in SeqAn2, that would be nice to have.

**Comment by smehringer** [comment]
We will revisit this issue once contracts are in
