### ISSUE TITLE
--license to print copyright

### ISSUE THREAD

**Issue by tloka** [seqan/seqan3#862]
There are many tools printing the copyright/license information using `--license` instead of `--copyright`.
I think it would make sense to print the license information with either of both parameters (`--license` or `--copyright`).

**Comment by smehringer** [comment]
I'm fine with adding this and it's only a one-liner in the initialisation function of the argument parser. 
Can you make a PR for this? :)
(you probably did that but just in case: remember to add the `--licence` to the `used_options_ids`)

**Comment by rrahn** [comment]
We will reevaluate this later!

See https://github.com/seqan/seqan3/projects/7#card-27120401
