### ISSUE TITLE
Template deduction produces errors in `view_drop_view_take_benchmark.cpp`

### ISSUE THREAD

**Issue by mariehoffmann** [seqan/seqan3#868]
Can't compile successfully performance benchmarks. Stop at `view_drop_view_take_benchmark`. Deduction of `ranges::take_view::size()` in `v3/view/take.hpp` fails. [Complete terminal output here](https://gist.github.com/mariehoffmann/342875d79208e2796bed7326abf4f72c). Just merged with current master head (last commit dcf2eaab97249aff088d98ab537326f3f13b60d5).
```script
range-v3/include/range/v3/view/take.hpp:155:30: error: no matching function for call to 'ranges::take_view<ranges::drop_view<ranges::take_view<ranges::drop_view<ranges::ref_view<std::__cxx11::list<unsigned char> > > > > >::size()'
                     auto s = static_cast<range_difference_t<Rng>>(size());
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by h-2** [comment]
Your submodules are not up to date (you should see this when running `git status`). Run `git submodule update --init` to update them.

**Comment by mariehoffmann** [comment]
Hmm, this is my standard procedure, BUT this time I did the `fetch upstream` AFTER the update :/ 
All benchmark are compiling now.
