### ISSUE TITLE
Final refactoring of alphabets

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#869]
These are the discussed changes and some smaller additions by me not yet discussed.
@seqan/core please have a look and give me objections ASAP since I want to start working on this very soon.

`seqan3::SemialphabetConcept`:
  * refines `std::StrictTotallyOrdered` (order required to respond to ranks)
  * refines `std::Copyable` and requires `std::is_trivially_copyable`
  * requirement for `std::Regular` is dropped, but recommended for all type definitions
  - [x] `to_rank` customisation point object
    * looks for member function
    * looks for free function via ADL
    * not  picked up via ADL itself
  * [x] `alphabet_size_v`
    * looks for static member variable `::alphabet_size` (now it's `::value_size` – a weird name leftover from SeqAn2)
    * looks for constexpr free function via ADL `alphabet_size()` which makes it possible to define your own alphabet without overriding the metafunction in SeqAn

`seqan3::WritableSemialphabetConcept`:
  * refines `seqan3::SemialphabetConcept`
  * [x] `assign_rank_to(rank, alph)` customisation point object
    * was `assign_rank(alph, rank)` in seqan2-(target, source)-style; new style is more intuitive and allows for `assign_rank_to<dna5>(rank)` instead of explicit construction `assign_rank(dna5{}, rank)` [also necessary because we don't require regularity anymore]
    * looks for `assign_rank(rank)` member function
    * looks for `assign_rank_to(rank, alph)` free function via ADL
    * not  picked up via ADL itself
    * the CPO defines a generic overload for `assign_rank_to(rank, alph &&)` so this does not have to be customised (only the overload for lvalue-references has to be customised).

`seqan3::AlphabetConcept`
  * refines `seqan3::SemialphabetConcept`
  * [x] `to_char` customisation point analogous to above
 
`seqan3::WritableAlphabetConcept`
  * refines `seqan3::AlphabetConcept` and `seqan3::WritableSemialphabetConcept`
  * [x]  `assign_char_to(char, alph)` customisation point object analogous to `assign_rank_to(rank, alph)` 

PLUS `Constexpr` versions of all of the above in `seqan3::detail::`.

  - [x] Note that `underlying_rank_t` and `underlying_char_t` will be renamed to `alphabet_rank_t` and `alphabet_char_t` and will not be customisation points, they always resolve to the return type of `to_char()` and `to_rank().

  - [x] rename `alphabet_size_v` -> `alphabet_size`
  - [x] rename `::value_size` -> `alphabet_size`

**Comment by eseiler** [comment]
In general I agree. I'm just wondering why we are dropping the std::Regular requirement. How will we adjust all the, e.g., unit tests where we require to default construct a alphabet?

**Comment by h-2** [comment]
We don't have to adapt our tests because our alphabets will still be Regular. We just don't require it.

The reason was, as discussed in escala, that default constructability is not required by interfaces that only consume alphabets and that it prevents references from modelling the concepts.

**Comment by smehringer** [comment]
Hm... didn't we have the function style guide for parameters `(out, in/out, in)`? the proposed changes to the free functions would be inconsistent with this..

**Comment by h-2** [comment]
> Hm... didn't we have the function style guide for parameters (out, in/out, in)? the proposed changes to the free functions would be inconsistent with this..

No, that was SeqAn2-style. In SeqAn3 it's "natural order" and has been since day 1:
https://github.com/seqan/seqan3/wiki/Functions#function-argument-number-and-order

**Comment by smehringer** [comment]
Then I'm fine with the changes

**Comment by eseiler** [comment]
> We don't have to adapt our tests because our alphabets will still be Regular. We just don't require it.
So we implicitly require it for our alphabets then.
> The reason was, as discussed in escala, that default constructability is not required by interfaces that only consume alphabets and that it prevents references from modelling the concepts.
Ok.

I agree.

**Comment by rrahn** [comment]
looks good to me.

**Comment by rrahn** [comment]
is this done?

**Comment by h-2** [comment]
Yep
