### ISSUE TITLE
aa10li

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#877]
Same as #876 but with the following clustering:
[ASTX][BDEQZ][CU][FWY*][G][HN][IV][JLM][KOR][P]

Reference for the documentation:
T. Li, K. Fan, J. Wang, and W. Wang. Reduction of protein sequence complexity by
residue grouping. Protein Eng., 16(5):323–330, May 2003.

**Comment by sarahet** [comment]
implemented via seqan/seqan3#940
