### ISSUE TITLE
Argument parser - export of file format (ctd) for KNIME engine 

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#89]
Can be partly adapted by seqan2.

**Comment by smehringer** [comment]
Will be reopened if planned for a sprint

**Comment by SGSSGene** [comment]
We moved the argument parser into its own repo: [sharg-parser](https://github.com/seqan/sharg-parser)

This feature is being implemented by this PR here https://github.com/seqan/sharg-parser/pull/94
