### ISSUE TITLE
Add valid_file_extensions function to alignment file and structured files. (see sequence_file)

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#892]

**Comment by rrahn** [comment]
Make it a detail function. 
And adapt the input file and output file to take a file type.

**Comment by smehringer** [comment]
is this really done? I thought the PR was only for sequence files, then we should keep the issue for the other files.

**Comment by rrahn** [comment]
Yep this done

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
