### ISSUE TITLE
views need extra documentation entry for header

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#895]
Since adaptors don't get their own documentation, the views don't have an entry for which header file provides them. This confused people on the retreat.

**Comment by rrahn** [comment]
Add `\headerfile` in documentation of view definitions, as they are not shown correctly by doxygen. 
@MitraDarja Can you work on this. You can come to me if you have questions for this.

**Comment by rrahn** [comment]
fixed by #1004
