### ISSUE TITLE
Index / search re-design

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#898]
These points are based on our discussions:

* make the indexes *not* be templates over text/alphabet
* store some run-time information in the index to prevent misuse:
  * dimension of text
  * size of alphabet
  * possibly a char-rank conversion table generated from alphabet
* indexes will be easier to (de)serialise
* `search(queries, index, cfg)`
  * static asserts against certain configs that need text (like configs with in-text-verification)
  * only allows an alphabet for `queries` that passes the index's alphabet checks
* `search(queries, text, index, cfg)`
  *  only allows an alphabet for `text` that passes the index's alphabet checks; same dimension
  * allows any alphabet for queries that is convertible to the text alphabet

**Comment by smehringer** [comment]
we don't label stuff with epic?

**Comment by rrahn** [comment]
Yeah it was done automatically. I removed the label and hope that it won't get added automatically again in the future

**Comment by cpockrandt** [comment]
Notes from meeting:

* `cur.path_label([text])` performs LF-mappings to retrieve the searched sequence if no text is supported.
* store information in index: collection, semi_alphabet, alphabet_size (check always in search interface), alph_table (check only in debug mode)

**Comment by eseiler** [comment]
```
template <bool collection, bool bi>
fm_index_iterator
```
