### ISSUE TITLE
Provide debug_stream for a custom type without pulling the complete library in.

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#905]
We decided on the following design:

```
core/debug_stream.hpp
core/debug_stream_detail.hpp
```

debug_stream_detail.hpp:
* `include <iosfwd>`
* debug_stream definition, no overloads

foobar.hpp:
* `include <debug_stream_detail.hpp>`
* overload of `operator<<(debug_stream_type, foobar const &)`

debug_stream.hpp
* `include <iostream>`
* `include <debug_stream_detail.hpp>`
* overloads of stuff that doesn't have own files, like built-in types, ranges

https://github.com/seqan/seqan3/issues/905#issuecomment-494002847

-------
~~I would like to discuss this at a strategy meeting.~~
~~relates to #510 ~~

**Comment by marehr** [comment]
We discussed this in the dev meeting.

We will introduce a `seqan3::to_string` implementation, which can be overloaded for seqan3 types that should be printed in a special way. This will decouple the overload for debug_stream from a seqan3 type and we don't need to pull in debug_stream.

How it should work then:

```c++
// seqan3/my_type.hpp
#include <string>
namespace seqan3
{
struct my_type;
std::string seqan3::to_string(seqan3::my_type); // overload
}

// as you can see no #include <seqan3/../debug_stream.hpp>
```

This will be provided
```c++
// seqan3/io/stream/debug_stream.hpp

// something like this
template <typename type_t>
  requires requires(type_t value){ {seqan3::to_string(value);} }
inline debug_stream_type & operator<<(debug_stream_type & s, alphabet_t const l)
//!\cond
    requires !OStream<std::ostream, alphabet_t>
//!\endcond
{
    return s << to_char(l);
}
```

**Comment by smehringer** [comment]
wait before you work on this! @h-2 had some thoughts why this may not work

**Comment by h-2** [comment]
Yes, we need to consider that we explicitly added our own format flags to the stream. They can switch between utf8 and ASCII and the can make [u]int8_t printable as numbers. We loose this ability if everything is converted to string before going to the debug_stream.

**Comment by h-2** [comment]
Ok, so we decided on the following design:

```
core/debug_stream/alphabet.hpp
core/debug_stream/alphabet.hpp
core/debug_stream/alphabet.hpp

**Comment by h-2** [comment]
Ok, new plan:

```
core/debug_stream.hpp
core/debug_stream_detail.hpp
```

debug_stream_detail.hpp:
* include <iosfwd>
* debug_stream definition, no overloads

foobar.hpp:
* include <debug_stream_detail.hpp>
* overload of `operator<<(debug_stream_type, foobar const &)`

debug_stream.hpp
* include <iostream>
* include <debug_stream_detail.hpp>
* overloads of stuff that doesn't have own files, like built-in types, ranges
