### ISSUE TITLE
[BUG] in view_take_until_and_consume

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#950]
If you add the following test to `take_line` it fails:
```cpp
TEST(view_take_line, eol_at_first_position)
{
    using sbt = std::istreambuf_iterator<char>;
    std::istringstream vec{"\nfoo"};
    auto stream_view = std::ranges::subrange<decltype(sbt{vec}), decltype(sbt{})> {sbt{vec}, sbt{}};
    EXPECT_EQ("", std::string(stream_view | view::take_line));
    EXPECT_EQ("foo", std::string(stream_view | view::take_line));
}

```

The problem is, that the iterator does not consume upon comparison, only upon incrementing which lets an input stream with take_line run into an infinite loop when the very first character is a character that evaluates `fun` to `true`.

I swa no elegant solution at first glance.

**Comment by smehringer** [comment]
@h-2 do you have time to take a look? I already found the bug I just don't know what's the best way to fix this (I would probably just add another if clause in the comparison operator but this would be inefficient.. Maybe on construction of the iterator?)

**Comment by rrahn** [comment]
I would do it in the construction of the iterator. If fun evaluates to true, it should consume until fun is not true anymore and set the at_end_gracefully.
