### ISSUE TITLE
documentation of views

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#99]
* view properties needs to be improved so that people understand the consequences
* most current views don't have `\ingroup view` set, yet
* remove Complexity
* remove Thread safety and Exception?

**Comment by h-2** [comment]
For views I would propose this table:

* `irng_t` is the type of the range passed in
* `rrng_t` is the type of the range returned (purposefully avoided the term "output")

The default values, met by e.g. `ranges::view::reverse`

|                                              | default                                   |
|----------------------------------------------|----------------------------------------------|
| concepts required of `irng_t`    | `input_range_concept<irng_t>` | 
| concepts met by `rrng_t`         | *same as `irng_t`*                   | 
| `value_type_t<rrng_t>`            | `value_type_t<irng_t>`             | 
| `const`-iterable                       | *unknown*                               | 

The table for `view::to_char`

|                                              | `seqan3::view::to_char`            |
|----------------------------------------------|----------------------------------------------|
| concepts required of `irng_t`    | `input_range_concept<irng_t> && alphabet_concept<value_type_t<irng_t>>` | 
| concepts met by `rrng_t`         | *same as `irng_t`*                   | 
| `value_type_t<rrng_t>`            | `char_type_t<value_type_t<irng_t>>` | 

|                                              | `seqan3::view::translate_frames` |
|----------------------------------------------|----------------------------------------------|
| concepts required of `irng_t`    | `random_access_range_concept<irng_t> && sized_range_concept<irng_t> && nucleotide_concept<value_type_t<irng_t>>` | 
| concepts met by `rrng_t`         | *same as `irng_t`*                   | 
| `value_type_t<rrng_t>`            | range of `value_type_t<irng_t>` |

**Comment by sarahet** [comment]
For ```seqan3::view::translate_frames``` is ```nucleotide_concept<value_type_t<rrng_t>>``` not valid. For single frame translation the returned range contains amino acids and cannot fulfill the nucleotide concept. 
In addition for multi-frame translation it is a range of ranges for 2, 3 or 6 frame translation. How do we want to document those cases in general where we have a range of ranges returned (concerning the underlying types)?

**Comment by h-2** [comment]
@sarahet I think we can just add more entries, if there are more things to document, see above. 
Let's move the discussion of the actual values over to #56

**Comment by h-2** [comment]
fixed via #103
