### ISSUE TITLE
Remaining Alphabet TODOs

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#999]
The following things still need to be done:

  1. `NucleotideAlphabet`:
    * make  `complement()` be a customisation point object
  2. `QualityAlphabet`:
    * split into `QualityAlphabet` and `WritableQualityAlphabet`
    * make `assign_phred_to` and `to_phred` be customisation point objects
  3. `RnaStructureAlphabet`
    * make the global functions customisation point objects

At the end of these changes, `alphabet/concept_pre.hpp` and `alphabet/detail/member_exposure.hpp` can be deleted.

@joergi-w This is quite important for the release. Can you take care of it? It should be mostly copy and pasting the changes I did to the regular alphabets. Only for the quality alphabets one should do a quick scan where the concept is currently used and where one might need to change requirements to `WritableQualityAlphabet`.
If you have any questions, I am happy to help!

**Comment by joergi-w** [comment]
Yes, I started today and finished task 1.
The `NucleotideAlphabet` requires `WritableAlphabet` and not just `Alphabet`, right?

**Comment by h-2** [comment]
No, the NucleotideAlphabet only adds a function that is read-only and does not depend on any of the assign_ functions so it only refines `Alphabet`.

For Quality we have a Writable concept and a regular one, they each refine also the regular and the Writable base concepts.

**Comment by joergi-w** [comment]
This is solved with PR #1024.
